AFS_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Plan_OI__c</fullName>
        <label>Account Plan OI%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Client_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <description>Reflects Client Portfolio Management (CPM) classification (Diamond, Foundation, Portfolio or Opportunistic).</description>
        <label>Client Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Mega Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunistic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_QA_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client QA Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Managing_Director_MC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MC Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operations_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operations Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P_Global_Client_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Executive responsible for managing the relationship with an AFS Client. Global Client Account Lead may oversee several Clients.</description>
        <label>Global Client Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Technology_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technology Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>The entity who will receive the services or products AFS provides (e.g., DC Department of Healthcare Finance). Selecting this Account Record Type will allow you to create a new AFS client to associate with new opportunities, contacts, and/or activities.</description>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Portfolio</fullName>
        <active>true</active>
        <description>The Entity (e.g., AFS or ASM), Portfolio (e.g., Civilian), or Sub-Portfolio (e.g., Citizen Services) to which many client accounts are aligned. Selecting this Account Record Type will allow you to create a new Entity, Portfolio, or Sub-Portfolio.</description>
        <label>Portfolio</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Plan_OI__c</fullName>
        <label>Account Plan OI%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Actual_Contract_Sign_Date__c</fullName>
        <inlineHelpText>Date the contract was signed by the client. Date field must always be after the Draft RFP Release Date, RFP Release Date, Proposal Submission Date, but may equal to the Expected Contract Sign Date.</inlineHelpText>
        <label>Actual Contract Sign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approved_Status_Stage__c</fullName>
        <inlineHelpText>Status/Stage the Sales Ops will approve the opportunity record to once the opportunity has gone through all approval processes</inlineHelpText>
        <label>Approved Status/Stage</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Best_Probable_Worst__c</fullName>
        <inlineHelpText>The scenario for AFS winning the deal. 
Worst Case: AFS would win in the worst case scenario. 
Probable Win: A win is likely. 
Probable Loss: A win is unlikely. 
Best Case: We would only win in the best case scenario. 
Exclude: Exclude from forecast.</inlineHelpText>
        <label>Best/Probable/Worst</label>
        <picklist>
            <picklistValues>
                <fullName>Exclude</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Best</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Possible Loss</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Probable Win</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Worst</fullName>
                <color>#78C953</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <formula>TEXT(Account.Client_Classification__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Classification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_QA_Director__c</fullName>
        <formula>Account.Client_QA_Director__r.FirstName  &amp; &quot; &quot; &amp;  Account.Client_QA_Director__r.LastName</formula>
        <label>Client QA Director</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consulting_End__c</fullName>
        <inlineHelpText>Start/End Dates should reflect the base award/booked sale represented by the Total Current Revenue</inlineHelpText>
        <label>Consulting End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Consulting_Start__c</fullName>
        <inlineHelpText>Date the Consulting portion of the contract is expected to begin. Field is required if the Financial Details Related List includes MC, SI, or TC Service Groups.</inlineHelpText>
        <label>Consulting Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Draft_RFP_Release_Date__c</fullName>
        <inlineHelpText>Anticipated release date of the Draft RFP. This date field may be equal to or before the &quot;RFP Release&quot; date field.</inlineHelpText>
        <label>Draft RFP Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Level__c</fullName>
        <description>Standalone (or Full &amp; Open): Procurement issued as a standalone contract; opportunities that are not a Contract Vehicle or Task Order under a Contract Vehicle should be classified as Standalone. 

Contract Vehicle: Procurement is an IDIQ or BPA vehicle that AFS is pursuing as a new award. 
 
Task Order: Procurement is a Task Order issued on an existing Contract Vehicle.</description>
        <inlineHelpText>Standalone: Indicates if a procurement is full and open

Contract Vehicle: IDIQ/BPA

Task Order: Opportunity under an existing contract vehicle</inlineHelpText>
        <label>Hierarchy Level</label>
        <picklist>
            <picklistValues>
                <fullName>Contract Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standalone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Managing_Director_MC__c</fullName>
        <formula>Account.Managing_Director_MC__r.FirstName &amp; &quot; &quot; &amp; Account.Managing_Director_MC__r.LastName</formula>
        <label>MC Account Lead</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outsourcing_End__c</fullName>
        <inlineHelpText>Date the Outsourcing portion of the contract will be complete.</inlineHelpText>
        <label>Outsourcing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_Start__c</fullName>
        <inlineHelpText>Start/End Dates should reflect the base award/booked sale represented by the Total Current Revenue</inlineHelpText>
        <label>Outsourcing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposal_Submission_Date__c</fullName>
        <inlineHelpText>Date AFS submitted the proposal. The Proposal Submission Date should always be before both the Expected Contract Sign Date and Actual Contract Sign Date.</inlineHelpText>
        <label>Proposal Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFP_Release_Date__c</fullName>
        <inlineHelpText>Date RFP was released. This field is used for tracking purposes. This date field must always come before the &quot;Proposal Submission Date&quot; field but may be equal to the Draft RFP Release Date.</inlineHelpText>
        <label>RFP Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Status_Since__c</fullName>
        <inlineHelpText>Tracks the date that an opportunity advancement request was submitted. Reporting Status Date is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Status__c</fullName>
        <inlineHelpText>Field updated based on the stage of the opportunity through workflow. Reporting Status is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status</label>
        <picklist>
            <controllingField>Approved_Status_Stage__c</controllingField>
            <picklistValues>
                <fullName>Lost</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
                <color>#A845DC</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Stage_Requested__c</fullName>
        <inlineHelpText>Use this field to request advancement to a subsequent stage when all required fields are complete.
Please note: there may be additional fields on the Related Lists (e.g., Financial Details, Attributes, Opp Team Roles) that are required for advancement.</inlineHelpText>
        <label>Status/Stage Requested</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Technology_Account_Lead__c</fullName>
        <formula>Account.Technology_Account_Lead__r.FirstName &amp; &quot; &quot; &amp;  Account.Technology_Account_Lead__r.LastName</formula>
        <label>Technology Account Lead</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Win_Probability__c</fullName>
        <inlineHelpText>The likelihood of winning. Win Probability is linked to BPW. 
Worst Case: 70, 90, or 100% 
Probable Win: 50% or 70% 
Possible Loss: 35% or 50% 
Best Case: 10%</inlineHelpText>
        <label>Win Probability</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>35</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/classes/AccountBLTest.cls
/**
 * Class Name: AccountBLTest
 * @author: Lhea Valencia
 * Date: 04/21/2015
 * Test Class for Account BL
 Test for jenkins
 */
@isTest(SeeAllData=true)
private class AccountBLTest {

    private static Account clientAcc;
    private static Account recordAcc;
    private static Account recordAcc2;
    private static Account recordAcc3;
    private static Account recordAcc4;
    private static Account recordAcc5;
    private static Account recordAcct;
    private static Opportunity OppAccountPlanOIValid;
    private static Opportunity OppAccountPlanOIInvalid; 
    private static Id accountID;
    private static Id userID;
    private static final Id PORTFOLIO_REC_TYPE  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Portfolio').getRecordTypeId();
    private static final Id CUSTOMER_REC_TYPE  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Summary Customer').getRecordTypeId();
    private static final Id CLIENT_REC_TYPE  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
    
    
    /*    
    * @Method Define scope of testmethod.    
    */
    private static void prepdata() {
        
        /*
        * - Test User
        */
        
        Profile p = [select id from profile where name='System Administrator' limit 1];
        
        User u = new User(
        alias = 'user1A',
        email='user1@sample.com',
        emailencodingkey='UTF-8',
        lastname='DOe',
        languagelocalekey='en_US',
        localesidkey='en_US',
        profileid = p.Id,
        timezonesidkey='America/Los_Angeles',
        username='user1@sample.com.dev'
        );
        Database.insert(u, true);
        userID = u.Id;
        
        User usr2 = new User(
        alias = 'user2Abc',
        email='user1@sample.com',
        emailencodingkey='UTF-8',
        lastname='DOeh',
        languagelocalekey='en_US', 
        localesidkey='en_US',
        profileid = p.Id,
        timezonesidkey='America/Los_Angeles',
        username='user2@sample.com.dev'
        );
        Database.insert(usr2, true);
        


        /*
        * - Test Account
        */
        
        Account testAcc = new Account(
        RecordTypeId = PORTFOLIO_REC_TYPE,
        name = 'Sample Test Account Acc',
        Status__c = 'Active',
        Type = 'AFS'
        );
        Database.insert(testAcc, true);
        
        Account testAcc2 = new Account(
        RecordTypeId = PORTFOLIO_REC_TYPE,
        name = 'Sample Test Account Acc22',
        Status__c = 'Active',
        Type = 'Portfolio',
        ParentId = testAcc.Id,
        Account_Plan_OI__c = 80
        );
        Database.insert(testAcc2, true);
                
        Account testAcc20 = new Account(
        RecordTypeId = CLIENT_REC_TYPE,
        name = 'Sample Test Account Acc220',
        Status__c = 'Active',
        Type = 'Client',
        Client_Account_Lead__c = u.id,
        Client_Classification__c = 'Diamond',    
        Account_Plan_OI__c = 80
        );
        Database.insert(testAcc20, true);
        testAcc20.Account_Plan_OI__c = 90;
        Database.update(testAcc20, true);
        accountID = testAcc20.Id;
        
        Account testAcc3 = new Account(
        RecordTypeId = PORTFOLIO_REC_TYPE,
        name = 'Sample Test Account Acc223',
        Status__c = 'Active',
        Type = 'Sub Portfolio',
        ParentId = testAcc2.Id
        );
        Database.insert(testAcc3, true);
            
        Account testAcc7 = new Account(
        RecordTypeId = PORTFOLIO_REC_TYPE,
        name = 'Sample Test Account Acc22377',
        Status__c = 'Active',
        Type = 'Sub Portfolio',
        ParentId = testAcc2.Id
        );
        Database.insert(testAcc7, true);
        recordAcc2 = testAcc7;
        
        Account testAcc6 = new Account(
        RecordTypeId = CUSTOMER_REC_TYPE,
        name = 'Sample Test Account Acc2266',
        Status__c = 'Active',
        Type = 'Customer',
        ParentId = testAcc7.Id
        );
        Database.insert(testAcc6, true);
        recordAcc = testAcc6;
        
        Account testAcc4 = new Account(
        RecordTypeId = CUSTOMER_REC_TYPE,
        name = 'Sample Test Account Acc2234',
        Status__c = 'Active',
        Type = 'Customer',
        ParentId = testAcc3.Id
        );
        Database.insert(testAcc4, true);
        recordAcct = testAcc4;
            
        Account testAcc8 = new Account(
        RecordTypeId = CLIENT_REC_TYPE,
        name = 'Sample Test Account Acc22384',
        Status__c = 'Active',
        ParentId = testAcc6.Id,
        Type = 'Client'
        );
        Database.insert(testAcc8, true);
        recordAcc3 = testAcc8;
        
        Account testAcc9 = new Account(
        RecordTypeId = CUSTOMER_REC_TYPE,
        name = 'Sample Test Account Acc2238445',
        Status__c = 'Active',
        Type = 'Customer',
        ParentId = testAcc3.Id
        );
        Database.insert(testAcc9, true);
        recordAcc5 = testAcc9;
        
        Account testAcc5 = new Account(
        RecordTypeId = CLIENT_REC_TYPE,
        ParentId = testAcc4.Id,
        name = 'Sample Test Account Acc3336',
        Status__c = 'Active',
        Type = 'Client',
        Client_Account_Lead__c = u.id,
        Client_QA_Director__c = usr2.id,
        P_Global_Client_Account_Lead__c = u.id,
        Managing_Director_MC__c = usr2.id,
        Operations_Lead__c = u.id,
        Technology_Account_Lead__c = usr2.id,
        Client_Classification__c = 'Diamond'
        );
        Database.insert(testAcc5, true);
        recordAcc4 = testAcc5;
        
    /*
    * - Test Opportunity
    */
        
        Opportunity testOpp = new Opportunity(
        Name = 'Opportunity Test Class 033341',
        AccountId = accountID,
        STATUS_STAGE_REQUESTED__C = '0',
        Draft_RFP_Release_Date__c = System.today() + 80,
        RFP_RELEASE_DATE__C = System.today() + 90,
        Proposal_Submission_Date__c = System.today() + 95,
        Actual_Contract_Sign_Date__c = System.today() + 110,
        CLOSEDATE = System.today() + 115,
        REPORTING_STATUS_SINCE__C = System.today() - 30, 
        TYPE = 'Competitive',
        STAGENAME = '0',
        APPROVED_STATUS_STAGE__C = '0',
        REPORTING_STATUS__C = 'Qualified',
        Consulting_Start__c  = System.today() + 120,
        Consulting_End__c = System.today() + 210,   
        Outsourcing_Start__c = System.today() + 150, 
        Outsourcing_End__c  = System.today() + 240 
        );
        Database.insert(testOpp,true);
        
        // Confirm that record is inserted
        System.assertNotEquals(null, testOpp.Id);


        


        
        Account afs = new Account ();
        afs.RecordTypeId = PORTFOLIO_REC_TYPE;
        afs.Name = 'AFS Sample Account';
        afs.Status__c = 'Active';
        afs.Type = 'AFS';
        Database.insert (afs, true);
        
        Account port = new Account ();
        port.RecordTypeId = PORTFOLIO_REC_TYPE;
        port.Name = 'Portfolio Sample Account';
        port.Status__c = 'Active';
        port.Type = 'Portfolio';
        port.ParentId = AFS.Id;
        Database.insert (port, true);
        
        Account subPort = new Account ();
        subPort.RecordTypeId = PORTFOLIO_REC_TYPE;
        subPort.Name = 'SubPortfolio Sample Account';
        subPort.Status__c = 'Active';
        subPort.Type = 'Sub Portfolio';
        subPort.ParentId = Port.Id;
        Database.insert (subPort, true);    

        Account customer = new Account();
        customer.RecordTypeId = CUSTOMER_REC_TYPE;
        customer.Name = 'Customer Sample Account';
        customer.Status__c = 'Active';
        customer.Type = 'Customer';
        customer.ParentId = SubPort.Id;
        Database.insert (customer, true);       

        Account client = new Account();
        client.RecordTypeId = CLIENT_REC_TYPE;
        client.Name = 'Client Sample Account';
        client.Status__c = 'Active';
        client.Type = 'Client';
        client.Account_Plan_OI__c = 75;
        client.ParentId = Customer.Id;
        Database.insert (client, true);
        clientAcc = client;

    /*
    * - Test Opportunity for Account Plan OI Valid
    */
        
        Opportunity testOppAccPlanOIValid = new Opportunity(
        Name = 'Opportunity For Account OI Valid',
        AccountId = clientAcc.Id,
        Approved_Status_Stage__c = '0',
        STATUS_STAGE_REQUESTED__C = '0',
        Draft_RFP_Release_Date__c = System.today() + 80,
        RFP_RELEASE_DATE__C = System.today() + 90,
        Proposal_Submission_Date__c = System.today() + 95,
        Actual_Contract_Sign_Date__c = System.today() + 110,
        CLOSEDATE = System.today() + 115,
        REPORTING_STATUS_SINCE__C = System.today() - 30, 
        TYPE = 'Competitive', 
        STAGENAME = '0',
        REPORTING_STATUS__C = 'Unqualified',
        Consulting_Start__c  = System.today() + 120,
        Consulting_End__c = System.today() + 210,   
        Outsourcing_Start__c = System.today() + 150, 
        Outsourcing_End__c  = System.today() + 240 
        );
        Database.insert(testOppAccPlanOIValid,true);
        OppAccountPlanOIValid = testOppAccPlanOIValid;      

    /*
    * - Test Opportunity for Account Plan OI Invalid
    */
        
        Opportunity testOppAccPlanOIInvalid = new Opportunity(
        Name = 'Opportunity For Account OI Invalid',
        AccountId = clientAcc.Id,
        Approved_Status_Stage__c = '0',
        STATUS_STAGE_REQUESTED__C = '0',
        Draft_RFP_Release_Date__c = System.today() + 80,
        RFP_RELEASE_DATE__C = System.today() + 90,
        Proposal_Submission_Date__c = System.today() + 95,
        Actual_Contract_Sign_Date__c = System.today() + 110,
        CLOSEDATE = System.today() + 115,
        REPORTING_STATUS_SINCE__C = System.today() - 30, 
        TYPE = 'Competitive', 
        STAGENAME = '0',
        REPORTING_STATUS__C = 'Unqualified',
        Consulting_Start__c  = System.today() + 120,
        Consulting_End__c = System.today() + 210,   
        Outsourcing_Start__c = System.today() + 150, 
        Outsourcing_End__c  = System.today() + 240 
        );
        Database.insert(testOppAccPlanOIInvalid,true);
        OppAccountPlanOIInvalid = testOppAccPlanOIInvalid;  
        
        
    }
    

    
    /* 
    * @Method Define scope of testmethod.
    */
    static testmethod void testIfAccount(){
        //Line 31
        Profile p = [select id from profile where name='System Administrator' limit 1];
        
        /*
        * - Test User
        */
        
        User u = new User(
        alias = 'user16',
        email='user1@sample.com',
        emailencodingkey='UTF-8',
        lastname='DOee',
        languagelocalekey='en_US',  
        localesidkey='en_US',
        profileid = p.Id,
        timezonesidkey='America/Los_Angeles',
        username='user111@sample.com.dev'
        );
        Database.insert(u, true);
        
        /*
        * - Test Account
        */
    
        RecordType clientRecordType = [Select Id FROM RecordType WHERE Name = 'Client' LIMIT 1];
        
        Account testAcc = new Account(
        RecordTypeId = clientRecordType.Id,
        name = 'Sample Test Account Acc',
        Status__c = 'Active',
        Type = 'Client',
        Client_Account_Lead__c = u.id,
        Client_Classification__c = 'Diamond'
        );
        Database.insert(testAcc, true);
        
        // Confirm that record is inserted
        System.assertNotEquals(null, testAcc.Id);
    }
    
    //Line 33
    /* 
    * @Method Define scope of testmethod.
    */
    static testmethod void testElseAccount(){
        
        /*
        * - Test User
        */
        
        Profile p = [select id from profile where name='System Administrator' limit 1];
        
        User u = new User(
        alias = 'user16',
        email='user1@sample.com',
        emailencodingkey='UTF-8',
        lastname='DOee',
        languagelocalekey='en_US',   
        localesidkey='en_US',
        profileid = p.Id,
        timezonesidkey='America/Los_Angeles',
        username='user11@sample.com.dev'
        );
        Database.insert(u, true);
        
        User usr2 = new User(
        alias = 'user2Ab0',
        email='user1@sample.com',
        emailencodingkey='UTF-8',
        lastname='DOehh',
        languagelocalekey='en_US',  
        localesidkey='en_US',
        profileid = p.Id,
        timezonesidkey='America/Los_Angeles',
        username='user22@sample.com.dev'
        );
        Database.insert(usr2, true);
        
        /*
        * - Test Account
        */
        
        Account testAcc6 = new Account(
        RecordTypeId = CUSTOMER_REC_TYPE,
        name = 'Sample Test Account Acc22666',
        Status__c = 'Active',
        Type = 'Customer'
        );
        Database.insert(testAcc6, false);
        recordAcc = testAcc6;
        
        Account testAcc10 = new Account(
        RecordTypeId = CLIENT_REC_TYPE,
        name = 'Sample Test Account Acc2238466',
        Status__c = 'Active',
        ParentId = testAcc6.Id,
        Type = 'Client'
        );
        Database.insert(testAcc10);
        
        // Confirm that record is inserted
        System.assertNotEquals(null, testAcc10.Id);
    }
    
    //Line 143
    /* 
    * @Method Define scope of testmethod.
    */
    static testmethod void testValidAccount(){
        
        /*
        * - Test Account
        */
 
        Account testAcc001 = new Account(
        RecordTypeId = PORTFOLIO_REC_TYPE,
        name = 'Sample Test Account Account',
        Status__c = 'Active',
        Type = 'AFS',
        Account_Plan_OI__c = 0
        );
        Database.insert(testAcc001, true);
        testAcc001.Account_Plan_OI__c = 100;
        Database.update(testAcc001, true);
        
        // Confirm that record is inserted
        System.assertNotEquals(null, testAcc001.Id);
    }
    
    
    /* 
    * @Method Define scope of testmethod.
    */
    static testmethod void queryValidAccount(){
        
        /*
        * - Test Account
        */
 
        Account testAcc002 = new Account(
        RecordTypeId = CLIENT_REC_TYPE,
        name = 'Sample Test Account Acc220',
        Status__c = 'Active',
        Type = 'Client',
        Client_Account_Lead__c = userID,
        Client_Classification__c = 'Diamond',    
        Account_Plan_OI__c = 80
        );
        Database.insert(testAcc002, true);
        testAcc002.Account_Plan_OI__c = 100;
                
        
        /*
        * - Test Opportunity
        */

        Opportunity testOpp23 = new Opportunity(
        Name = 'Opportunity Test Class 100',
        AccountId = testAcc002.Id,
        Win_Probability__c = '50',
        Best_Probable_Worst__c = 'Best',
        Hierarchy_Level__c = 'Standalone',
        STATUS_STAGE_REQUESTED__C = '0',
        Draft_RFP_Release_Date__c = System.today() + 80,
        RFP_RELEASE_DATE__C = System.today() + 90,
        Proposal_Submission_Date__c = System.today() + 95,
        Actual_Contract_Sign_Date__c = System.today() + 110,
        CLOSEDATE = System.today() + 115,
        REPORTING_STATUS_SINCE__C = System.today() - 30, 
        TYPE = 'Competitive',
        STAGENAME = '0',
        APPROVED_STATUS_STAGE__C = '0',
        Reporting_Status__c = 'Qualified',
        Consulting_Start__c  = System.today() + 120,
        Consulting_End__c = System.today() + 210,   
        Outsourcing_Start__c = System.today() + 150, 
        Outsourcing_End__c  = System.today() + 240 
        );
        Database.insert(testOpp23,true);
        Database.update(testAcc002, true); 
        Database.update(testOpp23,true);
        
        // Confirm that record is inserted
        System.assertNotEquals(null, testOpp23.Id);
    }
    
    /* 
    * @Method Define scope of testmethod.
    */    
    static testmethod void testUpdateClientAccount(){
        //Test Type Client
        
        //Insert Client Account - No Parent Acc
        Account clientAccParent = new Account(
        RecordTypeId = CLIENT_REC_TYPE,
        name = 'Sample Test Account Acc220',
        Status__c = 'Active',
        Type = 'Client',
        Client_Account_Lead__c = userID,
        Client_Classification__c = 'Diamond',    
        Account_Plan_OI__c = 80
        );
        Database.insert(clientAccParent, true);
        
        System.assertNotEquals(null, clientAccParent.Id);        
        
    }
    
    /* 
    * @Method Define scope of testmethod.
    */
    static testmethod void testAccount() {

        prepdata();
        //testIfAccount();
        //testElseAccount();
        //testValidAccount();
        //queryValidAccount();
        Test.startTest();
        
        //AccountHandler.firstRunForUpdate=True;

        System.debug('Approve Status Stage>>>> ' + OppAccountPlanOIValid.Approved_Status_Stage__c );
        System.debug('Reporting Status>>> ' + OppAccountPlanOIValid.REPORTING_STATUS__C);       
        System.debug('Before Value of Account Plan OI>>' + clientAcc.Account_Plan_OI__c);       
        System.debug('Before Value of Opp Plan OI>>' + OppAccountPlanOIValid.Account_Plan_OI__c);
        System.debug('Before Id of Opp Plan OI>>' + OppAccountPlanOIValid.Id);
        AccountHandler.firstRunForUpdate = True;
        
        clientAcc.Account_Plan_OI__c = 27;
        //AccountHandler.firstRunForUpdate = True;
        Database.update(clientAcc, true);

        System.debug('Approve Status Stage>>>> ' + OppAccountPlanOIInvalid.Approved_Status_Stage__c );
        System.debug('Reporting Status>>> ' + OppAccountPlanOIInvalid.REPORTING_STATUS__C);         
        System.debug('After Value of Account Plan OI>>' + clientAcc.Account_Plan_OI__c);
        System.debug('After Value of Opp Plan OI>>' + OppAccountPlanOIInvalid.Account_Plan_OI__c);
        System.debug('After Id of Opp Plan OI>>' + OppAccountPlanOIInvalid.Id);
        

        
        recordAcc.Type = 'Sub Portfolio';
        Database.update(recordAcc);
        
        Database.update(recordAcct);
        
        //recordAcc2.Type = 'Customer';
        Database.update(recordAcc2);
        
        //this is to satisfy the update, delete and undelete in AccountHandler  
        recordAcc3.Type = 'Client';
        Database.update(recordAcc3);       
        Database.delete(recordAcc5);        
        Database.undelete(recordAcc5);
        
        // Confirm that record is inserted
        System.assertNotEquals(null, recordAcc5.Id);
        
        Test.stopTest();
        
        
    }
    /*static testmethod void testHandler() {
    
        prepdata();
        Test.startTest();
        
        //this is to satisfy the update, delete and undelete in AccountHandler  
        recordAcc3.Type = 'Client';
        Database.update(recordAcc3);       
        Database.delete(recordAcc5);        
        Database.undelete(recordAcc5);
        
        // Confirm that record is inserted
        System.assertNotEquals(null, recordAcc5.Id);
        Test.stopTest();
    
    
    
    }*/
    
    
}