AFS_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <description>Reflects Client Portfolio Management (CPM) classification (Diamond, Foundation, Portfolio or Opportunistic).</description>
        <label>Client Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Mega Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunistic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Captures the source of creation for the record. This will be provide the ability to differentiate if the record was created in Salesforce or is a legacy record.</description>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>STaR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>The entity who will receive the services or products AFS provides (e.g., DC Department of Healthcare Finance). Selecting this Account Record Type will allow you to create a new AFS client to associate with new opportunities, contacts, and/or activities.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ATS_Notes__c</fullName>
        <inlineHelpText>Provide an introduction to ATS request. Provide explanation of below-target OI%, summarize any management discounts and/or costs assumed to be not billable, DSO, etc. For Agilex legacy deals, please specify new ODE.</inlineHelpText>
        <label>ATS Introduction</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Actual_Contract_Sign_Date__c</fullName>
        <inlineHelpText>Date the contract was signed by the client. Date field must always be after the Draft RFP Release Date, RFP Release Date, Proposal Submission Date, but may equal to the Expected Contract Sign Date.</inlineHelpText>
        <label>Actual Contract Sign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approved_Status_Stage__c</fullName>
        <inlineHelpText>Status/Stage the Sales Ops will approve the opportunity record to once the opportunity has gone through all approval processes</inlineHelpText>
        <label>Approved Status/Stage</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Best_Probable_Worst__c</fullName>
        <inlineHelpText>The scenario for AFS winning the deal. 
Worst Case: AFS would win in the worst case scenario. 
Probable Win: A win is likely. 
Probable Loss: A win is unlikely. 
Best Case: We would only win in the best case scenario. 
Exclude: Exclude from forecast.</inlineHelpText>
        <label>Best/Probable/Worst</label>
        <picklist>
            <picklistValues>
                <fullName>Exclude</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Best</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Possible Loss</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Probable Win</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Worst</fullName>
                <color>#78C953</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <formula>TEXT(Account.Client_Classification__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Classification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complexity_Category__c</fullName>
        <inlineHelpText>Indicates which of the AFS Complexity Criteria options are applicable to the opportunity.</inlineHelpText>
        <label>Complexity Category</label>
        <picklist>
            <picklistValues>
                <fullName>ATSLP: Req&apos;t to lease/acquire facilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATSLP: SW license chg/SW assets provided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATSLP: Transfer/sale/leasing of assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapCo: CapCo deal reneg/extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapCo: No longer requires CapCo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapCo: Referred to CapCo by ELT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB: Cross border client contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB: Geographic expansion/high risk area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CC: Capital &lt;$1M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CC: Capital &gt;=$10M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CC: Capital &gt;=$1M to &lt;$10M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JVMA: Assisting w/ Client M&amp;A activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JVMA: Jt Venture/Investment/Divestiture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JVMA: M&amp;A transaction &lt;$1M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JVMA: M&amp;A transaction &gt;=$10M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JVMA: M&amp;A transaction &gt;=$1M and &lt;$10M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal: Deal funded by/related to USARRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal: Deal funded by US Federal govt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal: Deviations from Policy AFS-1370</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal: Regulatory approval required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA: Opp Director confirms not applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSFS: Bank Guarantee/LoC &lt;$10M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSFS: Corp Guarantee/Pol 45 disclosure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSFS: Risk of negative media attention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSFS: Royalties, mktg assitance, etc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSFS: Sales incentives &lt;$10M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSFS: Surety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ONSC: Defense related opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ONSC: Expanded Scope of Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ONSC: Sole Source Contract</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Consulting_End__c</fullName>
        <inlineHelpText>Start/End Dates should reflect the base award/booked sale represented by the Total Current Revenue</inlineHelpText>
        <label>Consulting End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Consulting_Start__c</fullName>
        <inlineHelpText>Date the Consulting portion of the contract is expected to begin. Field is required if the Financial Details Related List includes MC, SI, or TC Service Groups.</inlineHelpText>
        <label>Consulting Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Draft_RFP_Release_Date__c</fullName>
        <inlineHelpText>Anticipated release date of the Draft RFP. This date field may be equal to or before the &quot;RFP Release&quot; date field.</inlineHelpText>
        <label>Draft RFP Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_End__c</fullName>
        <inlineHelpText>Date the Outsourcing portion of the contract will be complete.</inlineHelpText>
        <label>Outsourcing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_Start__c</fullName>
        <inlineHelpText>Start/End Dates should reflect the base award/booked sale represented by the Total Current Revenue</inlineHelpText>
        <label>Outsourcing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFP_Release_Date__c</fullName>
        <inlineHelpText>Date RFP was released. This field is used for tracking purposes. This date field must always come before the &quot;Proposal Submission Date&quot; field but may be equal to the Draft RFP Release Date.</inlineHelpText>
        <label>RFP Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Status_Since__c</fullName>
        <inlineHelpText>Tracks the date that an opportunity advancement request was submitted. Reporting Status Date is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Status__c</fullName>
        <inlineHelpText>Field updated based on the stage of the opportunity through workflow. Reporting Status is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status</label>
        <picklist>
            <controllingField>Approved_Status_Stage__c</controllingField>
            <picklistValues>
                <fullName>Lost</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
                <color>#A845DC</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesforce</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>STaR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Stage_Requested__c</fullName>
        <inlineHelpText>Use this field to request advancement to a subsequent stage when all required fields are complete.
Please note: there may be additional fields on the Related Lists (e.g., Financial Details, Attributes, Opp Team Roles) that are required for advancement.</inlineHelpText>
        <label>Status/Stage Requested</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/classes/RevenueBLTest.cls
/**
 * Class Name: RevenueBLTest
 * @author: Honelee Padilla
 * Date: 03/10/2015
 * Test Class for RevenueBL
 */
@isTest(SeeAllData=true)
    /*
    * - Testclass for RevenueBLTest
    */
private class RevenueBLTest{
    
   private static id opportunityId;
   private static final String SOME_VALUE = 'Some Value';
   private static Map<String, Id> priceBookEntryMap = new Map<String, Id>{};
   
   /*
    * - Test method that creates the needed data
    */
   static testmethod void prepdata() {
 
       /*
        * - Get profile to assign to testUser
        */
    Set<String> priceBookEntryNames = new Set<String> {
        'AO - CostPlus',
        'TC - Time & Materials',
        'BPO - CostPlus',
        'IO - CostPlus'
    };
    
    for (PriceBookEntry entry :[SELECT Id, Name FROM PriceBookEntry WHERE Name IN :priceBookEntryNames AND Pricebook2.IsStandard = true]) {
            priceBookEntryMap.put(entry.Name, entry.Id);
        }
  Profile testProfile = [select id from profile where name='System Administrator' limit 1];
  
    User u = new User();
    u.alias = 'userTest';
    u.email='user1@sample.com';
    u.emailencodingkey='UTF-8';
    u.lastname='Test';
    u.languagelocalekey='en_US';   
    u.localesidkey='en_US';
    u.profileid = testProfile.Id;
    u.timezonesidkey='America/Los_Angeles';
    u.username='user1@sample.com.dev';
    
    Database.insert(u, true);
    
    //insert u;
  
     /*
    * - Test Account
    */
  RecordType clientRecType = [Select Id FROM RecordType WHERE Name = 'Client' LIMIT 1];
  
  Account testAcc  = new Account();
  testAcc.RecordTypeId = clientRecType.Id;
  testAcc.name = 'Sample Test Account';
  testAcc.Status__c = 'Active';
  testAcc.Type = 'Client';
  testAcc.Client_Account_Lead__c = u.id; 
  testAcc.Client_Classification__c = 'Diamond'; 
  
  Database.insert(testAcc, true);
  
  //insert testAcc;

    /*
    * - Test Opportunity
    */
    Opportunity testOpp = new Opportunity();
    testOpp.Name = 'Opportunity Test Class';
    testOpp.AccountId = testAcc.id;
    testOpp.STATUS_STAGE_REQUESTED__C = '0';
    testOpp.RFP_RELEASE_DATE__C = System.today() + 90;
    testOpp.CLOSEDATE = System.today() + 115; 
    testOpp.Actual_Contract_Sign_Date__c = System.today() + 120;
    testOpp.REPORTING_STATUS_SINCE__C = System.today() - 30; 
    testOpp.TYPE = 'Competitive';
    testOpp.STAGENAME = '0';
    testOpp.APPROVED_STATUS_STAGE__C = '0';
    testOpp.REPORTING_STATUS__C = 'Qualified';
    testOpp.Consulting_Start__c  = System.today() + 120; 
    testOpp.Consulting_End__c = System.today() + 210;   
    testOpp.Outsourcing_Start__c = System.today() + 150; 
    testOpp.Outsourcing_End__c  = System.today() + 240; 
    testOpp.ATS_Notes__c = 'Write text here';
    testOpp.Best_Probable_Worst__c = 'Probable Win';
    testOpp.Source__c = 'StaR';
    testOpp.Complexity_Category__c = 'ATSLP: SW license chg/SW assets provided';
    testOpp.Draft_RFP_Release_Date__c = System.today();
    testOpp.RFP_Release_Date__c = System.today() + 1;
    testOpp.Estimator_Confirm_Compliance__c = 'Yes';
    testOpp.Client_Data_Protection_Risk_Assessment__c = SOME_VALUE;
    testOpp.Client_Industry_Area_of_Service__c = SOME_VALUE;
    testOpp.Hierarchy_Level__c = SOME_VALUE;
    
    Database.insert(testOpp, true);
    
    //insert testOpp;
    
    opportunityId = testOpp.Id;
    
    /*
    * - Test Opportunity Line Item
    */
    
    OpportunityLineItem testOppLI = new OpportunityLineItem();
    testOppLI.OpportunityId = opportunityId;
    testOppLI.PriceBookEntryId = priceBookEntryMap.get('AO - CostPlus');//'01uq0000000WvKyAAK';
    testOppLI.Revenue__c = 1000000;
    testOppLI.Total_Costs__c = 100;
    testOppLI.Type__c ='01 - AO';
    
    Database.insert(testOppLI, true);
    
    System.assertNotEquals(null, testOppLi.Id);
    
    }
    
     /*
      * - Method to test testRevenueBL and used the data in prepdata method
      */   
    static testmethod void testRevenueBL() {
    
        prepdata();
        RevenueBL.isRevenueScheduled = false;
        Test.startTest();
        
        OpportunityLineItem testOppLI2 = new OpportunityLineItem();
        testOppLI2.OpportunityId = opportunityId;
        testOppLI2.PriceBookEntryId = priceBookEntryMap.get('TC - Time & Materials');
        testOppLI2.Revenue__c = 5000000;
        testOppLI2.Total_Costs__c = 500;
        testOppLI2.Type__c ='06 - TC';
        testOppLi2.Type_of_Work__c = 'Consulting';
        
        OpportunityLineItem testOppLI3 = new OpportunityLineItem();
        testOppLI3.OpportunityId = opportunityId;
        testOppLI3.PriceBookEntryId = priceBookEntryMap.get('BPO - CostPlus');//'01uU0000001fHJ9IAM';
        testOppLI3.Revenue__c = 4000000;
        testOppLI3.Total_Costs__c = 400;
        testOppLI3.Type__c ='02 - BPO';
        testOppLI3.Type_of_Work__c = 'Outsourcing';
        
        OpportunityLineItem testOppLI4 = new OpportunityLineItem();
        testOppLI4.OpportunityId = opportunityId;
        testOppLI4.PriceBookEntryId = priceBookEntryMap.get('IO - CostPlus');//'01uq0000000WvL3AAK';
        testOppLI4.Revenue__c = 3000000;
        testOppLI4.Total_Costs__c = 300;
        testOppLI4.Type__c ='03 - IO';
		testOppLI4.Type_of_Work__c = 'Outsourcing';
        
        Database.insert(new OpportunityLineItem[]{testOppLI2, testOppLI3, testOppLI4}, true);
        System.assertNotEquals(null, testOppLI4.Id);
        
        System.debug('?????????????<<< id of opp line item 2 ' + testOppLI2.id);
        System.debug('?????????????<<< id of opp line item 3' + testOppLI3.id);
        System.debug('?????????????<<< id of opp line item 4' + testOppLI4.id);
        System.debug('?????????????<<< outsourcing/consulting value ' + testOppLI2.Type_of_Work__c);
        System.debug('?????????????<<< outsourcing/consulting value ' + testOppLI3.Type_of_Work__c);
        System.debug('?????????????<<< outsourcing/consulting value ' + testOppLI4.Type_of_Work__c);
        
        
        Test.stopTest();
    
    }  
}