AFS_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Account_Team_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team_Roles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team Roles</relationshipLabel>
        <relationshipName>Account_Team_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Access__c</fullName>
        <label>Case Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Access__c</fullName>
        <label>Contact Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Development Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Account Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client QA Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global CAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managing Director MC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Portfolio Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology Account Lead</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Team Role</label>
    <nameField>
        <displayFormat>Acc Team-{0000000}</displayFormat>
        <label>Account Team Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/classes/AccountTeamRoleBL.cls
/**
   @Author Lhea Valencia
   @name AccountTeamRoleBL
   @CreateDate 04/14/2015
   @Description Business Logic Class for Account Team Role object.
   @Version <1.0>
   @reference <Referenced program names>
  */
public class AccountTeamRoleBL {

    public static void insertAccountOwner( List<Account_Team_Role__c> newVal) {
        
        List<Account> accs = new List<Account>();
        List<Account_Team_Role__c> accTRole = new List<Account_Team_Role__c>();
        Set<Id> teamRoleIds = new Set<Id>();        
        Set<Id> accIds = new Set<Id>();
        Map<Id, Id> accIdAndOwner = new Map<Id, Id>{};
        
        for(Account_Team_Role__c accList : newVal) {
            teamRoleIds.add(accList.Id);
            accIds.add(accList.Account__c);
        }
        
        accs = [SELECT id, name, ownerId FROM Account where id=:accIds];
        for(Account acc : accs){
            accIdAndOwner.put(acc.id, acc.ownerId);
        }
        
        accTRole = [SELECT id, name , account_owner__c, account__c, status__c FROM Account_Team_Role__c where id IN :teamRoleIds AND status__c != 'Approved'];
        for(Account_Team_Role__c acctr : accTRole){
            acctr.status__c = 'New';
            acctr.account_owner__c = accIdAndOwner.get(acctr.account__c);
        }
        
        Database.update(accTRole);
    }
    
    public static void insertAccountTeam(Map<Id, Account_Team_Role__c> oldAccountTeamRoleMap,  Map<Id, Account_Team_Role__c> newAccountTeamRoleMap) {
        Map<Id, Account_Team_Role__c> approvedAccTeamRole = new Map<Id, Account_Team_Role__c>{};
        Map<Id, Id> approvedUserIds = new Map<Id, Id>{};
        Account_Team_Role__c newAccTeamRole = new Account_Team_Role__c();
        
        for(Id newId : newAccountTeamRoleMap.keySet()){
            newAccTeamRole = newAccountTeamRoleMap.get(newId);
            
            if(newAccTeamRole.status__c == 'Approved' && newAccTeamRole.Account_Owner__c != newAccTeamRole.Team_Member__c){
                approvedAccTeamRole.put(newId, newAccTeamRole);
                approvedUserIds.put(newAccTeamRole.Team_Member__c, newId);
            }
        }
        
        if(!approvedUserIds.isEmpty()){
            Map<Id, Account_Team_Role__c> addedAccTeamRole = commitNewAccountTeam(approvedUserIds, approvedAccTeamRole);
            commitNewAccountTeam(approvedUserIds, approvedAccTeamRole);
            List<Account_Team_Role__c> deleteAccountTeamRoles = [SELECT Id FROM Account_Team_Role__c WHERE Id IN :addedAccTeamRole.keySet()];
        }
    }
    
    public static Map<Id, Account_Team_Role__c> commitNewAccountTeam(Map<Id, Id> approvedUserIds, Map<Id, Account_Team_Role__c> approvedAccTeamRole){
        Map<Id, Account_Team_Role__c> addedAccTeamRole = new Map<Id, Account_Team_Role__c>();
        List<AccountShare> share = new List<AccountShare>();
        List<AccountShare> updateShare = new List<AccountShare>();
        List<AccountTeamMember> member = new List<AccountTeamMember>();
        Account_Team_Role__c accountTeamRole = new Account_Team_Role__c();
        AccountShare accountShare = new AccountShare();
        AccountTeamMember teamMember = new AccountTeamMember();
        
        for(Id userId: approvedUserIds.keySet()){
             accountTeamRole = approvedAccTeamRole.get(approvedUserIds.get(userId));
             
             teamMember = new AccountTeamMember();
             teamMember.AccountId = accountTeamRole.Account__c;
             teamMember.userId = accountTeamRole.Team_Member__c;
             teamMember.TeamMemberRole = accountTeamRole.Team_Role__c;
             member.add(teamMember);
             
             accountShare = new AccountShare();
             accountShare.AccountId = accountTeamRole.Account__c;
             accountShare.UserOrGroupId = accountTeamRole.Team_Member__c;
             accountShare.AccountAccessLevel = getAccessLevel(accountTeamRole.Account_Access__c);
             accountShare.ContactAccessLevel = getAccessLevel(accountTeamRole.Contact_Access__c);
             accountShare.CaseAccessLevel = getAccessLevel(accountTeamRole.Case_Access__c);
             accountShare.OpportunityAccessLevel = getAccessLevel(accountTeamRole.Opportunity_Access__c);
             share.add(accountShare);
             
             addedAccTeamRole.put(accountTeamRole.Id, accountTeamRole);
        }
        
        Database.insert(member);
        Database.insert(share);
        
        return addedAccTeamRole;
    }
    
    public static String getAccessLevel(String rawAccessLevel){
        String accessLevel = 'Read';
        
        if(rawAccessLevel == 'Read/Write'){
            accessLevel = 'Edit';
        }
        
        return accessLevel;
    }
}