AFS_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <description>Reflects Client Portfolio Management (CPM) classification (Diamond, Foundation, Portfolio or Opportunistic).</description>
        <label>Client Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Mega Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunistic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Captures the source of creation for the record. This will be provide the ability to differentiate if the record was created in Salesforce or is a legacy record.</description>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>STaR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>The entity who will receive the services or products AFS provides (e.g., DC Department of Healthcare Finance). Selecting this Account Record Type will allow you to create a new AFS client to associate with new opportunities, contacts, and/or activities.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>Att-{0000000000}</displayFormat>
        <label>Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Contract_Sign_Date__c</fullName>
        <inlineHelpText>Date the contract was signed by the client. Date field must always be after the Draft RFP Release Date, RFP Release Date, Proposal Submission Date, but may equal to the Expected Contract Sign Date.</inlineHelpText>
        <label>Actual Contract Sign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approved_Status_Stage__c</fullName>
        <inlineHelpText>Status/Stage the Sales Ops will approve the opportunity record to once the opportunity has gone through all approval processes</inlineHelpText>
        <label>Approved Status/Stage</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <formula>TEXT(Account.Client_Classification__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Classification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consulting_End__c</fullName>
        <inlineHelpText>Start/End Dates should reflect the base award/booked sale represented by the Total Current Revenue</inlineHelpText>
        <label>Consulting End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Consulting_Start__c</fullName>
        <inlineHelpText>Date the Consulting portion of the contract is expected to begin. Field is required if the Financial Details Related List includes MC, SI, or TC Service Groups.</inlineHelpText>
        <label>Consulting Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Draft_RFP_Release_Date__c</fullName>
        <inlineHelpText>Anticipated release date of the Draft RFP. This date field may be equal to or before the &quot;RFP Release&quot; date field.</inlineHelpText>
        <label>Draft RFP Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Level__c</fullName>
        <description>Standalone (or Full &amp; Open): Procurement issued as a standalone contract; opportunities that are not a Contract Vehicle or Task Order under a Contract Vehicle should be classified as Standalone. 

Contract Vehicle: Procurement is an IDIQ or BPA vehicle that AFS is pursuing as a new award. 
 
Task Order: Procurement is a Task Order issued on an existing Contract Vehicle.</description>
        <inlineHelpText>Standalone: Indicates if a procurement is full and open

Contract Vehicle: IDIQ/BPA

Task Order: Opportunity under an existing contract vehicle</inlineHelpText>
        <label>Hierarchy Level</label>
        <picklist>
            <picklistValues>
                <fullName>Contract Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standalone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Outsourcing_End__c</fullName>
        <inlineHelpText>Date the Outsourcing portion of the contract will be complete.</inlineHelpText>
        <label>Outsourcing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_Start__c</fullName>
        <inlineHelpText>Start/End Dates should reflect the base award/booked sale represented by the Total Current Revenue</inlineHelpText>
        <label>Outsourcing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PoC_Responsible__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Indicate who is on point to deliver this sales number?</inlineHelpText>
        <label>PoC Responsible?</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal_Submission_Date__c</fullName>
        <inlineHelpText>Date AFS submitted the proposal. The Proposal Submission Date should always be before both the Expected Contract Sign Date and Actual Contract Sign Date.</inlineHelpText>
        <label>Proposal Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFP_Release_Date__c</fullName>
        <inlineHelpText>Date RFP was released. This field is used for tracking purposes. This date field must always come before the &quot;Proposal Submission Date&quot; field but may be equal to the Draft RFP Release Date.</inlineHelpText>
        <label>RFP Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Status_Since__c</fullName>
        <inlineHelpText>Tracks the date that an opportunity advancement request was submitted. Reporting Status Date is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Status__c</fullName>
        <inlineHelpText>Field updated based on the stage of the opportunity through workflow. Reporting Status is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status</label>
        <picklist>
            <controllingField>Approved_Status_Stage__c</controllingField>
            <picklistValues>
                <fullName>Lost</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
                <color>#A845DC</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Committed_for_First_Year__c</fullName>
        <inlineHelpText>What sales have we committed to in the account plan for the first year of the contract?</inlineHelpText>
        <label>Sales Committed for First Year?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesforce</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>STaR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Stage_Requested__c</fullName>
        <inlineHelpText>Use this field to request advancement to a subsequent stage when all required fields are complete.
Please note: there may be additional fields on the Related Lists (e.g., Financial Details, Attributes, Opp Team Roles) that are required for advancement.</inlineHelpText>
        <label>Status/Stage Requested</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity_Team_Roles__c.object
<CustomObject>
    <description>This is an object for the Opportunity Team and Sales Credit Records.</description>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Name</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Opportunity Team Roles</relationshipLabel>
        <relationshipName>Opportunity_Teams_Sales_Credit</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Teams_Sales_Credit</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Team Roles</label>
    <nameField>
        <displayFormat>ID-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Team Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Service Group</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

AFS_Dev/src/objects/Person__c.object
<CustomObject>
    <description>This object is taking place of the user object where user names will be stored.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stores Active Directory user status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>AFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Contractor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/classes/AddAttributeExtTest.cls
/**
   @Author                       Honelee F. Padilla
   @name                         AddAttributeExtTest
   @CreateDate                   
   @Description                  <insert description here>
*/
@isTest(SeeAllData=true)
private class AddAttributeExtTest{

    private static id testPersonGlobalId;
    
    
   /**
   * This testAddAttributeExt1 will test create of opportunity product and insert, update and deletion of attributes.
   * @param N/A
   * @return void
   */
    private static testmethod void testAddAttributeExt1(){    
            
    Id opportunityId = null;
    Id accountId = null;
    list<Opportunity> opp = new list<Opportunity>();
    list<Opportunity> oppError = new list<Opportunity>();
    final String accountName = 'Sample Test Account';
    Set<String> priceBookEntryNames = new Set<String> {
        'AO - CostPlus',
        'IO - CostPlus',
        'BPO - CostPlus',
        'SI - CostPlus',
        'TC - CostPlus',
        'MC - CostPlus'
    };
    List<PriceBookEntry> priceBookEntries = new List<PriceBookEntry>{};
    Map<String, Id> priceBookEntryMap = new Map<String, Id>{};
  
        Profile p = [select id from profile where name='System Administrator' limit 1];
        User u = new User();
        u.alias = 'userTest';
        u.email='user1@sample.com';
        u.emailencodingkey='UTF-8';
        u.lastname='Test';
        u.languagelocalekey='en_US';   
        u.localesidkey='en_US';
        u.profileid = p.Id;
        u.timezonesidkey='America/Los_Angeles';
        u.username='user1@sample.com.dev';
        database.insert(u,true);
        System.assertNotEquals(null, u.Id);
        
        for (PriceBookEntry entry :[SELECT Id, Name FROM PriceBookEntry WHERE Name IN :priceBookEntryNames AND Pricebook2.IsStandard = true]) {
            priceBookEntryMap.put(entry.Name, entry.Id);
        }
        
        RecordType clientRecType = [Select Id FROM RecordType WHERE Name = 'Client' LIMIT 1];
      
        Account testAcc  = new Account();
        testAcc.RecordTypeId = clientRecType.Id;
        testAcc.name = accountName;
        testAcc.Status__c = 'Active';
        testAcc.Type = 'Client';
        testAcc.Client_Account_Lead__c = u.id; 
        testAcc.Client_Classification__c = 'Diamond'; 
        database.insert(testAcc,true);
        accountid = testAcc.id;

        /*
        * - Test Person
        */     
        Person__c testPersonGlobal = new Person__c(
            Name='Test name',
            email__c='test@email.com',
            user_type__c='AFS'
        ); 
        database.insert(testPersonGlobal,true);  
        testPersonGlobalId = testPersonGlobal.Id;

        Opportunity testOpp = new Opportunity();
        testOpp.Name = 'Opportunity Test Class Zero';
        testOpp.AccountId = accountid; //'001q0000006jVaf';
        testOpp.Source__c = 'Salesforce';
        testOpp.STATUS_STAGE_REQUESTED__C = '0';
        testOpp.Proposal_Submission_Date__c=System.today() + 4;
        testOpp.Draft_RFP_Release_Date__c=System.today() + 2;
        testOpp.Actual_Contract_Sign_Date__c=System.today() + 20;
        testOpp.RFP_RELEASE_DATE__C = System.today() + 3;
        testOpp.CLOSEDATE = System.today() + 115; 
        testOpp.REPORTING_STATUS_SINCE__C = System.today() - 30; 
        testOpp.TYPE = 'Competitive';
        testOpp.STAGENAME = '0';
        testOpp.APPROVED_STATUS_STAGE__C = '0';
        testOpp.REPORTING_STATUS__C = 'Unqualified';
        testOpp.Consulting_Start__c  = System.today() + 120; 
        testOpp.Consulting_End__c = System.today() + 210;   
        testOpp.Outsourcing_Start__c = System.today() + 150; 
        testOpp.Outsourcing_End__c  = System.today() + 240; 
        testOpp.Hierarchy_Level__c = 'Standalone';
        testOpp.Probability = 0.1;
        testOpp.PoC_Responsible__c = testPersonGlobalId;
        testOpp.Sales_Committed_for_First_Year__c = 1234;
        database.insert(testOpp,true);
        
        test.startTest();
        List<Attribute__c> testAtts = new List<Attribute__c>();
        Attribute__c testAtt1 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Accenture Digital',
        Attribute_Value__c = 'Analytics',
        AttributePercent__c = 20);
                
        testAtts.add(testAtt1);
        
        Attribute__c testAtt2 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
         Attribute_Type__c = 'TGP Offerings', 
        Attribute_Value__c ='Not Applicable', 
        AttributePercent__c = 1);
        testAtts.add(testAtt2);
        
        Attribute__c testAtt3 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Alliance',
        Attribute_Value__c = 'ADOBE',
        AttributePercent__c = 20);
                
        testAtts.add(testAtt3);

         Attribute__c testAtt4 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Alliance',
        Attribute_Value__c = 'CALLIDUS',
        AttributePercent__c = 20);
                
        testAtts.add(testAtt4);

         Attribute__c testAtt5 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Horizontals/Initiatives',
        Attribute_Value__c = 'Accenture Cloud Platform-Cloud Managed Services',
        AttributePercent__c = 20);
                
        testAtts.add(testAtt5);
        
        Database.insert(testAtts, false);
        
        Attribute__c testAtt6 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Horizontals/Initiatives',
        Attribute_Value__c = 'Cloud-Apps and Platform Services (PaaS)',
        AttributePercent__c = 20);
                
        testAtts.add(testAtt6);
        
        Attribute__c testAtt7 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Industry Business Services',
        Attribute_Value__c = 'D&PS-ENTERPRISE SERVICES FOR DEFENSE-DIGITAL DEFENSE TRANSFORMATION',
        AttributePercent__c = 20);
                
        testAtts.add(testAtt7);

        Attribute__c testAtt8 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Industry Business Services',
        Attribute_Value__c = 'D&PS-ENTERPRISE SERVICES FOR DEFENSE-MILITARY HEALTH',
        AttributePercent__c = 20);
                
        testAtts.add(testAtt8);

        Attribute__c testAtt9 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Ventures & Acquisitions',
        Attribute_Value__c = 'Agilex - Synergy',
        AttributePercent__c = 100);
                
        testAtts.add(testAtt9);

        Attribute__c testAtt10 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Ventures & Acquisitions',
        Attribute_Value__c = 'Agilex - Standalone',
        AttributePercent__c = 100);
                
        testAtts.add(testAtt10);

        Attribute__c testAtt11 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Ventures & Acquisitions',
        Attribute_Value__c = 'Agilex - Standalone',
        AttributePercent__c = 1);
                
        testAtts.add(testAtt11);

        Attribute__c testAtt12 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Ventures & Acquisitions',
        Attribute_Value__c = 'Agilex - Standalone',
        AttributePercent__c = 1);

        testAtts.add(testAtt12);

        Attribute__c testAtt13 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Accenture Digital',
        Attribute_Value__c = 'Analytics',
        AttributePercent__c = 0);
                
        testAtts.add(testAtt13);

        Attribute__c testAtt14 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Alliance',
        Attribute_Value__c = 'ADOBE',
        AttributePercent__c = 20);
                
        testAtts.add(testAtt14);

        Attribute__c testAtt15 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Industry Business Services',
        Attribute_Value__c = 'D&PS-ENTERPRISE SERVICES FOR DEFENSE-DIGITAL DEFENSE TRANSFORMATION',
        AttributePercent__c = 0);
                
        testAtts.add(testAtt15);

        database.insert(testAtts,false);
        
        ApexPages.currentPage().getParameters().put('id',testOpp.id);
          
        List <Attribute__c> attrib = [SELECT Name, id,Attribute_Check__c ,Attribute_TypeName__c, Attribute_Type__c, AttributeTxt__c, Attribute_Value__c, AttributePercent__c,Opportunity_Name__c FROM Attribute__c WHERE Opportunity_Name__c = :testOpp.id  ORDER BY Attribute_Type__c, Attribute_Value__c ASC LIMIT 50000];
        
        System.debug('AttributeVal: ' + attrib);
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(attrib);      
        AddAttributeExt objController  = new AddAttributeExt(ssc);
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'ASM - Synergy', 
        AttributePercent__c = 100);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'Agilex - Standalone', 
        AttributePercent__c = 100);
        objController.addAttribute();
        
        objController.attributes.clear();
        
        objController.ATT = new Attribute__c (        
        Opportunity_Name__c = testOpp.id, 
        Attribute_Check__c = true, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'ASM - Synergy', 
        AttributePercent__c = 100);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c ='Agilex - Standalone', 
        AttributePercent__c = 100);
        objController.updateAttributes(); 
        
        objController.attributes.clear();
        
        objController.ATT = new Attribute__c (        
        Opportunity_Name__c = testOpp.id, 
        Attribute_Check__c = true, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'ASM - Synergy', 
        AttributePercent__c = 100);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c ='Agilex - Standalone', 
        AttributePercent__c = 10);
        objController.updateAttributes(); 
          

        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Alliance', 
        Attribute_Value__c = 'MICROSOFT', 
        AttributePercent__c = 100);
        objController.addAttribute();
        
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Horizontals/Initiatives', 
        Attribute_Value__c ='UC & Network', 
        AttributePercent__c = 10);
        objController.addAttribute();
        
        objController.attributes.add(new Attribute__c (
        Attribute_Check__c = true, 
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Alliance', 
        Attribute_Value__c ='INFORMATICA', 
        AttributePercent__c = 16));
            
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Alliance', 
        Attribute_Value__c ='INFORMATICA', 
        AttributePercent__c = 18);
        objController.updateAttributes();
        
        objController.attributes.add(new Attribute__c (
        Attribute_Check__c = true, 
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Accenture Digital', 
        Attribute_Value__c ='Interactive', 
        AttributePercent__c = 16));
            
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Accenture Digital', 
        Attribute_Value__c ='Interactive', 
        AttributePercent__c = 10);
        objController.updateAttributes();
        
        objController.attributes.add(new Attribute__c (
        Attribute_Check__c = true, 
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Horizontals/Initiatives', 
        Attribute_Value__c ='Cloud-Strategy', 
        AttributePercent__c = 16));
        
        objController.ATT = new Attribute__c ( 
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Horizontals/Initiatives', 
        Attribute_Value__c ='Cloud-Strategy', 
        AttributePercent__c = 16);
        objController.deleteAttributes();
        
        objController.attributes.add(new Attribute__c (
        Attribute_Check__c = true, 
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Alliance', 
        Attribute_Value__c ='SI-Application Svcs for Mainframe', 
        AttributePercent__c = 16));
        
        objController.attributes = attrib;
        
        objController.ATT = new Attribute__c (
            Opportunity_Name__c = testOpp.id, 
            Attribute_Type__c = 'Alliance', 
            Attribute_Value__c ='CALLIDUS', 
            AttributePercent__c = 16);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
            Opportunity_Name__c = testOpp.id, 
            Attribute_Type__c = 'Industry Business Services', 
            Attribute_Value__c = 'D&PS-ENTERPRISE SERVICES FOR DEFENSE-DIGITAL DEFENSE TRANSFORMATION', 
            AttributePercent__c = 15);
        objController.updateAttributes();
       
        objController.ATT = new Attribute__c ( 
            Opportunity_Name__c = testOpp.id, 
            Attribute_Type__c = 'TGP Offerings', 
            Attribute_Value__c ='Not Applicable', 
            AttributePercent__c = 1);
        objController.addAttribute();
                
        objController.ATT = new Attribute__c (
            Opportunity_Name__c = testOpp.id, 
            Attribute_Type__c = null, 
            Attribute_Value__c = null, 
            AttributePercent__c = 10);
        objController.deleteAttributes();
        
        objController.ATT = new Attribute__c (
            Opportunity_Name__c = testOpp.id, 
            Attribute_Type__c = null, 
            Attribute_Value__c = null, 
            AttributePercent__c = null);
        objController.insertAttributes();
        
       objController.attributes.clear();
       
       objController.ATT = new Attribute__c (
            Attribute_Type__c = 'Accenture Digital', 
          Attribute_Value__c ='Interactive', 
          AttributePercent__c = 100);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
            Attribute_Type__c = 'Alliance', 
          Attribute_Value__c ='AMAZON WEB SERVICES (AWS)', 
          AttributePercent__c = 100);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
            Attribute_Type__c = 'Horizontals/Initiatives', 
          Attribute_Value__c ='Accenture Cloud Platform-Cloud Managed Services', 
          AttributePercent__c = 100);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
            Attribute_Type__c = 'Industry Business Services', 
          Attribute_Value__c ='D&PS-ENTERPRISE SERVICES FOR DEFENSE-DIGITAL DEFENSE TRANSFORMATION', 
          AttributePercent__c = 100);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
            Attribute_Type__c = 'Accenture Digital', 
          Attribute_Value__c ='Analytics', 
          AttributePercent__c = 0);
        objController.addAttribute();
        
        objController.attributes.clear();
        objController.offerings.clear();
        objController.ATT = new Attribute__c (
            Attribute_Type__c = 'Accenture Digital', 
          Attribute_Value__c ='Analytics', 
          AttributePercent__c = 150);
        objController.addAttribute();
        objController.offerings.clear();
        objController.collectTotal.clear();
        objController.attributes.clear();
        
        objController.ATT = new Attribute__c (
            Attribute_Type__c = 'Industry Business Services', 
          Attribute_Value__c =null, 
          AttributePercent__c = 10);
        objController.addAttribute();
        
        objController.attributes.add(new Attribute__c(
          Attribute_Check__c = true,
          Attribute_Type__c = 'Accenture Digital', 
          Attribute_Value__c ='Analytics', 
          AttributePercent__c = 10));
          
        objController.attributes.add(new Attribute__c(
          Attribute_Check__c = true,
          Attribute_Type__c = 'Accenture Digital', 
          Attribute_Value__c ='Interactive', 
          AttributePercent__c = 100));
                    
        objController.deleteAttributes();
       test.stopTest();
    }   
    
   /**
   * This testAddAttributeExt2 will test create of opportunity product and insert, update and deletion of attributes.
   * @param N/A
   * @return void
   */
     private static testmethod void testAddAttributeExt2(){    
            
    Id opportunityId = null;
    Id accountId = null;
    list<Opportunity> opp = new list<Opportunity>();
    list<Opportunity> oppError = new list<Opportunity>();
    final String accountName = 'Sample Test Account';
    Set<String> priceBookEntryNames = new Set<String> {
        'AO - CostPlus',
        'IO - CostPlus',
        'BPO - CostPlus',
        'SI - CostPlus',
        'TC - CostPlus',
        'MC - CostPlus'
    };
    List<PriceBookEntry> priceBookEntries = new List<PriceBookEntry>{};
    Map<String, Id> priceBookEntryMap = new Map<String, Id>{};
  
        Profile p = [select id from profile where name='System Administrator' limit 1];
        User u = new User();
        u.alias = 'userTest';
        u.email='user1@sample.com';
        u.emailencodingkey='UTF-8';
        u.lastname='Test';
        u.languagelocalekey='en_US';   
        u.localesidkey='en_US';
        u.profileid = p.Id;
        u.timezonesidkey='America/Los_Angeles';
        u.username='user1@sample.com.dev';
        database.insert(u,true);
        System.assertNotEquals(null, u.Id);
        
        for (PriceBookEntry entry :[SELECT Id, Name FROM PriceBookEntry WHERE Name IN :priceBookEntryNames AND Pricebook2.IsStandard = true]) {
            priceBookEntryMap.put(entry.Name, entry.Id);
        }
        
        RecordType clientRecType = [Select Id FROM RecordType WHERE Name = 'Client' LIMIT 1];
      
        Account testAcc  = new Account();
        testAcc.RecordTypeId = clientRecType.Id;
        testAcc.name = accountName;
        testAcc.Status__c = 'Active';
        testAcc.Type = 'Client';
        testAcc.Client_Account_Lead__c = u.id; 
        testAcc.Client_Classification__c = 'Diamond'; 
        database.insert(testAcc,true);
        accountid = testAcc.id;

        Opportunity testOpp = new Opportunity();
        testOpp.Name = 'Opportunity Test Class Zero';
        testOpp.AccountId = accountid; //'001q0000006jVaf';
        testOpp.Source__c = 'Salesforce';
        testOpp.STATUS_STAGE_REQUESTED__C = '0';
        testOpp.Proposal_Submission_Date__c=System.today() + 4;
        testOpp.Draft_RFP_Release_Date__c=System.today() + 2;
        testOpp.Actual_Contract_Sign_Date__c=System.today() + 20;
        testOpp.RFP_RELEASE_DATE__C = System.today() + 3;
        testOpp.CLOSEDATE = System.today() + 115; 
        testOpp.REPORTING_STATUS_SINCE__C = System.today() - 30; 
        testOpp.TYPE = 'Competitive';
        testOpp.STAGENAME = '0';
        testOpp.APPROVED_STATUS_STAGE__C = '0';
        testOpp.REPORTING_STATUS__C = 'Unqualified';
        testOpp.Consulting_Start__c  = System.today() + 120; 
        testOpp.Consulting_End__c = System.today() + 210;   
        testOpp.Outsourcing_Start__c = System.today() + 150; 
        testOpp.Outsourcing_End__c  = System.today() + 240; 
        testOpp.Hierarchy_Level__c = 'Standalone';
        testOpp.Probability = 0.1;
        testOpp.PoC_Responsible__c = testPersonGlobalId;
        testOpp.Sales_Committed_for_First_Year__c = 2344;
        database.insert(testOpp,true);
        
        Person__c testPerson = new Person__c(
            Name='Test name',
            email__c='test@email.com',
            user_type__c='AFS'
        ); 
        database.insert(testPerson,true);
        
        Opportunity_Team_Roles__c testOppTR = new Opportunity_Team_Roles__c();
        testOppTR.Opportunity_Name__c = testOpp.Id;
        testOppTR.Name__c = testPerson.id;
        testOppTR.Role__c = 'Opportunity Director';
        testOppTR.Opportunity_Access__c = 'Read Only';
        testOppTR.Sales_Credit__c= 2;
        database.insert(testOppTR,True);
        
        Opportunity_Team_Roles__c testOppTR2 = new Opportunity_Team_Roles__c();
        testOppTR2.Opportunity_Name__c = testOpp.Id;
        testOppTR2.Name__c = testPerson.id;
        testOppTR2.Role__c = 'Opportunity QA Director';
        testOppTR2.Opportunity_Access__c = 'Read Only';
        testOppTR.Sales_Credit__c= 0;
        database.insert(testOppTR2,True);        
        
        Opportunity testOpp1 = new Opportunity();
        testOpp1.id = testOpp.Id;
        testOpp.Source__c = 'Salesforce';
        testOpp1.STATUS_STAGE_REQUESTED__C = '1A';
        testOpp1.Best_Probable_Worst__c = 'Probable Win';
        testOpp1.Client_Industry_Area_of_Service__c = 'None Apply';
        testOpp1.Complexity_Category__c = 'CB: Cross border client contract';
        testOpp1.Export_Transfer_of_Products_Software__c  = 'No';
        testOpp1.Hierarchy_Level__c = 'Contract Vehicle';
        testOpp1.Industry_Sub_Segment__c  = 'D&PS OTHER';
        testOpp1.ONCONUS_Work_Required__c  = 'Yes';
        testOpp1.Primary_Function__c  = 'Business Process Outsourcing';
        testOpp1.Is_AFS_Prime_or_Subcontractor__c = 'Prime';
        testOpp1.Proposal_Submission_Date__c = System.today() + 10;
        testOpp1.RFP_Release_Date__c = System.today() + 5;
        testOpp1.The_Opportunity_involves_activities_now__c = 'No';
        testOpp1.Subject_countries_client_operates__c = 'None Apply';
        testOpp1.Win_Probability__c = '50';
        
        database.update(testOpp1,false);
        
        List<OpportunityLineItem> listOppItem = new List<OpportunityLineItem>();
        
        OpportunityLineItem testOppLI1 = new OpportunityLineItem();
        testOppLI1.OpportunityId = testOpp.id;
        testOppLI1.PriceBookEntryId = priceBookEntryMap.get('AO - CostPlus');
        testOppLI1.Revenue__c = 1000000;
        testOppLI1.Total_Costs__c = 100;
        testOppLI1.Type__c ='01 - AO';
        database.insert(testOppLI1,True);
        
        OpportunityLineItem testOppLI2 = new OpportunityLineItem();
        testOppLI2.OpportunityId = testOpp.id;
        testOppLI2.PriceBookEntryId = priceBookEntryMap.get('MC - CostPlus');
        testOppLI2.Revenue__c = 1000000;
        testOppLI2.Total_Costs__c = 100;
        testOppLI2.HW_SW_Costs__c = 0;
        testOppLI2.Type__c ='04 - MC';
        database.insert(testOppLI2,True);
        
        OpportunityLineItem testOppLI3 = new OpportunityLineItem();
        testOppLI3.OpportunityId = testOpp.id;
        testOppLI3.PriceBookEntryId = priceBookEntryMap.get('SI - CostPlus');
        testOppLI3.Revenue__c = 1000000;
        testOppLI3.Total_Costs__c = 100;
        testOppLI3.HW_SW_Costs__c = 0;
        testOppLI3.Type__c ='05 - SI';
        database.insert(testOppLI3,True);
        
        OpportunityLineItem testOppLI4 = new OpportunityLineItem();
        testOppLI4.OpportunityId = testOpp.id;
        testOppLI4.PriceBookEntryId = priceBookEntryMap.get('TC - CostPlus');
        testOppLI4.Revenue__c = 1000000;
        testOppLI4.Total_Costs__c = 100;
        testOppLI4.HW_SW_Costs__c = 0;
        testOppLI4.Type__c ='06 - TC';
        database.insert(testOppLI4,True);
        
        OpportunityLineItem testOppLI5 = new OpportunityLineItem();
        testOppLI5.OpportunityId = testOpp.id;
        testOppLI5.PriceBookEntryId = priceBookEntryMap.get('IO - CostPlus');
        testOppLI5.Revenue__c = 1000000;
        testOppLI5.Total_Costs__c = 100;
        testOppLI5.HW_SW_Costs__c = 0;
        testOppLI5.Type__c ='IO';
        database.insert(testOppLI5,True);
        
        test.startTest();
        List<Attribute__c> testAtts = new List<Attribute__c>();
        Attribute__c testAtt1 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Accenture Digital',
        Attribute_Value__c = 'Analytics',
        AttributePercent__c = 20);
                
        testAtts.add(testAtt1);
        
        database.insert(testAtts,true);
        
        ApexPages.currentPage().getParameters().put('id',testOpp.id);
          
        List <Attribute__c> attrib = [SELECT Name, id,Attribute_Check__c ,Attribute_TypeName__c, Attribute_Type__c, AttributeTxt__c, Attribute_Value__c, AttributePercent__c,Opportunity_Name__c FROM Attribute__c WHERE Opportunity_Name__c = :testOpp.id  ORDER BY Attribute_Type__c, Attribute_Value__c ASC LIMIT 50000];
        
        System.debug('AttributeVal: ' + attrib);
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(attrib);      
        AddAttributeExt objController  = new AddAttributeExt(ssc);

        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'Agilex - Standalone', 
        AttributePercent__c = 10);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'Agilex - Standalone', 
        AttributePercent__c = 150);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'Agilex - Standalone', 
        AttributePercent__c = 0);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'Agilex - Standalone', 
        AttributePercent__c = 100);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'Agilex - Standalone', 
        AttributePercent__c = 150);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'ASM - Synergy', 
        AttributePercent__c = 150);
        objController.addAttribute();
        
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'ASM - Synergy', 
        AttributePercent__c = 100);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'ASM - Synergy', 
        AttributePercent__c = 150);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'AO Offerings', 
        Attribute_Value__c = 'AO-Application Management', 
        AttributePercent__c = 100);
        objController.addAttribute(); 
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'IO Offerings', 
        Attribute_Value__c = 'IO-Data Center & Cloud Operations', 
        AttributePercent__c = 100);
        objController.addAttribute(); 
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'MC Offerings', 
        Attribute_Value__c = 'Analytics', 
        AttributePercent__c = 100);
        objController.addAttribute(); 
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'TC Offerings', 
        Attribute_Value__c = 'TC-Data Center Transformation', 
        AttributePercent__c = 100);
        objController.addAttribute(); 
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'SI Offerings', 
        Attribute_Value__c = 'SI-Application Svcs for Java', 
        AttributePercent__c = 100);
        objController.addAttribute(); 
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'SI Offerings', 
        Attribute_Value__c = 'SI-Application Svcs for Java', 
        AttributePercent__c = 100);
        objController.addAttribute(); 
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Accenture Digital', 
        Attribute_Value__c = 'Analytics', 
        AttributePercent__c = 20);
        objController.addAttribute(); 
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Accenture Digital', 
        Attribute_Value__c = 'Interactive', 
        AttributePercent__c = 20);
        objController.addAttribute(); 
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Horizontals/Initiatives', 
        Attribute_Value__c = 'Accenture Cloud Platform-Cloud Managed Services', 
        AttributePercent__c = 100);
        objController.addAttribute(); 
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Alliance', 
        Attribute_Value__c = 'MICROSOFT', 
        AttributePercent__c = 100);
        objController.addAttribute(); 
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Alliance', 
        Attribute_Value__c = 'ADOBE', 
        AttributePercent__c = 100);
        objController.addAttribute();
        
        System.debug('attributesVal: ' + objController.attributes);

        test.stopTest();
    }   
   /**
   * This testAddAttributeExt3 will test create of opportunity product and insert, update and deletion of attributes.
   * @param N/A
   * @return void
   */
    private static testmethod void testAddAttributeExt3(){    
            
    Id opportunityId = null;
    Id accountId = null ;
    list<Opportunity> opp = new list<Opportunity>();
    list<Opportunity> oppError = new list<Opportunity>();
    final String accountName = 'Sample Test Account';
    Set<String> priceBookEntryNames = new Set<String> {
        'AO - CostPlus',
        'IO - CostPlus',
        'BPO - CostPlus',
        'SI - CostPlus',
        'TC - CostPlus',
        'MC - CostPlus'
    };
    List<PriceBookEntry> priceBookEntries = new List<PriceBookEntry>{};
    Map<String, Id> priceBookEntryMap = new Map<String, Id>{};
  
        Profile p = [select id from profile where name='System Administrator' limit 1];
        User u = new User();
        u.alias = 'userTest';
        u.email='user1@sample.com';
        u.emailencodingkey='UTF-8';
        u.lastname='Test';
        u.languagelocalekey='en_US';   
        u.localesidkey='en_US';
        u.profileid = p.Id;
        u.timezonesidkey='America/Los_Angeles';
        u.username='user1@sample.com.dev';
        database.insert(u,true);
        System.assertNotEquals(null, u.id);
        
        for (PriceBookEntry entry :[SELECT Id, Name FROM PriceBookEntry WHERE Name IN :priceBookEntryNames AND Pricebook2.IsStandard = true]) {
            priceBookEntryMap.put(entry.Name, entry.Id);
        }
        
        RecordType clientRecType = [Select Id FROM RecordType WHERE Name = 'Client' LIMIT 1];
      
        Account testAcc  = new Account();
        testAcc.RecordTypeId = clientRecType.Id;
        testAcc.name = accountName;
        testAcc.Status__c = 'Active';
        testAcc.Type = 'Client';
        testAcc.Client_Account_Lead__c = u.id; 
        testAcc.Client_Classification__c = 'Diamond'; 
        database.insert(testAcc,true);
        accountid = testAcc.id;

        Opportunity testOpp = new Opportunity();
        testOpp.Name = 'Opportunity Test Class Zero';
        testOpp.AccountId = accountid; //'001q0000006jVaf';
        testOpp.Source__c = 'Salesforce';
        testOpp.STATUS_STAGE_REQUESTED__C = '0';
        testOpp.Proposal_Submission_Date__c=System.today() + 4;
        testOpp.Draft_RFP_Release_Date__c=System.today() + 2;
        testOpp.Actual_Contract_Sign_Date__c=System.today() + 20;
        testOpp.RFP_RELEASE_DATE__C = System.today() + 3;
        testOpp.CLOSEDATE = System.today() + 115; 
        testOpp.REPORTING_STATUS_SINCE__C = System.today() - 30; 
        testOpp.TYPE = 'Competitive';
        testOpp.STAGENAME = '0';
        testOpp.APPROVED_STATUS_STAGE__C = '0';
        testOpp.REPORTING_STATUS__C = 'Unqualified';
        testOpp.Consulting_Start__c  = System.today() + 120; 
        testOpp.Consulting_End__c = System.today() + 210;   
        testOpp.Outsourcing_Start__c = System.today() + 150; 
        testOpp.Outsourcing_End__c  = System.today() + 240; 
        testOpp.Hierarchy_Level__c = 'Standalone';
        testOpp.Probability = 0.1;
        testOpp.PoC_Responsible__c = testPersonGlobalId;
        testOpp.Sales_Committed_for_First_Year__c = 433;
        database.insert(testOpp,true);
        
        Person__c testPerson = new Person__c(
            Name='Test name',
            email__c='test@email.com',
            user_type__c='AFS'
        ); 
        database.insert(testPerson,true);
        
        Opportunity_Team_Roles__c testOppTR = new Opportunity_Team_Roles__c();
        testOppTR.Opportunity_Name__c = testOpp.Id;
        testOppTR.Name__c = testPerson.id;
        testOppTR.Role__c = 'Opportunity Director';
        testOppTR.Opportunity_Access__c = 'Read Only';
        testOppTR.Sales_Credit__c= 2;
        database.insert(testOppTR,True);
        
        Opportunity_Team_Roles__c testOppTR2 = new Opportunity_Team_Roles__c();
        testOppTR2.Opportunity_Name__c = testOpp.Id;
        testOppTR2.Name__c = testPerson.id;
        testOppTR2.Role__c = 'Opportunity QA Director';
        testOppTR2.Opportunity_Access__c = 'Read Only';
        testOppTR.Sales_Credit__c= 0;
        database.insert(testOppTR2,True);        
        
        Opportunity testOpp1 = new Opportunity();
        testOpp1.id = testOpp.Id;
        testOpp.Source__c = 'Salesforce';
        testOpp1.STATUS_STAGE_REQUESTED__C = '1A';
        testOpp1.Best_Probable_Worst__c = 'Probable Win';
        testOpp1.Client_Industry_Area_of_Service__c = 'None Apply';
        testOpp1.Complexity_Category__c = 'CB: Cross border client contract';
        testOpp1.Export_Transfer_of_Products_Software__c  = 'No';
        testOpp1.Hierarchy_Level__c = 'Contract Vehicle';
        testOpp1.Industry_Sub_Segment__c  = 'D&PS OTHER';
        testOpp1.ONCONUS_Work_Required__c  = 'Yes';
        testOpp1.Primary_Function__c  = 'Business Process Outsourcing';
        testOpp1.Is_AFS_Prime_or_Subcontractor__c = 'Prime';
        testOpp1.Proposal_Submission_Date__c = System.today() + 10;
        testOpp1.RFP_Release_Date__c = System.today() + 5;
        testOpp1.The_Opportunity_involves_activities_now__c = 'No';
        testOpp1.Subject_countries_client_operates__c = 'None Apply';
        testOpp1.Win_Probability__c = '50';
        
        database.update(testOpp1,false);
        
        List<OpportunityLineItem> listOppItem = new List<OpportunityLineItem>();
        
        OpportunityLineItem testOppLI1 = new OpportunityLineItem();
        testOppLI1.OpportunityId = testOpp.id;
        testOppLI1.PriceBookEntryId = priceBookEntryMap.get('AO - CostPlus');
        testOppLI1.Revenue__c = 1000000;
        testOppLI1.Total_Costs__c = 100;
        testOppLI1.Type__c ='01 - AO';
        database.insert(testOppLI1,True);
        
        OpportunityLineItem testOppLI2 = new OpportunityLineItem();
        testOppLI2.OpportunityId = testOpp.id;
        testOppLI2.PriceBookEntryId = priceBookEntryMap.get('MC - CostPlus');
        testOppLI2.Revenue__c = 1000000;
        testOppLI2.Total_Costs__c = 100;
        testOppLI2.HW_SW_Costs__c = 0;
        testOppLI2.Type__c ='04 - MC';
        database.insert(testOppLI2,True);
        
        OpportunityLineItem testOppLI3 = new OpportunityLineItem();
        testOppLI3.OpportunityId = testOpp.id;
        testOppLI3.PriceBookEntryId = priceBookEntryMap.get('SI - CostPlus');
        testOppLI3.Revenue__c = 1000000;
        testOppLI3.Total_Costs__c = 100;
        testOppLI3.HW_SW_Costs__c = 0;
        testOppLI3.Type__c ='05 - SI';
        database.insert(testOppLI3,True);
        
        OpportunityLineItem testOppLI4 = new OpportunityLineItem();
        testOppLI4.OpportunityId = testOpp.id;
        testOppLI4.PriceBookEntryId = priceBookEntryMap.get('TC - CostPlus');
        testOppLI4.Revenue__c = 1000000;
        testOppLI4.Total_Costs__c = 100;
        testOppLI4.HW_SW_Costs__c = 0;
        testOppLI4.Type__c ='06 - TC';
        database.insert(testOppLI4,True);
        
        OpportunityLineItem testOppLI5 = new OpportunityLineItem();
        testOppLI5.OpportunityId = testOpp.id;
        testOppLI5.PriceBookEntryId = priceBookEntryMap.get('IO - CostPlus');
        testOppLI5.Revenue__c = 1000000;
        testOppLI5.Total_Costs__c = 100;
        testOppLI5.HW_SW_Costs__c = 0;
        testOppLI5.Type__c ='IO';
        database.insert(testOppLI5,True);
        
        test.startTest();
        List<Attribute__c> testAtts = new List<Attribute__c>();
        Attribute__c testAtt1 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Accenture Digital',
        Attribute_Value__c = 'Analytics',
        AttributePercent__c = 20);
                
        testAtts.add(testAtt1);
        
        Attribute__c testAtt2 = new Attribute__c (Opportunity_Name__c = testOpp.Id,    
        Attribute_Type__c = 'Accenture Digital',
        Attribute_Value__c = 'Mobility',
        AttributePercent__c = 0);
                
        testAtts.add(testAtt2);
        
        database.insert(testAtts,true);
        
        ApexPages.currentPage().getParameters().put('id',testOpp.id);
          
        List <Attribute__c> attrib = [SELECT Name, id,Attribute_Check__c ,Attribute_TypeName__c, Attribute_Type__c, AttributeTxt__c, Attribute_Value__c, AttributePercent__c,Opportunity_Name__c FROM Attribute__c WHERE Opportunity_Name__c = :testOpp.id  ORDER BY Attribute_Type__c, Attribute_Value__c ASC LIMIT 50000];
        
        System.debug('AttributeVal: ' + attrib);
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(attrib);      
        AddAttributeExt objController  = new AddAttributeExt(ssc);

        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Ventures & Acquisitions', 
        Attribute_Value__c = 'Agilex - Standalone', 
        AttributePercent__c = 100);
        objController.addAttribute();
        
        objController.ATT = new Attribute__c (
        Opportunity_Name__c = testOpp.id, 
        Attribute_Type__c = 'Accenture Digital', 
        Attribute_Value__c = 'Analytics', 
        AttributePercent__c = 10);
        objController.addAttribute();

        test.stopTest();
    }  
}