AFS_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <description>Reflects Client Portfolio Management (CPM) classification (Diamond, Foundation, Portfolio or Opportunistic).</description>
        <label>Client Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Mega Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunistic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>The entity who will receive the services or products AFS provides (e.g., DC Department of Healthcare Finance). Selecting this Account Record Type will allow you to create a new AFS client to associate with new opportunities, contacts, and/or activities.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approved_Status_Stage__c</fullName>
        <inlineHelpText>Status/Stage the Sales Ops will approve the opportunity record to once the opportunity has gone through all approval processes</inlineHelpText>
        <label>Approved Status/Stage</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <formula>TEXT(Account.Client_Classification__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Classification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Team_Roles__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Team Roles</label>
        <referenceTo>Opportunity_Team_Roles__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporting_Status__c</fullName>
        <inlineHelpText>Field updated based on the stage of the opportunity through workflow. Reporting Status is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status</label>
        <picklist>
            <controllingField>Approved_Status_Stage__c</controllingField>
            <picklistValues>
                <fullName>Lost</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
                <color>#A845DC</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Stage_Requested__c</fullName>
        <inlineHelpText>Use this field to request advancement to a subsequent stage when all required fields are complete.
Please note: there may be additional fields on the Related Lists (e.g., Financial Details, Attributes, Opp Team Roles) that are required for advancement.</inlineHelpText>
        <label>Status/Stage Requested</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity_Team_Roles__c.object
<CustomObject>
    <description>This is an object for the Opportunity Team and Sales Credit Records.</description>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Name</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Opportunity Team Roles</relationshipLabel>
        <relationshipName>Opportunity_Teams_Sales_Credit</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <inlineHelpText>Salesforce License is required for access to be applicable.</inlineHelpText>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Teams_Sales_Credit</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Alliance Business Development Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capture Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Management Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deal Shaper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horizontal Business Development Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key Member of Opp.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity QA Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRG Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Architect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Credit__c</fullName>
        <label>Sales Credit %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Service_Group__c</fullName>
        <inlineHelpText>Service Group is required if the role, Solution Architect, was selected</inlineHelpText>
        <label>Service Group</label>
        <picklist>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Opportunity Team Roles</label>
    <nameField>
        <displayFormat>ID-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Team Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Person__c.object
<CustomObject>
    <description>This object is taking place of the user object where user names will be stored.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stores Active Directory user status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>AFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Contractor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/classes/OpportunityTeamRoleBLTest.cls
/**
 * Class Name: OpportunityTeamRoleBLTest
 * @author: Lhea Valencia
 * Date: 02/19/2015
 * Test Class for OpportunityTeamRoleBL
 */
@isTest(SeeAllData=true)
private class OpportunityTeamRoleBLTest{
    
    private static id opportunityId;
    private static id personId;
    private static id personId2;
    private static Opportunity_Team_Roles__c oppTR;
    
    /** Preparation Data for test */ 
    static testmethod void prepdata() {
        // Create Test User
        Profile p = [select id from profile where name='System Administrator' limit 1];
        User u = new User(
        alias = 'user1A',
        email='user1@sample.com',
        emailencodingkey='UTF-8',
        lastname='DOe',
        languagelocalekey='en_US',
        localesidkey='en_US',
        profileid = p.Id,
        timezonesidkey='America/Los_Angeles',
        username='user1@sample.com.dev'
        );
        database.insert(u,false);
        system.assertEquals(u,u);
    
        // Create Test Account
        RecordType clientRecType = [Select Id FROM RecordType WHERE Name = 'Client' LIMIT 1];
        Account testAcc  = new Account();
        testAcc.RecordTypeId = ClientRecType.Id;
        testAcc.name = 'Sample Test Account Acc';
        testAcc.Status__c = 'Active';
        testAcc.Type = 'Client';
        testAcc.Client_Account_Lead__c = u.id; 
        testAcc.Client_Classification__c = 'Diamond'; 
        database.insert(testAcc,false);
  
        /*
        * - Test Opportunity
        */
        
        Opportunity testOpp = new Opportunity();
        testOpp.Name = 'Sample Test Account Acc Opp 1';
        testOpp.AccountId = testAcc.Id;
        testOpp.StageName = '0';
        testOpp.Reporting_Status__c = 'Unqualified';
        testOpp.Type = 'Competitive';
        testOpp.CloseDate = System.today() + 30;
        testOpp.Approved_Status_Stage__c = '0';
        testOpp.Probability = 10;
        testOpp.STATUS_STAGE_REQUESTED__C = '0';
        database.insert(testOpp,false);
        //insert testOpp;
        opportunityId = testOpp.Id;
        
        /*
        * - Test Person
        */
        
        Person__c testPerson = new Person__c();
        testPerson.Name = 'Dana Smith';
        testPerson.Email__c = 'user1@sample.com';
        testPerson.User_Type__c = 'AFS';
        database.insert(testPerson,false);
        
        personId = testPerson.Id;
        
        /*
        * - Test Person2
        */
        
        Person__c testPerson2 = new Person__c();
        testPerson2.Name = 'Dana Smith2';
        testPerson2.Email__c = 'user1@sample.com';
        testPerson2.User_Type__c = 'AFS';
        database.insert(testPerson2,false);
        
        personId2 = testPerson2.Id;
        
        /*
        * - Test Opportunity Team Role
        */
        
        Opportunity_Team_Roles__c testOTRole = new Opportunity_Team_Roles__c();
        testOTRole.Opportunity_Name__c = testOpp.Id;
        testOTRole.Name__c = testPerson.Id;
        testOTRole.Role__c = 'Capture Lead';
        testOTRole.Opportunity_Access__c = 'Read Only';
        testOTRole.Sales_Credit__c = 37;
        testOTRole.Service_Group__c = 'AO';
        database.insert(testOTRole,false);
        
        /*
        * - Test Opportunity Team Role 2
        */
        
        Opportunity_Team_Roles__c testOTRole4 = new Opportunity_Team_Roles__c();
        testOTRole4.Opportunity_Name__c = testOpp.Id;
        testOTRole4.Name__c = testPerson.Id;
        testOTRole4.Role__c = 'Capture Lead';
        testOTRole4.Opportunity_Access__c = 'Read/Write';
        testOTRole4.Sales_Credit__c = 3;
        testOTRole4.Service_Group__c = 'AO';
        database.insert(testOTRole4,false);        
        
        Opportunity_Team_Roles__c testOTRole5 = new Opportunity_Team_Roles__c();
        testOTRole5.Opportunity_Name__c = testOpp.Id;
        testOTRole5.Name__c = testPerson.Id;
        testOTRole5.Role__c = 'Delivery Lead';
        testOTRole5.Opportunity_Access__c = 'Read Only';
        testOTRole5.Sales_Credit__c = 3;
        testOTRole5.Service_Group__c = 'AO';
        database.insert(testOTRole5,false);
        //insert testOTRole5;
        oppTR = testOTRole5;
    }
    /**Validates Sales Credit */ 
    static testmethod void testValidateSalesCredit() {
  
        prepdata();
        system.test.startTest();
  
        Opportunity_Team_Roles__c testOTRole4 = new Opportunity_Team_Roles__c();
        testOTRole4.Opportunity_Name__c = opportunityId;
        testOTRole4.Name__c = personId;
        testOTRole4.Role__c = 'Capture Lead';
        testOTRole4.Opportunity_Access__c = 'Read Only';
        testOTRole4.Sales_Credit__c = 45;
        testOTRole4.Service_Group__c = 'AO';    
        database.insert(testOTRole4,false);     
        
        try{
  
        Opportunity_Team_Roles__c testOTRole3 = new Opportunity_Team_Roles__c();
        testOTRole3.Opportunity_Name__c = opportunityId;
        testOTRole3.Name__c = personId;
        testOTRole3.Role__c = 'Capture Lead';
        testOTRole3.Opportunity_Access__c = 'Read Only';
        testOTRole3.Sales_Credit__c = 45;
            testOTRole3.Service_Group__c = 'AO';    
        database.insert(testOTRole3,false);  
        
        } catch (DMLException e) {
        //Assert Error Message
            System.assert( e.getMessage().contains('limit exceeded on user'), 
                e.getMessage() );             
        }
  
        try {
        Opportunity_Team_Roles__c testOTRole2 = new Opportunity_Team_Roles__c();
        testOTRole2.Opportunity_Name__c = opportunityId;
        testOTRole2.Name__c = personId2;
        testOTRole2.Role__c = 'Capture Lead';
        testOTRole2.Opportunity_Access__c = 'Read Only';
        testOTRole2.Sales_Credit__c = 73;
            testOTRole2.Service_Group__c = 'AO';
        database.insert(testOTRole2,false);  
        
        } catch (DMLException e) {
        //Assert Error Message
            System.assert( e.getMessage().contains('limit exceeded on role'), 
                e.getMessage() );   
        }
        
        //this is to satisfy the update, delete and undelete in OpportunityTeamRoleHandler
        oppTR.Sales_Credit__c = 1;
        database.update(oppTR,false);
        database.delete(oppTR,false);
        database.undelete(oppTR,false);
        system.test.stopTest();
  
    }
  
  
  
  
}