AFS_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <description>Reflects Client Portfolio Management (CPM) classification (Diamond, Foundation, Portfolio or Opportunistic).</description>
        <label>Client Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Mega Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunistic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_QA_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client QA Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Managing_Director_MC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MC Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operations_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operations Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P_Global_Client_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Executive responsible for managing the relationship with an AFS Client. Global Client Account Lead may oversee several Clients.</description>
        <label>Global Client Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Technology_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technology Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>The entity who will receive the services or products AFS provides (e.g., DC Department of Healthcare Finance). Selecting this Account Record Type will allow you to create a new AFS client to associate with new opportunities, contacts, and/or activities.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AFS_High_Priority_Deal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It&apos;s the record the Sales Team keep to track capture/deal shaper coverage on key deals. This is a new admin-only field to capture.</description>
        <inlineHelpText>It&apos;s the record the Sales Team keep to track capture/deal shaper coverage on key deals.</inlineHelpText>
        <label>AFS High Priority Deal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Actual_Contract_Sign_Date_Quater__c</fullName>
        <label>Actual Contract Sign Date Quater</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Contract_Sign_Date__c</fullName>
        <inlineHelpText>Date the contract was signed by the client. Date field must always be after the Draft RFP Release Date, RFP Release Date, Proposal Submission Date, but may equal to the Expected Contract Sign Date.</inlineHelpText>
        <label>Actual Contract Sign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approved_Status_Stage__c</fullName>
        <inlineHelpText>Status/Stage the Sales Ops will approve the opportunity record to once the opportunity has gone through all approval processes</inlineHelpText>
        <label>Approved Status/Stage</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Black_Hat_Review__c</fullName>
        <inlineHelpText>Optional field that is tracked in the Time Over Target (TOT) file that is used to track Top Opps and AFS High Priority Deals. Field generally completed by Leadership; leave field blank if date unknown.</inlineHelpText>
        <label>Black Hat Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <formula>TEXT(Account.Client_Classification__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Classification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_QA_Director__c</fullName>
        <formula>Account.Client_QA_Director__r.FirstName  &amp; &quot; &quot; &amp;  Account.Client_QA_Director__r.LastName</formula>
        <label>Client QA Director</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consulting_End__c</fullName>
        <inlineHelpText>Start/End Dates should reflect the base award/booked sale represented by the Total Current Revenue</inlineHelpText>
        <label>Consulting End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Consulting_Start__c</fullName>
        <inlineHelpText>Date the Consulting portion of the contract is expected to begin. Field is required if the Financial Details Related List includes MC, SI, or TC Service Groups.</inlineHelpText>
        <label>Consulting Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Draft_RFP_Release_Date__c</fullName>
        <inlineHelpText>Anticipated release date of the Draft RFP. This date field may be equal to or before the &quot;RFP Release&quot; date field.</inlineHelpText>
        <label>Draft RFP Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Follow_On_Revenue__c</fullName>
        <inlineHelpText>Indicate the additional value beyond TCR (base period) to which AFS is committed (e.g., options). Follow-on Revenue should be retained in the base period record when option records are created.</inlineHelpText>
        <label>Follow On Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Level__c</fullName>
        <description>Standalone (or Full &amp; Open): Procurement issued as a standalone contract; opportunities that are not a Contract Vehicle or Task Order under a Contract Vehicle should be classified as Standalone. 

Contract Vehicle: Procurement is an IDIQ or BPA vehicle that AFS is pursuing as a new award. 
 
Task Order: Procurement is a Task Order issued on an existing Contract Vehicle.</description>
        <inlineHelpText>Standalone: Indicates if a procurement is full and open

Contract Vehicle: IDIQ/BPA

Task Order: Opportunity under an existing contract vehicle</inlineHelpText>
        <label>Hierarchy Level</label>
        <picklist>
            <picklistValues>
                <fullName>Contract Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standalone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Managing_Director_MC__c</fullName>
        <formula>Account.Managing_Director_MC__r.FirstName &amp; &quot; &quot; &amp; Account.Managing_Director_MC__r.LastName</formula>
        <label>MC Account Lead</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outsourcing_End__c</fullName>
        <inlineHelpText>Date the Outsourcing portion of the contract will be complete.</inlineHelpText>
        <label>Outsourcing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_Start__c</fullName>
        <inlineHelpText>Start/End Dates should reflect the base award/booked sale represented by the Total Current Revenue</inlineHelpText>
        <label>Outsourcing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PTW_Review__c</fullName>
        <inlineHelpText>Optional field that is tracked in the Time Over Target (TOT) file that is used to track Top Opps and AFS High Priority Deals. Field generally completed by Leadership; leave field blank if date unknown.</inlineHelpText>
        <label>PTW Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Peak_Capital_Balance__c</fullName>
        <description>Peak Capital Balance is the highest capital balance in any one month during the contract. Most commonly, it results from billing in arrears and recognizing revenue in the month of service, which generates an unbilled services balance.</description>
        <inlineHelpText>Highest capital balance in any one month during the contract. Entered as a dollar amount. User may enter 0 as a value if there is no Peak Capital Balance.</inlineHelpText>
        <label>Peak Capital Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Proposal_Submission_Date__c</fullName>
        <inlineHelpText>Date AFS submitted the proposal. The Proposal Submission Date should always be before both the Expected Contract Sign Date and Actual Contract Sign Date.</inlineHelpText>
        <label>Proposal Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFP_Release_Date__c</fullName>
        <inlineHelpText>Date RFP was released. This field is used for tracking purposes. This date field must always come before the &quot;Proposal Submission Date&quot; field but may be equal to the Draft RFP Release Date.</inlineHelpText>
        <label>RFP Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Status_Since__c</fullName>
        <inlineHelpText>Tracks the date that an opportunity advancement request was submitted. Reporting Status Date is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Status__c</fullName>
        <inlineHelpText>Field updated based on the stage of the opportunity through workflow. Reporting Status is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status</label>
        <picklist>
            <controllingField>Approved_Status_Stage__c</controllingField>
            <picklistValues>
                <fullName>Lost</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
                <color>#A845DC</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Solution_Baseline_Review__c</fullName>
        <inlineHelpText>Optional field that is tracked in the Time Over Target (TOT) file that is used to track Top Opps and AFS High Priority Deals. Field generally completed by Leadership; leave field blank if date unknown.</inlineHelpText>
        <label>Solution Baseline Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Stage_Requested__c</fullName>
        <inlineHelpText>Use this field to request advancement to a subsequent stage when all required fields are complete.
Please note: there may be additional fields on the Related Lists (e.g., Financial Details, Attributes, Opp Team Roles) that are required for advancement.</inlineHelpText>
        <label>Status/Stage Requested</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Technology_Account_Lead__c</fullName>
        <formula>Account.Technology_Account_Lead__r.FirstName &amp; &quot; &quot; &amp;  Account.Technology_Account_Lead__r.LastName</formula>
        <label>Technology Account Lead</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/classes/ViewSummaryOnclickTest.cls
/**
 * Class Name: ViewSummaryOnclickTest
 * @author: Lhea Valencia
 * Date: 04/22/2015
 * Test Class for Summary_View_Onclick
 */

@isTest(SeeAllData=true) 
/*
 * @Class This class Summary_View_OnclickTest is used to test this class
 */
private class ViewSummaryOnclickTest{
/*    
    private static Id opportunityId; 
    private static final ID MAIN = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Main Record Type').getRecordTypeId();
    
     
    static void prepdata() {
        
       
        
        Profile p = [select id from profile where name='System Administrator' limit 1];
        
        User u = new User();
        u.alias = 'user1A';
        u.email='user1@sample.com';
        u.emailencodingkey='UTF-8';
        u.lastname='DOe';
        u.languagelocalekey='en_US';   
        u.localesidkey='en_US';
        u.profileid = p.Id;
        u.timezonesidkey='America/Los_Angeles';
        u.username='user1@sample.com.dev';
        
        //insert u;
        Database.insert(u, True);
        
        User usr2 = new User();
        usr2.alias = 'user2Abc';
        usr2.email='user1@sample.com';
        usr2.emailencodingkey='UTF-8';
        usr2.lastname='DOeh';
        usr2.languagelocalekey='en_US';   
        usr2.localesidkey='en_US';
        usr2.profileid = p.Id;
        usr2.timezonesidkey='America/Los_Angeles';
        usr2.username='user2@sample.com.dev';
        
        //insert usr2;
        Database.insert(usr2, false);
       
        RecordType clientRecType = [Select Id FROM RecordType WHERE Name = 'Client' LIMIT 1];
        
        Account testAcc = new Account();
        testAcc.RecordTypeId = ClientRecType.Id;
        testAcc.name = 'Sample Test Account Acc';
        testAcc.Status__c = 'Active';
        testAcc.Type = 'Client';
        testAcc.Client_Account_Lead__c = u.id; 
        testAcc.Client_QA_Director__c = usr2.id;
        testAcc.P_Global_Client_Account_Lead__c = u.id;
        testAcc.Managing_Director_MC__c = usr2.id;
        testAcc.Operations_Lead__c = u.id;
        testAcc.Technology_Account_Lead__c = usr2.id;
        testAcc.Client_Classification__c = 'Diamond'; 
        
        //insert testAcc;
        Database.insert(testAcc, false);
        
        
        
        Opportunity testOpp = new Opportunity();
        testOpp.Name = 'Sample Test Account Acc Opp 1';
        testOpp.AccountId = testAcc.Id;
        testOpp.StageName = '0';
        testOpp.Reporting_Status__c = 'Unqualified';
        testOpp.Type = 'Competitive';
        testOpp.CloseDate = System.today() + 30;
        testOpp.Approved_Status_Stage__c = '0';
        testOpp.Status_Stage_Requested__c = '0';
        testOpp.Consulting_Start__c = System.today() + 51;
        testOpp.Consulting_End__c = System.today() + 52;
        testOpp.AFS_High_Priority_Deal__c = True;
        testOpp.Actual_Contract_Sign_Date__c = System.today() + 50;
        testOpp.Actual_Contract_Sign_Date_Quater__c = System.today() + 30;
        testOpp.Stagename = '0';
        testOpp.Draft_RFP_Release_Date__c = System.today() + 20;
        testOpp.CloseDate = System.today() + 50;
        testOpp.Outsourcing_End__c = System.today() + 52;
        testOpp.Outsourcing_Start__c = System.today() + 51;
        testOpp.Peak_Capital_Balance__c = 24000;
        testOpp.Proposal_Submission_Date__c = System.today() + 40;
        testOpp.Reporting_Status__c = 'Unqualified';
        testOpp.Reporting_Status_Since__c = System.today() + 40;
        testOpp.RFP_Release_Date__c = System.today() + 25;
        testOpp.Hierarchy_Level__c = 'Standalone';
        testOpp.Follow_On_Revenue__c = 50000;
        testOpp.Solution_Baseline_Review__c = System.today() + 25;
        testOpp.Black_Hat_Review__c = System.today() + 26;
        testOpp.PTW_Review__c = System.today() + 27;
        testOpp.Color_Team_Review_Date__c = System.today() + 28;
        testOpp.PRG_Review_Date__c = System.today() + 29;
        testOpp.Date_of_Contract_Management_Review_Date__c = System.today() + 14;
        
        //insert testOpp;
        Database.insert(testOpp, True);
        OpportunityId = testOpp.id;
        system.assertNotEquals(testOpp.id, null);
    
    }
   
    static testmethod void testStageView() {
    
        prepdata();
        
        system.test.startTest();
        
        String opp = OpportunityId;
        String rectype = Main;
        
        ViewSummaryOnclick.recordtypecahng(opp , rectype.substring(0,15));
        
        System.assertEquals(Summary, [SELECT Id, recordTypeId FROM Opportunity WHERE Id =: OpportunityId LIMIT 5000][0].recordtypeId); // Default maximum of SOQL rows to 5000
        
        String errorReceived = ViewSummaryOnclick.recordtypecahng(opp , rectype.substring(0,15));
        System.assertEquals('',errorReceived);
        
       
        
        String opp2 = OpportunityId;
        String rectype2 = Summary;
        
        ViewSummaryOnclick.recordtypecahng(opp2 , rectype2.substring(0,15));
        
        System.assertEquals(Main, [SELECT Id, recordTypeId FROM Opportunity WHERE Id =: OpportunityId LIMIT 5000][0].recordtypeId); // Default maximum of SOQL rows to 5000
        
        String errorReceived2 = ViewSummaryOnclick.recordtypecahng(Null, rectype2.substring(0,15));
        String errorReceived3 = ViewSummaryOnclick.recordtypecahng(Main, rectype2.substring(0,15));
        System.assertNotEquals(null, errorReceived2);
        System.assertNotEquals(null, errorReceived3);
        
    } 
    */
}