AFS_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <description>Reflects Client Portfolio Management (CPM) classification (Diamond, Foundation, Portfolio or Opportunistic).</description>
        <label>Client Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Mega Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunistic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>The entity who will receive the services or products AFS provides (e.g., DC Department of Healthcare Finance). Selecting this Account Record Type will allow you to create a new AFS client to associate with new opportunities, contacts, and/or activities.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Account_Team_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Access__c</fullName>
        <label>Case Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Access__c</fullName>
        <label>Contact Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Team Role</label>
    <nameField>
        <displayFormat>Acc Team-{0000000}</displayFormat>
        <label>Account Team Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/classes/AccountTeamRoleTriggerTest.cls
/**
 * Class Name: AccountTeamRoleTriggerTest
 * @author: Recuerdo Bregente
 * Date: 10/20/2015
 * Test Class for AccountTeamRoleTrigger
 */
@isTest(SeeAllData=true)
private class AccountTeamRoleTriggerTest{

    static List<Account_Team_Role__c> accTeamRoles;

    /*  
    * @Method to prepare the data needed data for testing.
    */    
    static void prepdata() {
 
        List<User> users = TestData.createUsers(2, 'System Administrator');
        database.insert(users);
        
        List<Account> accounts = TestData.createAccounts(1, 'Client');
        for(Account acc : accounts) {
            acc.Client_Account_Lead__c = users[0].id;
            acc.Client_Classification__c = 'Diamond';  
        }
        
        Database.insert(accounts);
        
        accTeamRoles = TestData.createAccountTeamRoles(1, accounts[0].Id);
        for(Account_Team_Role__c accTeamRole : accTeamRoles){
            accTeamRole.Team_Member__c = users[1].Id;
        }
        
        Database.insert(accTeamRoles);
  
    }
    
    /*  
    * @Method to test all the methods of AccountTeamRoleTrigger Class.
    */  
    static testMethod void testTrigger(){
        List<Account_Team_Role__c> roles = null;
    
        //Inserts AccountTeamRole Object
        prepdata();
        
        //Updates AccountTeamRole Object
        accTeamRoles[0].Account_Access__c = 'Read Only';
        accTeamRoles[0].Case_Access__c = 'Read Only';
        accTeamRoles[0].Contact_Access__c = 'Read Only';
        accTeamRoles[0].Opportunity_Access__c = 'Read Only';
        
        Database.update(accTeamRoles);
        roles = [SELECT Id, Account_Access__c, Case_Access__c, Contact_Access__c, Opportunity_Access__c FROM Account_Team_Role__c WHERE Id = :accTeamRoles[0].Id];
       
        System.assertEquals('Read Only', roles[0].Account_Access__c);
        System.assertEquals('Read Only', roles[0].Case_Access__c);
        System.assertEquals('Read Only', roles[0].Contact_Access__c);
        System.assertEquals('Read Only', roles[0].Opportunity_Access__c);
        
        //Deletes AccountTeamRole Object
        Database.delete(accTeamRoles);
        roles = [SELECT Id FROM Account_Team_Role__c WHERE Id = :roles[0].Id];
        
        System.assertEquals(true, roles.isEmpty());
        
        //Undeletes AccountTeamRole Object
        Database.undelete(accTeamRoles);
        roles = [SELECT Id FROM Account_Team_Role__c WHERE Id = :accTeamRoles[0].Id];
        
        System.assertEquals(false, roles.isEmpty());
    }
}