AFS_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Source__c</fullName>
        <description>Captures the source of creation for the record. This will be provide the ability to differentiate if the record was created in Salesforce or is a legacy record.</description>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>STaR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Account_Team_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team Roles</relationshipLabel>
        <relationshipName>Account_Team_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Access__c</fullName>
        <label>Case Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Access__c</fullName>
        <label>Contact Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Development Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Account Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client QA Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global CAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managing Director MC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Portfolio Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology Account Lead</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Team Role</label>
    <nameField>
        <displayFormat>Acc Team-{0000000}</displayFormat>
        <label>Account Team Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Contract_Sign_Date__c</fullName>
        <inlineHelpText>Date the contract was signed by the client. Date field must always be after the Draft RFP Release Date, RFP Release Date, Proposal Submission Date, but may equal to the Expected Contract Sign Date.</inlineHelpText>
        <label>Actual Contract Sign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approved_Status_Stage__c</fullName>
        <inlineHelpText>Status/Stage the Sales Ops will approve the opportunity record to once the opportunity has gone through all approval processes</inlineHelpText>
        <label>Approved Status/Stage</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Draft_RFP_Release_Date__c</fullName>
        <inlineHelpText>Anticipated release date of the Draft RFP. This date field may be equal to or before the &quot;RFP Release&quot; date field.</inlineHelpText>
        <label>Draft RFP Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposal_Submission_Date__c</fullName>
        <inlineHelpText>Date AFS submitted the proposal. The Proposal Submission Date should always be before both the Expected Contract Sign Date and Actual Contract Sign Date.</inlineHelpText>
        <label>Proposal Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFP_Release_Date__c</fullName>
        <inlineHelpText>Date RFP was released. This field is used for tracking purposes. This date field must always come before the &quot;Proposal Submission Date&quot; field but may be equal to the Draft RFP Release Date.</inlineHelpText>
        <label>RFP Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Status_Since__c</fullName>
        <inlineHelpText>Tracks the date that an opportunity advancement request was submitted. Reporting Status Date is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesforce</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>STaR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Stage_Requested__c</fullName>
        <inlineHelpText>Use this field to request advancement to a subsequent stage when all required fields are complete.
Please note: there may be additional fields on the Related Lists (e.g., Financial Details, Attributes, Opp Team Roles) that are required for advancement.</inlineHelpText>
        <label>Status/Stage Requested</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity_Team_Roles__c.object
<CustomObject>
    <description>This is an object for the Opportunity Team and Sales Credit Records.</description>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <inlineHelpText>Salesforce License is required for access to be applicable.</inlineHelpText>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Alliance Business Development Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capture Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Management Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deal Shaper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horizontal Business Development Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key Member of Opp.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity QA Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRG Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Architect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Opportunity Team Roles</label>
    <nameField>
        <displayFormat>ID-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Team Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Person__c.object
<CustomObject>
    <description>This object is taking place of the user object where user names will be stored.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stores Active Directory user status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/classes/TestData.cls
/**
 * Class Name: TestData
 * @author: Recuerdo Bregente
 * Date: 10/20/2015
 * Class for creating test data.
 */
@isTest(SeeAllData=true)
public class TestData{

    /**
    * @Method to create new user objects to be used for test class.
    */
    public static List<User> createUsers(Integer count, String profileType){
        Profile p = [select id from profile where name=:profileType limit 1];
        List<User> users = new List<User>();
        User newUser = new User();
        
        Integer counter = 0;
        for(; counter < count; counter++){
            newUser = new User();
            String name = 'user' + (counter+1);
            newUser.alias = 'userTest';
            newUser.email= name + '@sample.com';
            newUser.emailencodingkey='UTF-8';
            newUser.lastname='Test';
            newUser.languagelocalekey='en_US';   
            newUser.localesidkey='en_US';
            newUser.profileid = p.Id;
            newUser.timezonesidkey='America/Los_Angeles';
            newUser.username= name + '@sample.com.dev';
            users.add(newUser);
        }
        
        return users;
    }
    
    /**
    * @Method to create new Account objects to be used for test class.
    */
    public static List<Account> createAccounts(Integer count, String accountType){
         RecordType clientRecType = [Select Id FROM RecordType WHERE Name =:accountType LIMIT 1];
        List<Account> accounts= new List<Account>();
        Account newAccount = new Account();
        
        Integer counter = 0;
        for(; counter < count; counter++){
            newAccount = new Account();
            newAccount.RecordTypeId = clientRecType.Id;
            newAccount.Name = 'Sample Test Account' + (counter+1);
            newAccount.Status__c = 'Active';
            newAccount.Type = accountType;
            accounts.add(newAccount);
        }
        
        return accounts;
    }
    
    /**
    * @Method to create new AccountTeamRole objects to be used for test class.
    */
    public static List<Account_Team_Role__c> createAccountTeamRoles(Integer count, Id accountId){
        List<Account_Team_Role__c> accTeamRoles = new List<Account_Team_Role__c>();
        Account_Team_Role__c newAccTeamRole = new Account_Team_Role__c();
        
        Integer counter = 0;
        for(; counter < count; counter++){
            newAccTeamRole = new Account_Team_Role__c();
            newAccTeamRole.Account__c = accountId;
            newAccTeamRole.Account_Access__c = 'Read/Write';
            newAccTeamRole.Case_Access__c = 'Read/Write';
            newAccTeamRole.Contact_Access__c = 'Read/Write';
            newAccTeamRole.Opportunity_Access__c = 'Read/Write';
            newAccTeamRole.Team_Role__c = 'General';
            accTeamRoles.add(newAccTeamRole);
        }
        
        return accTeamRoles;
    }
    
    /**
    * @Method to create new Opportunity objects to be used for test class.
    */
    public static List<Opportunity> createOpportunities(Integer count){
        List<Opportunity> opportunities = new List<Opportunity>();
        Opportunity oppRecord = new Opportunity();
        
        String SOME_VALUE = 'Some Value';
        
        Integer counter = 0;
        for(; counter < count; counter++){
            oppRecord = new Opportunity();
            oppRecord.Name = 'Opportunity Test Class Zero';
            oppRecord.Source__c = 'Salesforce';
            oppRecord.STATUS_STAGE_REQUESTED__C = '0';
            oppRecord.Proposal_Submission_Date__c=System.today() + 4;
            oppRecord.Draft_RFP_Release_Date__c=System.today() + 2;
            oppRecord.Actual_Contract_Sign_Date__c=System.today() + 20;
            oppRecord.RFP_RELEASE_DATE__C = System.today() + 3;
            oppRecord.CLOSEDATE = System.today() + 115; 
            oppRecord.REPORTING_STATUS_SINCE__C = System.today() - 30; 
            oppRecord.TYPE = 'Competitive';
            oppRecord.STAGENAME = '0';
            oppRecord.APPROVED_STATUS_STAGE__C = '0';
            oppRecord.REPORTING_STATUS__C = 'Unqualified';
            oppRecord.Consulting_Start__c  = System.today() + 120; 
            oppRecord.Consulting_End__c = System.today() + 210;   
            oppRecord.Outsourcing_Start__c = System.today() + 150; 
            oppRecord.Outsourcing_End__c  = System.today() + 240; 
            oppRecord.Hierarchy_Level__c = 'Standalone';
            oppRecord.Probability = 0.1;
            oppRecord.Sales_Committed_for_First_Year__c = 2344;
            opportunities.add(oppRecord);
        }
        
        return opportunities;
    }
    
    /**
    * @Method to create new Person objects to be used for test class.
    */
    public static List<Person__c> createPersons(Integer count){
        List<Person__c> persons = new List<Person__c>();
        Person__c personRecord = new Person__c();
        
        Integer counter = 0;
        for(; counter < count; counter++){
            personRecord = new Person__c(
            Name='Test name',
            email__c='test@email.com',
            user_type__c='AFS'
            );
            
            persons.add(personRecord);
         }
         
         return persons;
        
    }
    
    /**
    * @Method to create new Opportunity Team Role objects to be used for test class.
    */
    public static List<Opportunity_Team_Roles__c> createOppTeamRoles(Integer count){
        List<Opportunity_Team_Roles__c> oppTeamRoles = new List<Opportunity_Team_Roles__c>();
        Opportunity_Team_Roles__c oppTeamRoleRecord = new Opportunity_Team_Roles__c();
        
        Integer counter = 0;
        for(; counter < count; counter++){
            oppTeamRoleRecord = new Opportunity_Team_Roles__c();
            oppTeamRoleRecord.Role__c = 'Opportunity Director';
            oppTeamRoleRecord.Opportunity_Access__c = 'Read Only';
            oppTeamRoleRecord.Sales_Credit__c= 2;
            oppTeamRoles.add(oppTeamRoleRecord);
         }
         
         return oppTeamRoles;
    }
}