AFS_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <description>Reflects Client Portfolio Management (CPM) classification (Diamond, Foundation, Portfolio or Opportunistic).</description>
        <label>Client Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Mega Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunistic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Captures the source of creation for the record. This will be provide the ability to differentiate if the record was created in Salesforce or is a legacy record.</description>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>STaR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>The entity who will receive the services or products AFS provides (e.g., DC Department of Healthcare Finance). Selecting this Account Record Type will allow you to create a new AFS client to associate with new opportunities, contacts, and/or activities.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <formula>TEXT(Account.Client_Classification__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Classification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Team_Roles__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Team Roles</label>
        <referenceTo>Opportunity_Team_Roles__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PoC_Responsible__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Indicate who is on point to deliver this sales number?</inlineHelpText>
        <label>PoC Responsible?</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesforce</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>STaR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity_Team_Roles__c.object
<CustomObject>
    <description>This is an object for the Opportunity Team and Sales Credit Records.</description>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Name</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Opportunity Team Roles</relationshipLabel>
        <relationshipName>Opportunity_Teams_Sales_Credit</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Teams_Sales_Credit</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Team Roles</label>
    <nameField>
        <displayFormat>ID-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Team Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Person__c.object
<CustomObject>
    <description>This object is taking place of the user object where user names will be stored.</description>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/classes/UpdateOpportunityTeamBatchTest.cls
/**
 * Class Name: UpdateOpportunityTeamBatchTest
 * @author:Recuerdo Bregente    
 * Date: 11/10/2015
 * Test Class for UpdateOpportunityTeamBatch
 */
@isTest
private class UpdateOpportunityTeamBatchTest {

    
     // Prepares the data to be used in testing
     static void prepareData(){
         List<User> users = TestData.createUsers(1, 'System Administrator');
         Database.insert(users);
         
         List<Account> accounts = TestData.createAccounts(1, 'Client');
         accounts[0].Client_Account_Lead__c = users[0].id; 
         accounts[0].Client_Classification__c = 'Diamond';
         Database.insert(accounts);
         
         List<Person__c> persons = TestData.createPersons(1);
         Database.insert(persons);
         
         List<Opportunity> opportunities = TestData.createOpportunities(1);
         opportunities[0].Source__c = 'STaR';
         opportunities[0].AccountId = accounts[0].Id;
         opportunities[0].PoC_Responsible__c = persons[0].Id;
         Database.insert(opportunities);
         
         opportunities[0].Source__c = 'STaR';
         Database.update(opportunities);
         
         List<Opportunity_Team_Roles__c> oppTeamRoles = TestData.createOppTeamRoles(1);
         oppTeamRoles[0].Opportunity_Name__c = opportunities[0].Id;
         oppTeamRoles[0].Name__c = persons[0].Id;
         Database.insert(oppTeamRoles);
     }
        
     // Tests the batch class
     static testmethod void testBatch() {
     
        prepareData();
        
        boolean isErrorExists = false;
        
        try{
            system.test.startTest();
            UpdateOpportunityTeamBatch batch = new UpdateOpportunityTeamBatch();
            database.executeBatch(batch); 
            system.test.stopTest();
        }
        catch(Exception e){
            isErrorExists = true;
        }
        
        System.assertEquals(false, isErrorExists);
     }
}