AFS_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <description>Reflects Client Portfolio Management (CPM) classification (Diamond, Foundation, Portfolio or Opportunistic).</description>
        <label>Client Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Mega Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunistic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>The entity who will receive the services or products AFS provides (e.g., DC Department of Healthcare Finance). Selecting this Account Record Type will allow you to create a new AFS client to associate with new opportunities, contacts, and/or activities.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Account_Team_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team_Roles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team Roles</relationshipLabel>
        <relationshipName>Account_Team_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Development Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Account Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client QA Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global CAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managing Director MC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Portfolio Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology Account Lead</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Team Role</label>
    <nameField>
        <displayFormat>Acc Team-{0000000}</displayFormat>
        <label>Account Team Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/classes/AccountTeamRoleBLTest.cls
/**
 * Class Name: AccountTeamRoleBLTest
 * @author: Recuerdo Bregente
 * Date: 10/20/2015
 * Test Class for AccountTeamRoleBL
 */
@isTest(SeeAllData=true)
private class AccountTeamRoleBLTest{

    static List<Account_Team_Role__c> accTeamRoles;

    /*  
    * @Method to prepare the data needed data for testing.
    */    
    static void prepdata() {
 
        List<User> users = TestData.createUsers(2, 'System Administrator');
        database.insert(users);
        
        List<Account> accounts = TestData.createAccounts(1, 'Client');
        for(Account acc : accounts) {
            acc.Client_Account_Lead__c = users[0].id;
            acc.Client_Classification__c = 'Diamond';  
        }
        
        Database.insert(accounts);
        
        accTeamRoles = TestData.createAccountTeamRoles(1, accounts[0].Id);
        for(Account_Team_Role__c accTeamRole : accTeamRoles){
            accTeamRole.Team_Member__c = users[1].Id;
        }
        
        Database.insert(accTeamRoles);
  
    }
    
    /*  
    * @Method to test insertAccountOwner() method of AccountTeamRoleTrigger Class if list parameter is null.
    */  
    static testMethod void testInsertAccountOwnerIfListIsEmpty(){
        accTeamRoles = new List<Account_Team_Role__c>();
        boolean errorExists = false;
        try{
            AccountTeamRoleBL.insertAccountOwner(accTeamRoles);
        }
        catch(Exception e){
            errorExists = true;
        }
        
        System.assertEquals(false, errorExists);
        
    }
    
    /*  
    * @Method to test insertAccountOwner() method of AccountTeamRoleTrigger Class if the List Values are valid.
    */  
    static testMethod void testInsertAccountOwnerIfListValuesValid(){
        
        prepData();
        
        AccountTeamRoleBL.insertAccountOwner(accTeamRoles);
        
        Account_Team_Role__c role = [SELECT Id, status__c, account_owner__c, Account__c FROM Account_Team_Role__c WHERE Id =:accTeamRoles[0].Id];
        Account acc = [SELECT ownerId FROM Account WHERE Id =:role.Account__c];
        
        System.assertEquals('New', role.status__c);
        System.assertEquals(acc.ownerId, role.account_owner__c);
        
    }
    
    /*  
    * @Method to test insertAccountTeam() method of AccountTeamRoleTrigger Class if Map parameter is null.
    */  
    static testMethod void testInsertAccountTeamIfListIsEmpty(){
        Map<Id, Account_Team_Role__c> newMap = new Map<Id, Account_Team_Role__c>{};
        Map<Id, Account_Team_Role__c> oldMap = new Map<Id, Account_Team_Role__c>{};
        boolean errorExists = false;
        try{
            AccountTeamRoleBL.insertAccountTeam(oldMap, newMap);
        }
        catch(Exception e){
            errorExists = true;
        }
        
        System.assertEquals(false, errorExists);
        
    }
    
    /*  
    * @Method to test insertAccountTeam() method of AccountTeamRoleTrigger Class if the Map Values are valid.
    */  
    static testMethod void testInsertAccountTeamIfListValuesValid(){
        Map<Id, Account_Team_Role__c> newMap = new Map<Id, Account_Team_Role__c>{};
        Map<Id, Account_Team_Role__c> oldMap = new Map<Id, Account_Team_Role__c>{};
        prepData();
        
        for(Account_Team_Role__c accTeamRole : accTeamRoles){
            accTeamRole.status__c = 'Approved';
            newMap.put(accTeamRole.Id, accTeamRole);
        }
        
        AccountTeamRoleBL.insertAccountTeam(oldMap, newMap);
        
        List<AccountTeamMember> members = [SELECT Id, TeamMemberRole FROM AccountTeamMember WHERE AccountId =: accTeamRoles[0].Account__c AND
                                            userId =:accTeamRoles[0].Team_Member__c];
        
        System.assertEquals(1, members.size());
        System.assertEquals(accTeamRoles[0].Team_Role__c, members[0].TeamMemberRole);
        
        List<AccountShare> shares = [SELECT Id FROM AccountShare WHERE AccountId =:accTeamRoles[0].Account__c AND UserOrGroupId =:accTeamRoles[0].Team_Member__c];
        System.assertEquals(1, shares.size());
        
    }
}