AFS_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Account_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <description>Reflects Client Portfolio Management (CPM) classification (Diamond, Foundation, Portfolio or Opportunistic).</description>
        <label>Client Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Mega Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diamond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunistic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Captures the source of creation for the record. This will be provide the ability to differentiate if the record was created in Salesforce or is a legacy record.</description>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>STaR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>The entity who will receive the services or products AFS provides (e.g., DC Department of Healthcare Finance). Selecting this Account Record Type will allow you to create a new AFS client to associate with new opportunities, contacts, and/or activities.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

AFS_Dev/src/classes/UpdateAccountBatchTest.cls
/**
 * Class Name: UpdateAccountBatchTest
 * @author:Lhea Valencia    
 * Date: 11/10/2015
 * Test Class for UpdateAccountBatch
 */
@isTest
private class UpdateAccountBatchTest {

    
     // Prepares the data to be used in testing
     static void prepareData(){
         List<User> users = TestData.createUsers(1, 'System Administrator');
         Database.insert(users);
         
         List<Account> accounts = TestData.createAccounts(1, 'Client');
         accounts[0].Client_Account_Lead__c = users[0].id; 
         accounts[0].Client_Classification__c = 'Diamond';
         accounts[0].Source__c = 'STaR';
         Database.insert(accounts);
     }
        
     // Tests the batch class
     static testmethod void testBatch() {
     
        prepareData();
        
        boolean isErrorExists = false;
        
        try{
            system.test.startTest();
            UpdateAccountBatch batch = new UpdateAccountBatch();
            database.executeBatch(batch); 
            system.test.stopTest();
        }
        catch(Exception e){
            isErrorExists = true;
        }
        
        System.assertEquals(false, isErrorExists);
     }
}