AFS_Dev/src/objects/Attribute__c.object
<CustomObject>
    <fields>
        <fullName>AttributePercent__c</fullName>
        <label>Attribute %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AttributeTxt__c</fullName>
        <description>Temporary holder of attribute % value</description>
        <label>AttributeTxt</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_TypeName__c</fullName>
        <description>This will holds the value of Map String Id for each Attribute type record.</description>
        <label>Attribute Type Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Type__c</fullName>
        <label>Attribute Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accenture Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMIN:Digital Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMIN:Digital Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horizontals/Initiatives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IO Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ventures &amp; Acquisitions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy Offerings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attribute_Value__c</fullName>
        <label>Attribute Value</label>
        <picklist>
            <controllingField>Attribute_Type__c</controllingField>
            <picklistValues>
                <fullName>Accenture Cloud Platform-Cloud Managed Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADOBE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agilex - Standalone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agilex - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMAZON WEB SERVICES (AWS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Application Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Application Modernization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Capacity Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Microsoft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Testing Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Workday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APIGEE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APPLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASM - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CALLIDUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CISCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLICKSOFTWARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Agile Infrastructure (IaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Apps and Platform Services (PaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Business Process as a Service (BPaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-SaaS Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D&amp;PS-ENTERPRISE SERVICES FOR DEFENSE-DIGITAL DEFENSE TRANSFORMATION</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>Att-{0000000000}</displayFormat>
        <label>Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/objects/AttributeValidator_Helper__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Parameter__c</fullName>
        <description>This is the parameter that will be taken by the program</description>
        <label>Parameter</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>AttributeValidator Helper</label>
</CustomObject>

AFS_Dev/src/classes/TCAttributeValidator.cls
//Purpose: to validate the opportunities' attributes. will make sure aggregate
//			percentage of each attribute is 100% and that there is at least 1
//			attribute of each type in every opportunity
//Date: 3/28/2016
//Written By: Raymond Garcia

global class TCAttributeValidator implements Database.Batchable<sObject> {
    //purpose: to start the lifecycle of the batch class
    //input: context of the class (context)
    //output: query locator
    global Database.QueryLocator start(Database.BatchableContext context){
        //write real query pull all open opportunities which have all tc items (still only use this opp as testing) util constants
        String oppType = AttributeValidator_Helper__c.getValues('Opportunity Placeholder').Parameter__c;
        string query = Util_Constants.ATTRIBUTE_VALIDATION_BATCHQUERY1 + Util_Constants.ATTRIBUTE_VALIDATION_BATCHQUERY2 + oppType;
        return Database.getQueryLocator(query);
    }
    //purpose: to run the logic of class
    //input: context of the class (context), list of opps from start query
    //output: none
    global void execute(Database.BatchableContext context, List<sObject> lineItems){
        List<Attribute__c> toUpdate  = new List<Attribute__c>();
        Set<Id> opps = new Set<Id>();
        
        //get a set of unique opps from the queried line items
        for(sObject lineItem: lineItems)
            opps.add(((OpportunityLineItem)lineItem).Opportunity.ID);
        
        for(Id currentOpp: opps)
            //validate each opportunity's attributes
            toUpdate.addAll(validateAttributes(currentOpp));
        
        UPSERT toUpdate;
    }
    //purpose: to validate the attributes, make sure aggregate percentage is 100% 
    //			and that there is at least one of each attribute
    //input: current opportunity id
    //output: list of any placeholder atttributes needed to validate opp
    global List<Attribute__c> validateAttributes(id currentOpp){
        String attributeType = AttributeValidator_Helper__c.getValues('Attribute Placeholder').Parameter__c;
        List<Attribute__c> validated = new List<Attribute__c>();
        decimal totalTCPercentage = 0,
                totalSPercentage = 0;
        
        //take a total of all attribute percentages
        //retrieve only TC attributes
        for(Attribute__c currentAttribute: [SELECT id, attribute_value__c, attribute_type__c, attributepercent__c FROM Attribute__c WHERE opportunity_name__c = :currentOpp AND attribute_type__c = :attributeType]){
          //total of tc attributes
          if(currentAttribute.attribute_type__c == Util_Constants.TGP_TC)
              totalTCPercentage += currentAttribute.attributepercent__c;           
          else if(currentAttribute.attribute_type__c == Util_Constants.TGP_Strategy)
              totalSPercentage += currentAttribute.attributepercent__c; 

          else
              System.debug(attributeType + ' is not a handled attribute type');
        }
        
        //check if placeholder is necessary (total is less than 100%), create if needed	
	  if(attributeType == Util_Constants.TGP_TC && totalTCPercentage < 100)
        {
            Attribute__c placeholderAttribute = new Attribute__c();
            placeholderAttribute.AttributePercent__c = 100 - totalTCPercentage;
            placeholderAttribute.AttributeTxt__c = String.valueOf(placeholderAttribute.AttributePercent__c);
            //placeholderAttribute.Attribute_TypeName__c = Util_Constants.TGP_TC;
            placeholderAttribute.Attribute_Type__c = Util_Constants.TGP_TC;
            placeholderAttribute.Attribute_Value__c = 'TC-Placeholder Attribute';
            placeholderAttribute.Opportunity_Name__c = currentOpp;
            validated.add(placeholderAttribute);
        }if(attributeType == Util_Constants.TGP_Strategy && totalSPercentage < 100)
        {
            Attribute__c placeholderAttribute = new Attribute__c();
            placeholderAttribute.AttributePercent__c = 100 - totalSPercentage;
            placeholderAttribute.AttributeTxt__c = String.valueOf(placeholderAttribute.AttributePercent__c);
            //placeholderAttribute.Attribute_TypeName__c = Util_Constants.TGP_TC;
            placeholderAttribute.Attribute_Type__c = Util_Constants.TGP_Strategy;
            placeholderAttribute.Attribute_Value__c = 'S-Placeholder Attribute';
            placeholderAttribute.Opportunity_Name__c = currentOpp;
            validated.add(placeholderAttribute);
                
        }
        
        //return any placeholders created
        return validated;
    }
    //purpose: to end the lifecycle of the batch class
    //input: context of the class (context)
    //output: none
    global void finish(Database.BatchableContext context){
    }

}