AFS_Dev/src/objects/Attribute__c.object
<CustomObject>
    <fields>
        <fullName>AttributePercent__c</fullName>
        <label>Attribute %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AttributeTxt__c</fullName>
        <description>Temporary holder of attribute % value</description>
        <label>AttributeTxt</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_TypeName__c</fullName>
        <description>This will holds the value of Map String Id for each Attribute type record.</description>
        <label>Attribute Type Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Type__c</fullName>
        <label>Attribute Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accenture Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMIN:Digital Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMIN:Digital Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horizontals/Initiatives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IO Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ventures &amp; Acquisitions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy Offerings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attribute_Value__c</fullName>
        <label>Attribute Value</label>
        <picklist>
            <controllingField>Attribute_Type__c</controllingField>
            <picklistValues>
                <fullName>Accenture Cloud Platform-Cloud Managed Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADOBE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agilex - Standalone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agilex - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMAZON WEB SERVICES (AWS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Application Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Application Modernization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Capacity Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Microsoft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Testing Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Workday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APIGEE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APPLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASM - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CALLIDUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CISCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLICKSOFTWARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Agile Infrastructure (IaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Apps and Platform Services (PaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Business Process as a Service (BPaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-SaaS Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D&amp;PS-ENTERPRISE SERVICES FOR DEFENSE-DIGITAL DEFENSE TRANSFORMATION</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>Att-{0000000000}</displayFormat>
        <label>Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/classes/TCAttributePlaceholderBatch.cls
/******************************************************************************************************************************
* Name        - TC_Attribute_Placeholder_Batch 
* Description - This batch class creates a placeholder holder for TC attribute type to store the lacking percentage value.
*        
* Modification Log :
* ---------------------------------------------------------------------------
* Developer                   Date                   Description
* ---------------------------------------------------------------------------
* Recuerdo Bregente           04/04/2016             Initial creation.
* ******************************************************************************************************************************/
global class TCAttributePlaceholderBatch implements Database.Batchable<sObject>{
    
    /* Start method of Interface */
    global Database.QueryLocator start(Database.BatchableContext BC){
        //Retrieves the query from the UTIL_Constants class
        String query = UTIL_Constants.OPEN_OPPORTUNITIES_BATCHQUERY;
        return Database.getQueryLocator(query);
    }
      
    /* Script statements to run on scope */
    global void execute(Database.BatchableContext BC, List<Opportunity> opps){
        //Iterates all through all Open Opportunities and store Ids to a Set Object.
        Set<Id> oppIdSet = new Set<Id>();
        for(Opportunity oppRec : opps){
            oppIdSet.add(oppRec.Id);
        }
        
        Map<Id, Decimal> oppAttributeMap = retrieveOppAttibuteMappings(oppIdSet, Util_Constants.TGP_TC);
        
        List<Attribute__c> toInsert = new List<Attribute__c>();
        
        // Iterates through all Map of Decimal Data and create an Attribute Placeholder record if Map data is less than 100
        for(Id oppId : oppAttributeMap.keySet()){
            if(oppAttributeMap.get(oppId) < Util_Constants.DEFAULT_HUNDRED){
                toInsert.add(new Attribute__c(
                    AttributePercent__c = Util_Constants.DEFAULT_HUNDRED - oppAttributeMap.get(oppId),
                    AttributeTxt__c = (Util_Constants.DEFAULT_HUNDRED - oppAttributeMap.get(oppId)) + UTIL_Constants.DEFAULT_PERCENT_STRING,
                    Attribute_TypeName__c = Util_Constants.TGP_TC,
                    Attribute_Type__c = Util_Constants.TGP_TC,
                    Attribute_Value__c = Util_Constants.TC_PLACEHOLDER,
                    Opportunity_Name__c = oppId
                ));
            }
        }
        
        Database.insert(toInsert);
     
    }
    
    /* Method for retrieving Attribute records of specific Attribute Type and Store it to a Map if Decimal object with OpportunityId as key */
    private Map<Id, Decimal> retrieveOppAttibuteMappings(Set<Id> oppIdSet, String attType){
        // Instantiate a Map of Decimal object.
        Map<Id, Decimal> oppAttributeMap = new Map<Id, Decimal>();
        
        // Retrives all Attribute records of specific Attribute Type, process the data and store it to a Map of Decimal object.
        for(Attribute__c attRec : [SELECT Id, Attribute_Value__c, Attribute_Type__c, AttributePercent__c, Opportunity_Name__c FROM Attribute__c WHERE 
                                Opportunity_Name__c IN :oppIdSet AND Attribute_Type__c = :attType]){
            if(!oppAttributeMap.containsKey(attRec.opportunity_name__c)){
                oppAttributeMap.put(attRec.opportunity_name__c, Util_Constants.DEFAULT_ZERO_DECIMAL);
            }
            
            oppAttributeMap.put(attRec.opportunity_name__c, oppAttributeMap.get(attRec.opportunity_name__c) + attRec.AttributePercent__c);
        }
        
        return oppAttributeMap;
    }
    
    /* Any post-processing will be run here */
    global void finish(Database.BatchableContext BC){
        // Logic to be Executed at finish
    }
}