AFS_Dev/src/objects/Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>Att-{0000000000}</displayFormat>
        <label>Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/classes/RedirectAttributeExt.cls
/**
 *  @Author Pablito Abalos
 *  @name AddAttributeExt
 *  @CreateDate <Date>
 *  @Description <purpose of the class>
 *  @Version <1.0>
 *  @reference <Referenced program names>
 */
public class RedirectAttributeExt {

    private final Attribute__c attribute;
    private final Id opportunityId;
    private List<User> userList = new List<User>();
   /**
   * This is Constructor which assign the value of attribute and opportunity id upon load.
   * @param ApexPages.StandardController.
   * @return none
   */
    public RedirectAttributeExt(ApexPages.StandardController stdController) {
        this.attribute = (Attribute__c)stdController.getRecord();
        this.opportunityId = [SELECT Opportunity_Name__c from Attribute__c WHERE Id = :attribute.Id][0].Opportunity_Name__c;
        this.userList = [select user.id, user.Email, user.FirstName, user.LastName, user.profile.name, user.Username, user.IsActive FROM user, user.profile where user.id =: UserInfo.getUserId() Limit 1];
    }
    
   /**
   * This is return addAttribute page
   * @param None
   * @return PageReference
   */
    public PageReference redirect() {
 
        PageReference redirectPage = Page.AddAttribute;
        redirectPage.getParameters().put(UTIL_Constants.id, opportunityId );
        redirectPage.setRedirect(true);
        return redirectPage;
    }

}