AFS_Dev/src/objects/Attribute__c.object
<CustomObject>
    <fields>
        <fullName>AttributePercent__c</fullName>
        <label>Attribute %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Attribute_Type__c</fullName>
        <label>Attribute Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accenture Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMIN:Digital Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMIN:Digital Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horizontals/Initiatives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IO Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ventures &amp; Acquisitions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy Offerings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attribute_Value__c</fullName>
        <label>Attribute Value</label>
        <picklist>
            <controllingField>Attribute_Type__c</controllingField>
            <picklistValues>
                <fullName>Accenture Cloud Platform-Cloud Managed Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADOBE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agilex - Standalone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agilex - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMAZON WEB SERVICES (AWS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Application Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Application Modernization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Capacity Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Microsoft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Testing Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Workday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APIGEE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APPLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASM - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CALLIDUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CISCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLICKSOFTWARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Agile Infrastructure (IaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Apps and Platform Services (PaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Business Process as a Service (BPaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-SaaS Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D&amp;PS-ENTERPRISE SERVICES FOR DEFENSE-DIGITAL DEFENSE TRANSFORMATION</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>Att-{0000000000}</displayFormat>
        <label>Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Custom_Error_Messages__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <label>Custom Error Messages</label>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status_Stage_Requested__c</fullName>
        <inlineHelpText>Use this field to request advancement to a subsequent stage when all required fields are complete.
Please note: there may be additional fields on the Related Lists (e.g., Financial Details, Attributes, Opp Team Roles) that are required for advancement.</inlineHelpText>
        <label>Status/Stage Requested</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>TCR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Service Group</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

AFS_Dev/src/classes/AttributeBL.cls
/**
   @Author Pablito M. Abalos Jr
   @name AttributeTrigger
   @CreateDate 2/17/2015
   @Description This class validate attribute records on before update event.
   @Version <1.0>
   @reference 
 */
public class AttributeBL{
    public static List<Attribute__c> attrib = new List<Attribute__c>();
    public static List<Opportunitylineitem> oppLineItem = new List<Opportunitylineitem>();
    
    
    /**
    *  To validate Attribute record in opportunity level 
    *  @name validateAttribute
    *  @param Opportunity[] Old, New and Opportunity Sobject
    *  @return void
    *  @throws exception
    */
    public static String validateAttribute(Opportunity[] oldOpportunities , Opportunity[] newOpportunities){
        Map<String, Custom_Error_Messages__c> message = Custom_Error_Messages__c.getAll();
        Set<ID> oppsIDs = new Set<ID>();
        String attribErrorMessage = UTIL_Constants.STRING_EMPTY;
        
        for (Integer i = 0; i < newOpportunities.size(); i++) {
            System.debug('Value of: oldOpportunities: ' + oldOpportunities[i].Status_Stage_Requested__c + ' - ' +oldOpportunities[i].id+ ' newOpportunities: '+ newOpportunities[i].Status_Stage_Requested__c + ' - ' +newOpportunities[i].id);
            if (oldOpportunities[i].Status_Stage_Requested__c != newOpportunities[i].Status_Stage_Requested__c){

                Integer mC_OFFERING = 0, mC_OFFERINGTOTAL = 0, 
                        tGP_SI = 0 ,tGP_SITOTAL = 0, 
                        tGP_AO = 0,tGP_AOTOTAL =0, 
                        tGP_IO = 0,tGP_IOTOTAL = 0, 
                        tGP_TC = 0,tGP_TCTOTAL = 0;
                          
                Integer mC_OFFER = 0, sI = 0, aO = 0, iO = 0, tC = 0;
                
                
                
                for(Opportunity OppId : newOpportunities){
                    oppsIDs.add(OppId.id);
                }
                
                attrib = [SELECT id, Name, Attribute_Type__c, Attribute_Value__c, AttributePercent__c, Opportunity_Name__c FROM Attribute__c WHERE Opportunity_Name__c in : oppsIDs ORDER BY Attribute_Type__c, Attribute_Value__c ASC LIMIT 50000];
                oppLineItem = [SELECT Id, OpportunityId, Type__c, Revenue__c FROM OpportunityLineItem WHERE OpportunityId in : oppsIDs LIMIT 50000];
            
                for(Opportunity Opp : newOpportunities){
                    
                    

                    String [] typeNames = UTIL_Constants.STAGEREQ_2A_3.split(UTIL_Constants.STRING_COMMA);
                    
                    for(String typeName : typeNames){
                    
                        if (opp.Status_Stage_Requested__c ==typeName){
                            
                            for(Opportunitylineitem oppLineItems : oppLineItem){
                                if(oppLineItems.OpportunityId.equals(Opp.id)){
                                    if(oppLineItems.Type__c != null){
                                        if(oppLineItems.Type__c.equals(UTIL_Constants.PRODUCT_MC) && oppLineItems.Revenue__c != null){
                                            ++mC_OFFER;
                                        }
                                        if(oppLineItems.Type__c.equals(UTIL_Constants.PRODUCT_SI) && oppLineItems.Revenue__c != null){
                                            ++sI;
                                        }
                                        if(oppLineItems.Type__c.equals(UTIL_Constants.PRODUCT_AO) && oppLineItems.Revenue__c != null){
                                            ++aO;
                                        }
                                        if(oppLineItems.Type__c.equals(UTIL_Constants.PRODUCT_IO) && oppLineItems.Revenue__c != null){
                                            ++iO;
                                        }
                                        if(oppLineItems.Type__c.equals(UTIL_Constants.PRODUCT_TC) && oppLineItems.Revenue__c != null){
                                            ++tC;
                                        }
                                    }
                                }
                            }
                            if(!attrib.isEmpty()){
                                for(Attribute__c attr : attrib){
                                    if(attr.Opportunity_Name__c.equals(Opp.Id)){
                                                                       
                                        //MC Offerings validation
                                        if(attr.Attribute_Type__c.equals(UTIL_Constants.MC_OFERRING))
                                        {   
                                            mC_OFFERINGTOTAL += Integer.valueOf(attr.AttributePercent__c);                        
                                            ++mC_OFFERING;
                                        }
                                        //TGP SI validation
                                        if(attr.Attribute_Type__c.equals(UTIL_Constants.TGP_SI))
                                        {   
                                            tGP_SITOTAL += Integer.valueOf(attr.AttributePercent__c);                        
                                            ++tGP_SI;
                                        }
                                        //TGP AO valdiation
                                        if(attr.Attribute_Type__c.equals(UTIL_Constants.TGP_AO))
                                        {   
                                            tGP_AOTOTAL += Integer.valueOf(attr.AttributePercent__c);                        
                                            ++tGP_AO;
                                        }
                                        //TGP IO valdiation
                                        if(attr.Attribute_Type__c.equals(UTIL_Constants.TGP_IO))
                                         {   
                                            tGP_IOTOTAL += Integer.valueOf(attr.AttributePercent__c);                        
                                            ++tGP_IO;
                                        }
                                        //TGP TC validation
                                        if(attr.Attribute_Type__c.equals(UTIL_Constants.TGP_TC))
                                        {   
                                            tGP_TCTOTAL += Integer.valueOf(attr.AttributePercent__c);                        
                                            ++tGP_TC;
                                        }
                                    }
                                }
                            }
                            
                            //MC Offerings validation
                            if(mC_OFFERING==0  && mC_OFFER != 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE +message.get(UTIL_Constants.ERROR_MSG_ATT_007).Error_Message__c + UTIL_Constants.STRING_BREAK;
                            }
                            
                            if(mC_OFFERINGTOTAL != 0 && mC_OFFERINGTOTAL!=100 && mC_OFFER != 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE + message.get(UTIL_Constants.ERROR_MSG_ATT_022).Error_Message__c + UTIL_Constants.STRING_BREAK;
                            }
                                                    
                            if(mC_OFFERINGTOTAL != 0 && mC_OFFER == 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE +message.get(UTIL_Constants.ERROR_MSG_ATT_017).Error_Message__c + UTIL_Constants.STRING_BREAK;
                            }
                            
                            //TGP SI validation
                            if(tGP_SITOTAL==0  && sI != 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE +message.get(UTIL_Constants.ERROR_MSG_ATT_009).Error_Message__c + UTIL_Constants.STRING_BREAK;
                            }
                            
                            if(tGP_SITOTAL != 0 && tGP_SITOTAL != 100 && sI != 0 ){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE +message.get(UTIL_Constants.ERROR_MSG_ATT_023).Error_Message__c + UTIL_Constants.STRING_BREAK; 
                            }
                            
                            if(tGP_SITOTAL != 0 && sI == 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE + message.get(UTIL_Constants.ERROR_MSG_ATT_018).Error_Message__c + UTIL_Constants.STRING_BREAK;
                            }
                            
                            //TGP AO validation
                            if(tGP_AOTOTAL==0  && aO != 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE + message.get(UTIL_Constants.ERROR_MSG_ATT_011).Error_Message__c + UTIL_Constants.STRING_BREAK; 
                            }
                            
                            if(tGP_AOTOTAL != 0 && tGP_AOTOTAL != 100 && aO != 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE + message.get(UTIL_Constants.ERROR_MSG_ATT_024).Error_Message__c+ UTIL_Constants.STRING_BREAK; 
                            }
                            
                            if(tGP_AOTOTAL != 0 && aO == 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE + message.get(UTIL_Constants.ERROR_MSG_ATT_019).Error_Message__c + UTIL_Constants.STRING_BREAK;
                            }
                            
                            //TGP IO validation
                            if(tGP_IOTOTAL==0  && iO != 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE +message.get(UTIL_Constants.ERROR_MSG_ATT_013).Error_Message__c+ UTIL_Constants.STRING_BREAK;
                            }
                            
                            if(tGP_IOTOTAL != 0 && tGP_IOTOTAL != 100 && iO != 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE +message.get(UTIL_Constants.ERROR_MSG_ATT_025).Error_Message__c + UTIL_Constants.STRING_BREAK;
                            }
                            
                            if(tGP_IOTOTAL != 0 && iO == 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE + message.get(UTIL_Constants.ERROR_MSG_ATT_020).Error_Message__c + UTIL_Constants.STRING_BREAK;
                            }
                            
                            //TGP TC validation
                            if(tGP_TCTOTAL==0  && tC != 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE +message.get(UTIL_Constants.ERROR_MSG_ATT_015).Error_Message__c + UTIL_Constants.STRING_BREAK;  
                            }
                            
                            if(tGP_TCTOTAL != 0 && tGP_TCTOTAL != 100 && tC != 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE + message.get(UTIL_Constants.ERROR_MSG_ATT_026).Error_Message__c + UTIL_Constants.STRING_BREAK; 
                            }
                            
                            if(tGP_TCTOTAL != 0 && tC == 0){
                                attribErrorMessage += UTIL_Constants.STRING_SPAN_SPACE + message.get(UTIL_Constants.ERROR_MSG_ATT_021).Error_Message__c+ UTIL_Constants.STRING_BREAK; 
                            }
                            
                            /*if(!attribErrorMessage.equals(UTIL_Constants.STRING_EMPTY) || attribErrorMessage.length() != 0)
                            {
                                Opps.AddError(attribErrorMessage.substring(0, attribErrorMessage.length() - 1));
                            }*/
                            
                        }
                    }
                }
            }
        }
        return attribErrorMessage; 
    }
}