AFS_Dev/src/objects/Attribute__c.object
<CustomObject>
    <fields>
        <fullName>AttributePercent__c</fullName>
        <label>Attribute %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AttributeTxt__c</fullName>
        <description>Temporary holder of attribute % value</description>
        <label>AttributeTxt</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_TypeName__c</fullName>
        <description>This will holds the value of Map String Id for each Attribute type record.</description>
        <label>Attribute Type Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Type__c</fullName>
        <label>Attribute Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accenture Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMIN:Digital Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMIN:Digital Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horizontals/Initiatives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IO Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ventures &amp; Acquisitions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy Offerings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attribute_Value__c</fullName>
        <label>Attribute Value</label>
        <picklist>
            <controllingField>Attribute_Type__c</controllingField>
            <picklistValues>
                <fullName>Accenture Cloud Platform-Cloud Managed Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADOBE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agilex - Standalone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agilex - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMAZON WEB SERVICES (AWS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Application Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Application Modernization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Capacity Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Microsoft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Testing Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Workday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APIGEE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APPLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASM - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CALLIDUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CISCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLICKSOFTWARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Agile Infrastructure (IaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Apps and Platform Services (PaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Business Process as a Service (BPaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-SaaS Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D&amp;PS-ENTERPRISE SERVICES FOR DEFENSE-DIGITAL DEFENSE TRANSFORMATION</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>Att-{0000000000}</displayFormat>
        <label>Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <formula>IF(AND(Consulting_Total_Revenue__c&lt;&gt;0, Outsourcing_Total_Revenue__c&lt;&gt;0),&quot;C/O&quot;,
IF(AND(Consulting_Total_Revenue__c=0, Outsourcing_Total_Revenue__c&gt;0), &quot;O&quot;, 
IF(AND(Outsourcing_Total_Revenue__c=0,Consulting_Total_Revenue__c&gt;0), &quot;C&quot;,
IF(AND(Consulting_Total_Revenue__c=0, Outsourcing_Total_Revenue__c=0),&quot;&quot;,&quot;&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type of Work</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Cost_Components_N_A__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cost Components N/A</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HW_SW_Costs__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Does not apply to BPO
Fields required to enter stage 2A and beyond</inlineHelpText>
        <label>HW/SW Costs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Cost_Components__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This applies to Consulting ToW ONLY and includes costs such as: Airfare, Hotel, Industrial Funding Fee, Contract Access Fee, etc.
Fields required to enter stage 2A and beyond</inlineHelpText>
        <label>Other Cost Components</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>TCR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subcontractor_Expenses__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This applies to Consulting ToW ONLY
Fields required to enter stage 2A and beyond</inlineHelpText>
        <label>Subcontractor Expenses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_OI_Temp_Calc__c</fullName>
        <label>Target OI Temp Calc</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_OI__c</fullName>
        <label>Target OI%</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Costs__c</fullName>
        <inlineHelpText>This includes both direct &amp; indirect costs</inlineHelpText>
        <label>Total Costs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Service Group</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <label>Type of Work</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

AFS_Dev/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Target_OI__c</fullName>
        <label>Target OI%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Service Group</label>
        <picklist>
            <picklistValues>
                <fullName>01 - AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02 - BPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03 - IO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 - MC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 - SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 - TC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 - Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 - IC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <label>Type of Work</label>
        <picklist>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outsourcing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AFS_Dev/src/objects/ServiceGroupConversion__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Use to manage Percentage Split of Service Group Conversion on MC, TC, and SI</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Split_Percentage__c</fullName>
        <label>Split Percentage</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Service Group Conversion</label>
</CustomObject>

AFS_Dev/src/classes/TCServiceGroupConversionBatch.cls
global class TCServiceGroupConversionBatch implements Database.Batchable<sObject>{
    
    // Start Method
    global Database.QueryLocator start(Database.BatchableContext BC){
         String query = UTIL_Constants.TC_SG_CONVERSION_BATCHQUERY;
        return Database.getQueryLocator(query);
    }
      
    // Execute Logic
    global void execute(Database.BatchableContext BC, List<OpportunityLineItem> oppLineItemList){
        ServiceGroupConversion__c tcStrategy = ServiceGroupConversion__c.getValues('TC to Strategy');
        ServiceGroupConversion__c tcIC = ServiceGroupConversion__c.getValues('TC to IC');
        
        Decimal strategyPercentage = 0.50;
        Decimal icPercentage = 0.50;
        if(tcStrategy.Active__c == true){
            strategyPercentage = tcStrategy.Split_Percentage__c/100;
        }
        
        if(tcIC.Active__c == true){
            icPercentage = tcIC.Split_Percentage__c/100;
        }
        
        Set<Id> oppIds = insertLineItemSplit(oppLineItemList, strategyPercentage, icPercentage);
        insertAttributeSplit(oppIds, strategyPercentage, icPercentage);
     
    }
    
    private Set<Id> insertLineItemSplit(List<OpportunityLineItem> oppLineItemList, Decimal strategyPercentage, Decimal icPercentage){
        List<OpportunityLineItem> toInsert = new List<OpportunityLineItem>();
        OpportunityLineItem icOppLineItem = new OpportunityLineItem();
        OpportunityLineItem strategyOppLineItem = new OpportunityLineItem();
        
        Map<String, PricebookEntry> pbNameMap = new Map<String, PricebookEntry>();
        for(PricebookEntry pricebookEntry : [SELECT Id, Product2.Name, Product2.Type__c FROM PricebookEntry Where Product2.Name like '%IC%' OR Product2.Name like '%Strategy%']){
            pbNameMap.put(pricebookEntry.Product2.Name, pricebookEntry);
        }
        
        Set<Id> oppIds = new Set<Id>();
        for(OpportunityLineItem oppLineItem: oppLineItemList){
            oppIds.add(oppLineItem.Opportunity.Id);
            
            strategyOppLineItem = new OpportunityLineItem();
            
            strategyOppLineItem.Revenue__c = oppLineItem.Revenue__c * strategyPercentage;
            strategyOppLineItem.Total_Costs__c = oppLineItem.Total_Costs__c * strategyPercentage;
            strategyOppLineItem.HW_SW_Costs__c = oppLineItem.HW_SW_Costs__c * strategyPercentage;
            strategyOppLineItem.Other_Cost_Components__c = oppLineItem.Other_Cost_Components__c * strategyPercentage;
            strategyOppLineItem.Subcontractor_Expenses__c = oppLineItem.Subcontractor_Expenses__c * strategyPercentage;
            strategyOppLineItem.OpportunityId = oppLineItem.OpportunityId;
            strategyOppLineItem.Quantity = 1;
            strategyOppLineItem.Cost_Components_N_A__c = oppLineItem.Cost_Components_N_A__c;
            strategyOppLineItem.Target_OI__c = oppLineItem.Target_OI__c;
            strategyOppLineItem.Target_OI_Temp_Calc__c = oppLineItem.Target_OI_Temp_Calc__c;
            strategyOppLineItem.Type_of_Work__c = oppLineItem.Type_of_Work__c;
            
        
            icOppLineItem = new OpportunityLineItem();
            
            icOppLineItem.Revenue__c = oppLineItem.Revenue__c * icPercentage;
            icOppLineItem.Total_Costs__c = oppLineItem.Total_Costs__c * icPercentage;
            icOppLineItem.HW_SW_Costs__c = oppLineItem.HW_SW_Costs__c * icPercentage;
            icOppLineItem.Other_Cost_Components__c = oppLineItem.Other_Cost_Components__c * icPercentage;
            icOppLineItem.Subcontractor_Expenses__c = oppLineItem.Subcontractor_Expenses__c * icPercentage;
            icOppLineItem.OpportunityId = oppLineItem.OpportunityId;
            icOppLineItem.Quantity = 1;
            icOppLineItem.Cost_Components_N_A__c = oppLineItem.Cost_Components_N_A__c;
            icOppLineItem.Target_OI__c = oppLineItem.Target_OI__c;
            icOppLineItem.Target_OI_Temp_Calc__c = oppLineItem.Target_OI_Temp_Calc__c;
            icOppLineItem.Type_of_Work__c = oppLineItem.Type_of_Work__c;
            
            if(oppLineItem.Product2.Name.equals('TC - CostPlus')){
                strategyOppLineItem.PricebookEntryId = pbNameMap.get('Strategy - CostPlus').Id;
                strategyOppLineItem.Type__c = pbNameMap.get('Strategy - CostPlus').Product2.Type__c;
                
                icOppLineItem.PricebookEntryId = pbNameMap.get('IC - CostPlus').Id;
                icOppLineItem.Type__c = pbNameMap.get('IC - CostPlus').Product2.Type__c;
            }
            else if(oppLineItem.Product2.Name.equals('TC - Fixed Price')){
                strategyOppLineItem.PricebookEntryId = pbNameMap.get('Strategy - Fixed Price').Id;
                strategyOppLineItem.Type__c = pbNameMap.get('Strategy - Fixed Price').Product2.Type__c;
                
                icOppLineItem.PricebookEntryId = pbNameMap.get('IC - Fixed Price').Id;
                icOppLineItem.Type__c = pbNameMap.get('IC - Fixed Price').Product2.Type__c;
            }
            else{
                strategyOppLineItem.PricebookEntryId = pbNameMap.get('Strategy - Time & Materials').Id;
                strategyOppLineItem.Type__c = pbNameMap.get('Strategy - Time & Materials').Product2.Type__c;
                
                icOppLineItem.PricebookEntryId = pbNameMap.get('IC - Time & Materials').Id;
                icOppLineItem.Type__c = pbNameMap.get('IC - Time & Materials').Product2.Type__c;
            }
            
            toInsert.add(strategyOppLineItem);
            toInsert.add(icOppLineItem);
            
        }
        
        Database.insert(toInsert);
        Database.delete(oppLineItemList);
        
        return oppIds;
    }
    
    private void insertAttributeSplit(Set<Id> oppIds, Decimal strategyPercentage, Decimal icPercentage){
        
        List<Attribute__c> toUpdateAndInsert = new List<Attribute__c>();
        for(Attribute__c attribute : [SELECT AttributePercent__c, Attribute_Type__c, Attribute_Value__c, Opportunity_Name__c FROM Attribute__c WHERE
                                        Attribute_Type__c = 'TC Offerings' AND Opportunity_Name__c IN :oppIds]){
            toUpdateAndInsert.add(new Attribute__c(
                Attribute_Type__c = 'S Offerings',
                Attribute_Value__c = attribute.Attribute_Value__c.replace('TC-','S-'),
                AttributePercent__c = attribute.AttributePercent__c * strategyPercentage,
                AttributeTxt__c = attribute.AttributePercent__c * strategyPercentage + '%',
                Attribute_TypeName__c = 'Strategy Offerings',
                Opportunity_Name__c = attribute.Opportunity_Name__c));
                
             attribute.Attribute_Type__c = 'IC Offerings';
             attribute.Attribute_Value__c = attribute.Attribute_Value__c.replace('TC-','IC-');
             attribute.AttributePercent__c = attribute.AttributePercent__c * icPercentage;
             attribute.AttributeTxt__c = attribute.AttributePercent__c + '%';
             attribute.Attribute_TypeName__c = attribute.Attribute_Type__c;
             
             toUpdateAndInsert.add(attribute);
        }                                
             
             
        Database.upsert(toUpdateAndInsert);                            
    }
     
    global void finish(Database.BatchableContext BC){
        // Logic to be Executed at finish
    }
}