AFS_Dev/src/objects/Custom_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Line_Item_Id__c</fullName>
        <description>Id of the parent Opportunity Line Item.</description>
        <label>Opportunity Line Item Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Custom Schedule</label>
    <nameField>
        <label>Custom Schedules Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Reporting_Status__c</fullName>
        <inlineHelpText>Field updated based on the stage of the opportunity through workflow. Reporting Status is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status</label>
        <picklist>
            <controllingField>Approved_Status_Stage__c</controllingField>
            <picklistValues>
                <fullName>Lost</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
                <color>#A845DC</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Summary_Customer__c</fullName>
        <formula>Account.Parent.Name</formula>
        <label>Summary Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <formula>IF(AND(Consulting_Total_Revenue__c&lt;&gt;0, Outsourcing_Total_Revenue__c&lt;&gt;0),&quot;C/O&quot;,
IF(AND(Consulting_Total_Revenue__c=0, Outsourcing_Total_Revenue__c&gt;0), &quot;O&quot;, 
IF(AND(Outsourcing_Total_Revenue__c=0,Consulting_Total_Revenue__c&gt;0), &quot;C&quot;,
IF(AND(Consulting_Total_Revenue__c=0, Outsourcing_Total_Revenue__c=0),&quot;&quot;,&quot;&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type of Work</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Consulting_End_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Consulting&apos;, Opportunity.Consulting_End__c,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Consulting End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Consulting_Start_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Consulting&apos;,Opportunity.Consulting_Start__c,null)</formula>
        <label>Consulting Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_End_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Outsourcing&apos;,Opportunity.Outsourcing_End__c,null)</formula>
        <label>Outsourcing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_Start_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Outsourcing&apos;,Opportunity.Outsourcing_Start__c,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outsourcing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>TCR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <label>Type of Work</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

AFS_Dev/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <label>Type of Work</label>
        <picklist>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outsourcing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AFS_Dev/src/classes/OpenOpportunityScheduleExt.cls
public with sharing class OpenOpportunityScheduleExt {

    public List<OpportunitySchedule> opportunitySchedules {get; set;}
    public String productName {get; set;}
    public String opportunityName {get; set;}
    public String accountName {get; set;}
    public String accountParentName {get; set;}
    
    public Class OpportunitySchedule{
        public boolean isSelected {get; set;}
        public Opportunity oppRecord {get; set;}
        public List<OpportunityLineItem> oppLineItemsWrap {get; set;}
        
        
    }
    
    /**
    * Constructor for openOpportunityScheduleExt Class.
    * @param ApexPages.StandardController stdcontroller.
    */
    public OpenOpportunityScheduleExt() {
        productName = '';
        opportunityName = '';
        accountName = '';
        accountParentName = '';
        processData(Database.query(getGeneralQuery()));
    }
    
    private void processData(List<Opportunity> oppList){
        opportunitySchedules = new List<OpportunitySchedule>();
        Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>();
        
        for(Opportunity oppRecord : oppList){
            opportunityMap.put(oppRecord.Id, oppRecord);
        }
            /**new Map<Id, Opportunity>([SELECT Id, Name,
            (SELECT Id, Name, Product2.Name, TotalPrice, Type_of_Work__c, Revenue__c, Outsourcing_Start_Date__c, Outsourcing_End_Date__c, Consulting_Start_Date__c, Consulting_End_Date__c, VF_Checkbox__c, OpportunityId
                FROM OpportunityLineItems WHERE Type_of_Work__c =: UTIL_Constants.PRODUCT_TYPE_OF_WORK_OUTSOURCING OR Type_of_Work__c =: UTIL_Constants.PRODUCT_TYPE_OF_WORK_CONSULTING LIMIT 50000)
            FROM Opportunity WHERE Reporting_Status__c NOT IN ('Closed', 'Won', 'Lost') AND Type_of_Work__c IN ('C', 'O', 'C/O') LIMIT 50000]);**/
        
        for(Id oppId : opportunityMap.keySet()){
            if(!opportunityMap.get(oppId).OpportunityLineItems.isEmpty()){
                opportunitySchedules.add(new OpportunitySchedule());
                opportunitySchedules[opportunitySchedules.size()-1].isSelected = true;
                opportunitySchedules[opportunitySchedules.size()-1].oppRecord = opportunityMap.get(oppId);
                opportunitySchedules[opportunitySchedules.size()-1].oppLineItemsWrap = opportunityMap.get(oppId).OpportunityLineItems;
            }
            
        }
        
        if(opportunitySchedules.isEmpty()){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'No Match Data Found'));        
        }
        
        //filterOppLineItemWithSchedule();
    }
    
    private String getGeneralQuery(){
        List<String> productTypes = new List<String>();
        productTypes.add('\''+UTIL_Constants.PRODUCT_TYPE_OF_WORK_OUTSOURCING+'\'');
        productTypes.add('\''+UTIL_Constants.PRODUCT_TYPE_OF_WORK_CONSULTING+'\'');
        
        String lineItemQuery = 'SELECT Id, Name, Product2.Name, TotalPrice, Type_of_Work__c, Revenue__c, Outsourcing_Start_Date__c, Outsourcing_End_Date__c, Consulting_Start_Date__c, Consulting_End_Date__c,' +
                               ' VF_Checkbox__c, OpportunityId FROM OpportunityLineItems WHERE' +
                               ' Product2.Name LIKE \'%'+String.escapeSingleQuotes(productName)+'%\''+
                               ' AND Type_of_Work__c IN' + productTypes +
                               ' LIMIT 50000';
        
        String queryString = 'SELECT Id, Name, (' + lineItemQuery + ') FROM Opportunity WHERE Reporting_Status__c NOT IN (\'Closed\', \'Won\', \'Lost\') AND Type_of_Work__c IN (\'C\', \'O\', \'C/O\')';
                queryString += ' AND Name LIKE \'%'+String.escapeSingleQuotes(opportunityName)+'%\'';
                queryString += ' AND Account.Name LIKE \'%'+String.escapeSingleQuotes(accountName)+'%\'';
                if(!String.isEmpty(accountParentName)){
                    queryString += ' AND Summary_Customer__c LIKE \'%'+String.escapeSingleQuotes(accountParentName)+'%\'';
                }
                
                queryString += ' LIMIT 50000';
        
        System.debug(LoggingLevel.DEBUG,'----------------QueryString: '+queryString);
        return queryString;
    }
    
    private void filterOppLineItemWithSchedule(){
        Set<Id> oppIds = new Set<Id>();
        
        for(OpportunitySchedule oppSchedObj: opportunitySchedules){
            for(OpportunityLineItem oppLineItem : oppSchedObj.oppLineItemsWrap){
                oppIds.add(oppLineItem.Id);
            }
        }
        
        Map<Id, AggregateResult> oppToRemove = new Map<Id, AggregateResult>();
        
        for(AggregateResult agg : [SELECT Id, COUNT(Opportunity_Line_Item_Id__c) lineCount FROM Custom_Schedule__c WHERE Opportunity_Line_Item_Id__c IN :oppIds GROUP BY Id]){
            if(Integer.valueOf(agg.get('lineCount')) == 0){
                oppToRemove.put(String.valueOf(agg.get('Id')), agg);
            }
        }
        
        for(OpportunitySchedule oppSchedObj: opportunitySchedules){
            for(Integer i = oppSchedObj.oppLineItemsWrap.size()-1; i >= 0; i--){
                if(!oppToRemove.containsKey(oppSchedObj.oppLineItemsWrap[i].Id)){
                    oppSchedObj.oppLineItemsWrap.remove(i);
                }
            }
            
        }
        
    }
    
    public pageReference search(){
        /**
        for(OpportunitySchedule oppSchedObj: opportunitySchedules){
            if(oppSchedObj.oppRecord.Name.containsIgnoreCase(opportunityName)){
                oppSchedObj.isSelected = true;
                
            }
            else{
                oppSchedObj.isSelected = false;
                
              
            }
        }*/
        
        processData(Database.query(getGeneralQuery()));
        
        return null;
    }
    
    public pageReference customSchedules(){
        pageReference page = null;
        boolean atleastOneSelected = false;
        List<Id> itemIds = new List<Id>();
        for(OpportunitySchedule oppSchedObj: opportunitySchedules){
            for(OpportunityLineItem oppLineItem : oppSchedObj.oppLineItemsWrap){
                if(oppLineItem.VF_Checkbox__c){
                    itemIds.add(oppLineItem.Id);
                    atleastOneSelected = true;
                }
            }
        }
        String jsonString = JSON.serialize(itemIds);
        if(atleastOneSelected){
            page = new pageReference('https://smartafs--dev--c.cs10.visual.force.com/apex/opportunityRevenuePage?lineItems='+jsonString);
            page.setRedirect(true);
            
        }
        else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Please select an Product Item'));
        }
            
        return page;
    }
    
    public pageReference selectAll(){
        for(OpportunitySchedule oppSchedObj: opportunitySchedules){
            for(OpportunityLineItem oppLineItem : oppSchedObj.oppLineItemsWrap){
                if(!oppLineItem.VF_Checkbox__c){
                    oppLineItem.VF_Checkbox__c = true;
                }
            }
        }
        
        return null;
    }
    
    public pageReference unSelectAll(){
        
        for(OpportunitySchedule oppSchedObj: opportunitySchedules){
            for(OpportunityLineItem oppLineItem : oppSchedObj.oppLineItemsWrap){
                if(oppLineItem.VF_Checkbox__c){
                    oppLineItem.VF_Checkbox__c = false;
                }
            }
        }
        return null;
    }
    
    public pageReference cancelOrReturn(){
        List<OpportunityLineItem> toUpdate = new List<OpportunityLineItem>();
        for(OpportunitySchedule oppSchedObj: opportunitySchedules){
            for(OpportunityLineItem oppLineItem : oppSchedObj.oppLineItemsWrap){
                if(oppLineItem.VF_Checkbox__c){
                    oppLineItem.VF_Checkbox__c = false;
                    toUpdate.add(oppLineItem);
                }
            }
        }
        
        if(!toUpdate.isEmpty()){
            Database.update(toUpdate);
        }
        
        PageReference page = new pageReference('https://smartafs--dev.cs10.my.salesforce.com/006?fcf=00BJ0000000yl3y&rolodexIndex=-1&page=1');
        page.setRedirect(true);
        return page;
    }
}