AFS_Dev/src/objects/Custom_Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OpportunityLineItemId__c</fullName>
        <label>Opp Line Item Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ScheduleDate__c</fullName>
        <label>Schedule Date</label>
        <type>Date</type>
    </fields>
    <label>Custom Schedule</label>
    <nameField>
        <displayFormat>Sched-{0000000000}</displayFormat>
        <label>Schedules Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <formula>IF(AND(Consulting_Total_Revenue__c&lt;&gt;0, Outsourcing_Total_Revenue__c&lt;&gt;0),&quot;C/O&quot;,
IF(AND(Consulting_Total_Revenue__c=0, Outsourcing_Total_Revenue__c&gt;0), &quot;O&quot;, 
IF(AND(Outsourcing_Total_Revenue__c=0,Consulting_Total_Revenue__c&gt;0), &quot;C&quot;,
IF(AND(Consulting_Total_Revenue__c=0, Outsourcing_Total_Revenue__c=0),&quot;&quot;,&quot;&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type of Work</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Consulting_End_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Consulting&apos;, Opportunity.Consulting_End__c,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Consulting End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Consulting_Start_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Consulting&apos;,Opportunity.Consulting_Start__c,null)</formula>
        <label>Consulting Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_End_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Outsourcing&apos;,Opportunity.Outsourcing_End__c,null)</formula>
        <label>Outsourcing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_Start_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Outsourcing&apos;,Opportunity.Outsourcing_Start__c,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outsourcing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>TCR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <label>Type of Work</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

AFS_Dev/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <label>Type of Work</label>
        <picklist>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outsourcing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AFS_Dev/src/classes/DisplayScheduleRecordsExt.cls
public with sharing class DisplayScheduleRecordsExt {
public List<OpportunityLineItem> oppLineItems {get; set;}
    public List<Custom_Schedules__c> customSchedules {get; set;}
    public boolean hasNoSchedules {get; set;}
    
   /**
   * Constructor for DisplayScheduleRecordsExt Class.
   * @param ApexPages.StandardController stdcontroller.
   * @return void
   */
    public DisplayScheduleRecordsExt (ApexPages.StandardController stdcontroller) {
        customSchedules = new List<Custom_Schedules__c>();
        String oppLineItemId = ApexPages.currentPage().getParameters().get('oppId');
        
        oppLineItems =
            [SELECT Id, Opportunity.Name, Product2.Name, Type_of_Work__c, Revenue__c, Outsourcing_Start_Date__c, Outsourcing_End_Date__c,
                Consulting_Start_Date__c, Consulting_End_Date__c
                FROM OpportunityLineItem WHERE Id = :oppLineItemId LIMIT 50000];
                
        customSchedules = retrieveSchedules(oppLineItemId);
        
    }
    
    private List<Custom_Schedules__c> retrieveSchedules(String oppLineItemId){
       return [SELECT ScheduleDate__c, Revenue__c,Comment__c, OpportunityLineItemId__c
                FROM Custom_Schedules__c WHERE OpportunityLineItemId__c = :oppLineItemId LIMIT 50000];
    }
    
    public PageReference createSchedules(){
        String oppLineItemId = ApexPages.currentPage().getParameters().get('oppId');
        hasNoSchedules = false;
        
        customSchedules = retrieveSchedules(oppLineItemId);
        
        if(customSchedules.isEmpty() && !oppLineItems.isEmpty() && 
            (oppLineItems[0].Type_of_Work__c.equals(UTIL_Constants.PRODUCT_TYPE_OF_WORK_OUTSOURCING) || oppLineItems[0].Type_of_Work__c.equals(UTIL_Constants.PRODUCT_TYPE_OF_WORK_CONSULTING))){
          
            Map<Id, OpportunityLineItem> mapLineItem = new Map<Id, OpportunityLineItem>();
            mapLineItem.put(oppLineItems[0].Id, oppLineItems[0]);
            
            try{
                RevenueBL.isRevenueScheduled = false;
                RevenueBL.setRevenueSchedule(mapLineItem, UTIL_Constants.OPPLINEITEMHANDLER_LINE_MAP_INSERT);
            } catch(Exception e){
               hasNoSchedules = true; 
            }
            
            if(!hasNoSchedules){
                customSchedules = retrieveSchedules(oppLineItemId);
                if(customSchedules.isEmpty()){
                    hasNoSchedules = true;
                }
            }
        }
        
        return null;
    }

    public PageReference doReturn(){
        String oppLineItemId = ApexPages.currentPage().getParameters().get('oppId');
        pageReference page = new pageReference('https://smartafs--dev02.cs10.my.salesforce.com/'+ oppLineItemId);
        page.setRedirect(true);
        return page;
    }    
    
    public PageReference doCancel(){
        String oppLineItemId = ApexPages.currentPage().getParameters().get('oppId');
        pageReference page = new pageReference('https://smartafs--dev02.cs10.my.salesforce.com/'+ oppLineItemId);
        page.setRedirect(true);
        return page;
    }
    
    
}