AFS_Dev/src/objects/Custom_Error_Messages__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Custom Error Messages</label>
</CustomObject>

AFS_Dev/src/objects/Custom_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Custom_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Custom Revenue</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Line_Item_Id__c</fullName>
        <description>Id of the parent Opportunity Line Item.</description>
        <label>Opportunity Line Item Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Custom Schedules</relationshipLabel>
        <relationshipName>Custom_Schedules</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Schedule_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Schedule Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Custom Schedule</label>
    <nameField>
        <label>Custom Schedules Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Consulting_End__c</fullName>
        <inlineHelpText>Start/End Dates should reflect the base award/booked sale represented by the Total Current Revenue</inlineHelpText>
        <label>Consulting End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Consulting_Start__c</fullName>
        <inlineHelpText>Date the Consulting portion of the contract is expected to begin. Field is required if the Financial Details Related List includes MC, SI, or TC Service Groups.</inlineHelpText>
        <label>Consulting Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_End__c</fullName>
        <inlineHelpText>Date the Outsourcing portion of the contract will be complete.</inlineHelpText>
        <label>Outsourcing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_Start__c</fullName>
        <inlineHelpText>Start/End Dates should reflect the base award/booked sale represented by the Total Current Revenue</inlineHelpText>
        <label>Outsourcing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Current_Revenue__c</fullName>
        <inlineHelpText>The total sales number/booking for the entire opportunity. Total Current Revenue is a read-only field that is populated from the Financial Details Related List.</inlineHelpText>
        <label>Total Current Revenue</label>
        <summarizedField>OpportunityLineItem.Revenue__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <formula>IF(AND(Consulting_Total_Revenue__c&lt;&gt;0, Outsourcing_Total_Revenue__c&lt;&gt;0),&quot;C/O&quot;,
IF(AND(Consulting_Total_Revenue__c=0, Outsourcing_Total_Revenue__c&gt;0), &quot;O&quot;, 
IF(AND(Outsourcing_Total_Revenue__c=0,Consulting_Total_Revenue__c&gt;0), &quot;C&quot;,
IF(AND(Consulting_Total_Revenue__c=0, Outsourcing_Total_Revenue__c=0),&quot;&quot;,&quot;&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type of Work</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Custom_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Custom Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Schedules</relationshipLabel>
        <relationshipName>Opportunity_Schedules</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Opportunity Schedule</label>
    <nameField>
        <displayFormat>OS-{000000}</displayFormat>
        <label>Opportunity Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Consulting_End_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Consulting&apos;, Opportunity.Consulting_End__c,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Consulting End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Consulting_Start_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Consulting&apos;,Opportunity.Consulting_Start__c,null)</formula>
        <label>Consulting Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_End_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Outsourcing&apos;,Opportunity.Outsourcing_End__c,null)</formula>
        <label>Outsourcing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_Start_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Outsourcing&apos;,Opportunity.Outsourcing_Start__c,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outsourcing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>TCR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Service Group</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <label>Type of Work</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

AFS_Dev/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Service Group</label>
        <picklist>
            <picklistValues>
                <fullName>01 - AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02 - BPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03 - IO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 - MC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 - SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 - TC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 - Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 - IC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <label>Type of Work</label>
        <picklist>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outsourcing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AFS_Dev/src/classes/RevenueBL.cls
/**
   @Author Honelee F.Padilla
   @name RevenueBL()
   @CreateDate 04/01/2015
   @Description To auto calculate Revenue Phasing Schedule and reschedule revenue phasing for updated Consulting and Outsourcing Dates.
   @Version 1.0
   @reference <Referenced program names>
  */
public with sharing class RevenueBL {

    public static Boolean isRevenueScheduled = false;

    /**
    *  To calculate revenue phasing schedule dates base on the type of work per product line item.
    *  @name   setRevenueSchedule()
    *  @param  OpportunityLineItem map of old opportunities , newOpportunityLineItemMap   map of current opportunities
    *  @return void
    *  @throws exception-NA
    */
    public static void setRevenueSchedule(Map<Id, OpportunityLineItem> newOpportunityLineItemMap, String origin) {
    
        if (!isRevenueScheduled) {
            isRevenueScheduled = true;
            OpportunityLineItemSchedule[] revenueSchedulesToInsert = new OpportunityLineItemSchedule[]{};
            Custom_Schedule__c[] customSchedulesToInsert = new Custom_Schedule__c[]{}; // Added Recuerdo 11-03-15
            Set<Id> lineItemIds = new Set<Id>{};
            Map<String, Custom_Error_Messages__c> cem = Custom_Error_Messages__c.getAll();
            Decimal revenue_update = UTIL_Constants.DEFAULT_ZERO_DECIMAL;
            
            Map<Id, OpportunityLineItem> oppLineItemMap = 
                new Map<Id, OpportunityLineItem>([SELECT Id, Product2.Name FROM OpportunityLineItem WHERE Id IN:newOpportunityLineItemMap.keySet() LIMIT 50000]);
            
            for (OpportunityLineItem lineItem : newOpportunityLineItemMap.values()) {
                if (lineItem.Revenue__c == null) {
                    revenue_update = UTIL_Constants.DEFAULT_ZERO_DECIMAL;
                }
                else{
                    revenue_update = lineItem.Revenue__c ;
                }
                    if (lineItem.Type_of_Work__c != null) {
                        
                        // Calculate revenue and schedule dates for Outsourcing type of work
                        if (lineItem.Type_of_Work__c.equals(UTIL_Constants.PRODUCT_TYPE_OF_WORK_OUTSOURCING)){
                            if (lineItem.Outsourcing_Start_Date__c <> null && lineItem.Outsourcing_End_Date__c <> null) {
                                Integer installments = lineItem.Outsourcing_Start_Date__c.monthsBetween(lineItem.Outsourcing_End_Date__c) + 1;                  
                                for (Integer i = 0; i < installments; i++) {
                                    revenueSchedulesToInsert.add(
                                        new OpportunityLineItemSchedule(
                                            OpportunityLineItemId = lineItem.Id,
                                            Revenue = (revenue_update / installments).SetScale(2),
                                            ScheduleDate = lineItem.Outsourcing_Start_Date__c.addMonths(i),
                                            Type = UTIL_Constants.SCHEDULE_TYPE_REVENUE
                                            )
                                        );
                                     // -Start- Added Recuerdo 11-03-15
                                     customSchedulesToInsert.add(
                                         new Custom_Schedule__c(
                                             Opportunity__c = lineItem.OpportunityId,
                                             Opportunity_Line_Item_Id__c = lineItem.Id,
                                             Product_Name__c = oppLineItemMap.get(lineItem.Id).Product2.Name,
                                             Revenue__c = (revenue_update / installments).SetScale(2),
                                             Date__c = lineItem.Outsourcing_Start_Date__c.addMonths(i),
                                             Type__c = UTIL_Constants.SCHEDULE_TYPE_REVENUE,
                                             Schedule_Check__c  = false
                                          )
                                     );
                                     // -End-
                                }
                                lineItemIds.add(lineItem.Id);
                            }
                        }
                    // Calculate revenue and schedule dates for Consulting type of work
                        if (lineItem.Type_of_Work__c.equals(UTIL_Constants.PRODUCT_TYPE_OF_WORK_CONSULTING)){
                            if (lineItem.Consulting_Start_Date__c <> null && lineItem.Consulting_End_Date__c <> null) {
                                Integer installments = lineItem.Consulting_Start_Date__c.monthsBetween(lineItem.Consulting_End_Date__c) + 1;
                                for (Integer i = 0; i < installments; i++) {
                                    revenueSchedulesToInsert.add(
                                        new OpportunityLineItemSchedule(
                                            OpportunityLineItemId = lineItem.Id,
                                            Revenue = (revenue_update / installments).SetScale(2),
                                            ScheduleDate = lineItem.Consulting_Start_Date__c.addMonths(i),
                                            Type = UTIL_Constants.SCHEDULE_TYPE_REVENUE
                                            )
                                        );
                                    // -Start- Added Recuerdo 11-03-15
                                    customSchedulesToInsert.add(
                                         new Custom_Schedule__c(
                                             Opportunity__c = lineItem.OpportunityId,
                                             Opportunity_Line_Item_Id__c = lineItem.Id,
                                             Product_Name__c = oppLineItemMap.get(lineItem.Id).Product2.Name,
                                             Revenue__c = (revenue_update / installments).SetScale(2),
                                             Date__c = lineItem.Consulting_Start_Date__c.addMonths(i),
                                             Type__c = UTIL_Constants.SCHEDULE_TYPE_REVENUE,
                                             Schedule_Check__c  = false
                                          )
                                     );
                                     // -End-
                                }
                                lineItemIds.add(lineItem.Id);
                            }  
                        }                   
                    }
    
    
            //Fetch line items to be deleted and inserted
            
               
            //if (!revenueSchedulesToDelete.isEmpty()) delete revenueSchedulesToDelete;
            //if (!revenueSchedulesToInsert.isEmpty()) insert revenueSchedulesToInsert;
            }
            
             try{
                    OpportunityLineItemSchedule[] revenueSchedulesToDelete = [SELECT Id from OpportunityLineItemSchedule 
                                                                          WHERE OpportunityLineItemId IN :lineItemIds ];
                    System.debug(LoggingLevel.ERROR,'----------------revenueSchedulesToDelete'+revenueSchedulesToInsert.size());
                    
                    if (!revenueSchedulesToDelete.isEmpty()){       
                        Database.delete(revenueSchedulesToDelete, true);
                    }
                    if (!revenueSchedulesToInsert.isEmpty()){
                        Database.insert(revenueSchedulesToInsert, true);
                        System.debug(LoggingLevel.ERROR,'--revenueSchedulesToInsert-'+revenueSchedulesToInsert);
                        //revenueSchedulesToInsert = new OpportunityLineItemSchedule[]{};
                    }
                    
                    // -Start- Added Recuerdo 11-03-15
                    Custom_Schedule__c[] customSchedulesToDelete = [SELECT Id from Custom_Schedule__c
                                                                          WHERE Opportunity_Line_Item_Id__c IN :lineItemIds];
                    
                    System.debug(LoggingLevel.ERROR,'----------------customSchedulesToDelete: '+customSchedulesToDelete.size());
                    
                    if (!customSchedulesToDelete.isEmpty()){       
                        Database.delete(customSchedulesToDelete, true);
                    }
                    if (!customSchedulesToInsert.isEmpty()){
                        Database.insert(customSchedulesToInsert, true);
                        System.debug(LoggingLevel.ERROR,'--customSchedulesToInsert-'+customSchedulesToInsert);
                    }
                    // -End-
                    
                } catch(exception e){
                System.debug(LoggingLevel.ERROR,'--Praveen-'+e.getMessage());
            }
        }
    }
    
      
    /**
    *  To get updated Outsourcing and Consulting Dates to reschedule revenue phasing schedule dates.
    *  @name   rescheduleRevenue()
    *  @param  oldOpportunities map of old opportunities , newOpportunities   map of current opportunities
    *  @return void
    *  @throws exception-NA
    */
    public static void rescheduleRevenue(Opportunity[] oldOpportunities, Opportunity[] newOpportunities) {
    
        Set<Id> opportunityIds = new Set<Id>();
        for (Integer i = 0; i < newOpportunities.size(); i++) {
            //Get Outsourcing Dates that were updated
            if (oldOpportunities[i].Outsourcing_Start__c != newOpportunities[i].Outsourcing_Start__c ||
                oldOpportunities[i].Outsourcing_End__c != newOpportunities[i].Outsourcing_End__c) {
                opportunityIds.add(newOpportunities[i].Id);
            }
            //Get Consulting Dates that were updated
            if (oldOpportunities[i].Consulting_Start__c != newOpportunities[i].Consulting_Start__c ||
                oldOpportunities[i].Consulting_End__c != newOpportunities[i].Consulting_End__c ) {
                opportunityIds.add(newOpportunities[i].Id);
            }
        }
        //Fetch Opportunity Line Items fields for mapping
        Map<Id, OpportunityLineItem> newOpportunityLineItemMap = new Map<Id, OpportunityLineItem>([
            SELECT Id, OpportunityId, Type__c, Type_of_Work__c, Revenue__c, Outsourcing_Start_Date__c, 
            Outsourcing_End_Date__c,  Consulting_Start_Date__c, Consulting_End_Date__c
            FROM OpportunityLineItem WHERE OpportunityId IN :opportunityIds]);
        
        //call method to re-calculate revenue schedule
        RevenueBL.setRevenueSchedule(newOpportunityLineItemMap, UTIL_Constants.REVENUE_BL_ORIGIN);
        setOpportunityRevenue(newOpportunityLineItemMap);
    }
    
    public static void setOpportunityRevenue(Map<Id, OpportunityLineItem> newOpportunityLineItemMap){
        Set<Id> oppIds = new Set<Id>();
        
        for(OpportunityLineItem oppLineItem : newOpportunityLineItemMap.values()){
           oppIds.add(oppLineItem.OpportunityId);
        }
    
        Map<Id, Opportunity> oppRecords = new Map<Id, Opportunity>(
            [SELECT Id, Total_Current_Revenue__c, Consulting_Start__c, Consulting_End__c, Outsourcing_Start__c, Outsourcing_End__c FROM Opportunity
            WHERE ID IN :oppIds LIMIT 50000]);
            
        Map<Id, Decimal> tcrMap = new Map<Id, Decimal>();
        for(AggregateResult agg : [SELECT Opportunity.Id oppId, SUM(Revenue__c) newTCR FROM
            OpportunityLineItem WHERE Opportunity.Id IN : oppRecords.keySet() GROUP BY Opportunity.Id LIMIT 50000]){
            tcrMap.put(String.valueOf(agg.get('oppId')), (Decimal)agg.get('newTCR'));
        }
            
        List<Opportunity_Schedule__c> schedules = new List<Opportunity_Schedule__c>();
        Set<Id> oppIdsToDelete = new Set<Id>();
        Date minDate = System.today();
        Date maxDate = System.today();
        for(Opportunity oppRecord : oppRecords.values()){
            System.debug(LoggingLevel.ERROR,'TCR====================== :' + tcrMap.get(oppRecord.Id));
            if(tcrMap.get(oppRecord.Id) > 0 && 
                    ((oppRecord.Consulting_Start__c <> null && oppRecord.Consulting_End__c <> null) || 
                    (oppRecord.Outsourcing_Start__c <> null && oppRecord.Outsourcing_End__c <> null))){
                    
                    minDate = oppRecord.Consulting_Start__c;
                    
                    if(oppRecord.Outsourcing_Start__c <> null && (minDate == null || minDate > oppRecord.Outsourcing_Start__c)){
                        minDate = oppRecord.Outsourcing_Start__c;
                    }
                    
                    maxDate = oppRecord.Consulting_End__c;
                    
                    if(oppRecord.Outsourcing_End__c <> null && (maxDate == null || maxDate < oppRecord.Outsourcing_End__c)){
                        maxDate = oppRecord.Outsourcing_End__c;
                    }
                    
                    Integer installments = minDate.monthsBetween(maxDate) + 1;                  
                    for (Integer i = 0; i < installments; i++) {
                        schedules.add(new Opportunity_Schedule__c(
                            Opportunity__c = oppRecord.Id,
                            Date__c = minDate.addMonths(i),
                            Revenue__c = (tcrMap.get(oppRecord.Id) / installments).SetScale(2),
                            Custom_Revenue__c = 0.00
                            )
                        );
                    }
                    
                    oppIdsToDelete.add(oppRecord.Id);
             }
        }
        
        try{
            List<Opportunity_Schedule__c> schedulesToDelete = [SELECT Id FROM Opportunity_Schedule__c WHERE Opportunity__c IN :oppIdsToDelete LIMIT 50000];
            
            if(!schedulesToDelete.isEmpty()){
                Database.delete(schedulesToDelete, true);
            }
            
            if(!schedules.isEmpty()){
               Database.insert(schedules, true);
               System.debug(LoggingLevel.ERROR,'INSERT====================== :' + schedules.size());
            }
            
        }catch(Exception e){
            System.debug(LoggingLevel.ERROR,e.getMessage());
        }
    }
    
}