AFS_Dev/src/objects/Custom_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Custom Revenue</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Line_Item_Id__c</fullName>
        <description>Id of the parent Opportunity Line Item.</description>
        <label>Opportunity Line Item Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Schedule_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Schedule Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Custom Schedule</label>
    <nameField>
        <label>Custom Schedules Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <formula>IF(AND(Consulting_Total_Revenue__c&lt;&gt;0, Outsourcing_Total_Revenue__c&lt;&gt;0),&quot;C/O&quot;,
IF(AND(Consulting_Total_Revenue__c=0, Outsourcing_Total_Revenue__c&gt;0), &quot;O&quot;, 
IF(AND(Outsourcing_Total_Revenue__c=0,Consulting_Total_Revenue__c&gt;0), &quot;C&quot;,
IF(AND(Consulting_Total_Revenue__c=0, Outsourcing_Total_Revenue__c=0),&quot;&quot;,&quot;&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type of Work</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Consulting_End_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Consulting&apos;, Opportunity.Consulting_End__c,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Consulting End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Consulting_Start_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Consulting&apos;,Opportunity.Consulting_Start__c,null)</formula>
        <label>Consulting Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_End_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Outsourcing&apos;,Opportunity.Outsourcing_End__c,null)</formula>
        <label>Outsourcing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outsourcing_Start_Date__c</fullName>
        <formula>If (Type_of_Work__c=&apos;Outsourcing&apos;,Opportunity.Outsourcing_Start__c,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outsourcing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>TCR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Service Group</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <label>Type of Work</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

AFS_Dev/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Service Group</label>
        <picklist>
            <picklistValues>
                <fullName>01 - AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02 - BPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03 - IO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 - MC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 - SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 - TC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 - Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 - IC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <label>Type of Work</label>
        <picklist>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outsourcing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AFS_Dev/src/classes/ScheduleExt.cls
public with sharing class ScheduleExt {
    public List<OpportunityLineItem> oppLineItems {get; set;}
    public List<Custom_Schedule__c> customSchedules {get; set;}
    public boolean hasNoSchedules {get; set;}
    public String totalRevenue {get; set;}
    public String totalCustomRevenue {get; set;}
    
    /**
    * Constructor for ScheduleExt Class.
    * @param ApexPages.StandardController stdcontroller.
    * @return void
    */
    public ScheduleExt(ApexPages.StandardController stdcontroller) {
        customSchedules = new List<Custom_Schedule__c>();
        Id oppLineItemId = ApexPages.currentPage().getParameters().get('oppId');
        
        oppLineItems =
            [SELECT Id, Opportunity.Name, Product2.Name, Type_of_Work__c, Revenue__c, Outsourcing_Start_Date__c, Outsourcing_End_Date__c,
                Consulting_Start_Date__c, Consulting_End_Date__c
                FROM OpportunityLineItem WHERE Id = :oppLineItemId LIMIT 50000];
                
        customSchedules = retrieveSchedules(oppLineItemId);
        
        Decimal customRevenue = 0;
        
        for(Custom_Schedule__c customSchedule: customSchedules){
            customRevenue += customSchedule.Custom_Revenue__c;
        }
        
        totalRevenue = oppLineItems[0].Revenue__c.format() + '.' + String.valueOf(oppLineItems[0].Revenue__c.setScale(2)).split('\\.')[1];
        totalCustomRevenue = customRevenue.format() + '.' + String.valueOf(customRevenue.setScale(2)).split('\\.')[1];
        
    }
    
    private List<Custom_Schedule__c> retrieveSchedules(String oppLineItemId){
       return [SELECT Date__c, Revenue__c, Comment__c, Type__c, Opportunity_Line_Item_Id__c, Schedule_Check__c, Custom_Revenue__c
                FROM Custom_Schedule__c WHERE Opportunity_Line_Item_Id__c = :oppLineItemId LIMIT 50000];
    }
    
    public PageReference createSchedules(){
        Id oppLineItemId = ApexPages.currentPage().getParameters().get('oppId');
        hasNoSchedules = false;
        
        customSchedules = retrieveSchedules(oppLineItemId);
        
        if(customSchedules.isEmpty() && !oppLineItems.isEmpty() && 
            (oppLineItems[0].Type_of_Work__c.equals(UTIL_Constants.PRODUCT_TYPE_OF_WORK_OUTSOURCING) || oppLineItems[0].Type_of_Work__c.equals(UTIL_Constants.PRODUCT_TYPE_OF_WORK_CONSULTING))){
          
            Map<Id, OpportunityLineItem> mapLineItem = new Map<Id, OpportunityLineItem>();
            mapLineItem.put(oppLineItems[0].Id, oppLineItems[0]);
            
            try{
                RevenueBL.isRevenueScheduled = false;
                RevenueBL.setRevenueSchedule(mapLineItem, UTIL_Constants.OPPLINEITEMHANDLER_LINE_MAP_INSERT);
            } catch(Exception e){
               hasNoSchedules = true; 
            }
            
            if(!hasNoSchedules){
                customSchedules = retrieveSchedules(oppLineItemId);
                if(customSchedules.isEmpty()){
                    hasNoSchedules = true;
                }
            }
        }
        
        return null;
    }

    public PageReference doReturn(){
        String oppLineItemId = ApexPages.currentPage().getParameters().get('oppId');
        pageReference page = new pageReference('https://smartafs--dev.cs10.my.salesforce.com/'+ oppLineItemId);
        page.setRedirect(true);
        return page;
    }    
    
    public PageReference doCancel(){
        String oppLineItemId = ApexPages.currentPage().getParameters().get('oppId');
        pageReference page = new pageReference('https://smartafs--dev.cs10.my.salesforce.com/'+ oppLineItemId);
        page.setRedirect(true);
        return page;
    }
    
    public PageReference save() {
    
        Decimal newTotalRevenue = 0;
        
        for(Custom_Schedule__c customSched: customSchedules) {
            newTotalRevenue += customSched.Custom_Revenue__c;
        }
        
        totalCustomRevenue = newTotalRevenue.format() + '.' + String.valueOf(newTotalRevenue.setScale(2)).split('\\.')[1];
        
        if(newTotalRevenue > oppLineItems[0].Revenue__c){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'New Total Revenue Exceeds $' +oppLineItems[0].Revenue__c));
        }
        else{
            Database.update(customSchedules);
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Update Successful!'));
        }
        return null;
    }

        
    
}