AFS_Dev/src/objects/Custom_Error_Messages__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <label>Custom Error Messages</label>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Team_Roles__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Team Roles</label>
        <referenceTo>Opportunity_Team_Roles__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity_Team_Roles__c.object
<CustomObject>
    <description>This is an object for the Opportunity Team and Sales Credit Records.</description>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Name</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Opportunity Team Roles</relationshipLabel>
        <relationshipName>Opportunity_Teams_Sales_Credit</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <inlineHelpText>Salesforce License is required for access to be applicable.</inlineHelpText>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Teams_Sales_Credit</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Alliance Business Development Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capture Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Management Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deal Shaper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horizontal Business Development Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key Member of Opp.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity QA Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRG Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Architect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Credit__c</fullName>
        <label>Sales Credit %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Opportunity Team Roles</label>
    <nameField>
        <displayFormat>ID-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Team Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/objects/OpportunityTeamMember.object
<CustomObject>
    <fields>
        <fullName>Custom_Opportunity_Id__c</fullName>
        <label>Custom Opportunity Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

AFS_Dev/src/objects/Person__c.object
<CustomObject>
    <description>This object is taking place of the user object where user names will be stored.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stores Active Directory user status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AFS_Dev/src/classes/OpportunityTeamRoleBL.cls
/**
   @Author Honelee F. Padilla
   @name OpportunityTeamRoleBL
   @CreateDate 04/10/2015
   @Description To copy custom Opportunity Team Roles in standard Opportunity Team and OpportunityShare 
   @Version <1.0>
   @reference <Referenced program names>
  */
public without sharing class OpportunityTeamRoleBL {

    /**
    *  To delete Opportunity Team and copy over the Access level in standard Opportunity Team and OpportunityShare 
    *  @name deleteOpportunityTeam
    *  @param teamRolesToDelete - Team roles for deletion
    *  @return void
    *  @throws exception
    */
    public static void deleteOpportunityTeam(Opportunity_Team_Roles__c[] teamRolesToDelete){

        integer rw = 0;    
        Set<String> teamRoleIds = new Set<String>();
        Map<Id, String> personMap = new Map<Id, String>{};
        Map<String, User> userMap = new Map<String, User>{};
        Set<Id> userIds = new Set<Id>();
        Set<Id> opportunityIds = new Set<Id>();
        OpportunityShare[] opportunitySharesToDelete = new OpportunityShare[]{};
        OpportunityShare[] opportunitySharesToInsert = new OpportunityShare[]{};
        OpportunityTeamMember[] teamMembersToDelete = new OpportunityTeamMember[]{};
        OpportunityTeamMember[] teamMembersToInsert = new OpportunityTeamMember[]{};
        Map<String, OpportunityShare> shareDeleteMap = new Map<String, OpportunityShare>{};
        Map<String, Opportunity_Team_Roles__c[]> dupeTeamRoleMap = new Map<String, Opportunity_Team_Roles__c[]>{};
        
        for(Opportunity_Team_Roles__c team : teamRolesToDelete){
            personMap.put(team.Name__c, null);
            opportunityIds.add(team.Opportunity_Name__c);
            teamRoleIds.add(team.Id);  
        }
        
        for (Person__c person : [SELECT Id, Email__c FROM Person__c WHERE Status__c = :UTIL_Constants.PERSON_STATUS AND Id IN :personMap.keyset() LIMIT 5000]){// Default maximum of SOQL rows to 5000
            personMap.put(person.Id, person.Email__c);
        }
        
        for (User usr : [
            SELECT Id, Email FROM User
            WHERE IsActive = true
            AND Email IN :personMap.values()
            LIMIT 5000 // Default maximum of SOQL rows to 5000
        ]){
            userMap.put(usr.Email, usr);
        }
        
        for (User usr : [
            SELECT Id, Email FROM User
            WHERE IsActive = true
            AND Email IN :personMap.values()
            LIMIT 5000 // Default maximum of SOQL rows to 5000
        ]){
            userIds.add(usr.Id);
        }
                
        teamMembersToDelete = [
            SELECT OpportunityId, UserId, TeamMemberRole, Custom_Opportunity_Id__c
            FROM OpportunityTeamMember 
            WHERE Custom_Opportunity_Id__c IN: teamRoleIds
            LIMIT 5000 // Default maximum of SOQL rows to 5000
        ];
        
        for(OpportunityShare share: [
            SELECT UserOrGroupId,OpportunityId,Id 
            FROM OpportunityShare 
            WHERE UserOrGroupId IN: userIds 
            AND OpportunityId IN: opportunityIds
            LIMIT 5000 // Default maximum of SOQL rows to 5000
        ]){
            shareDeleteMap.put(share.UserOrGroupId+ UTIL_Constants.PIPE +share.OpportunityId, share);
        }
        
        for(Opportunity_Team_Roles__c share: [
            SELECT Name__c, Opportunity_Name__c, Opportunity_Access__c, Id , Role__c
            FROM Opportunity_Team_Roles__c 
            WHERE Name__c IN :personMap.keyset()
            AND Opportunity_Name__c IN: opportunityIds
            AND ID NOT IN :teamRoleIds
            LIMIT 5000 // Default maximum of SOQL rows to 5000
        ]){
            if (!dupeTeamRoleMap.containsKey(share.Name__c+ UTIL_Constants.PIPE +share.Opportunity_Name__c)) {
                dupeTeamRoleMap.put(share.Name__c+ UTIL_Constants.PIPE +share.Opportunity_Name__c, new Opportunity_Team_Roles__c[]{share});
            }
            dupeTeamRoleMap.get(share.Name__c+ UTIL_Constants.PIPE +share.Opportunity_Name__c).add(share);
        }
        // Get duplicate names but with diff roles
        for(Opportunity_Team_Roles__c team: teamRolesToDelete){
            if(shareDeleteMap.get(team.Name__c + UTIL_Constants.PIPE + team.Opportunity_Name__c) <> null){
                opportunitySharesToDelete.add(shareDeleteMap.get(team.Name__c + UTIL_Constants.PIPE + team.Opportunity_Name__c));
            }
            if (dupeTeamRoleMap.containsKey(team.Name__c + UTIL_Constants.PIPE + team.Opportunity_Name__c)) {
                for (Opportunity_Team_Roles__c role : dupeTeamRoleMap.get(team.Name__c + UTIL_Constants.PIPE + team.Opportunity_Name__c)) { 
                    if(role.Opportunity_Access__c.equals(UTIL_Constants.OPPORTUNITY_ACCESS_READWRITE)){
                        System.debug('Read Write');
                        OpportunityShare sharet = new OpportunityShare();
                        sharet.OpportunityId = role.Opportunity_Name__c;
                        sharet.OpportunityAccessLevel = UTIL_Constants.OPPORTUNITY_ACCESS_EDIT;
                        if (personMap.containsKey(team.Name__c)) {
                            if (userMap.containsKey(personMap.get(team.Name__c))) {
                                sharet.UserOrGroupId = userMap.get(personMap.get(team.Name__c)).Id; 
                            }
                        }
                        opportunitySharesToInsert.add(sharet);
                        //break;
                    }
                    
                    // Get name with Read/Write access
                    if(role.Opportunity_Access__c.equals(UTIL_Constants.OPPORTUNITY_ACCESS_READWRITE)){
                        System.debug('Read Write access');
                        OpportunityTeamMember member = new OpportunityTeamMember();
                        member.OpportunityId = role.Opportunity_Name__c;
                        member.TeamMemberRole = role.Role__c;
                        if (personMap.containsKey(team.Name__c)) {
                            if (userMap.containsKey(personMap.get(team.Name__c))) {
                                member.UserId = userMap.get(personMap.get(team.Name__c)).Id;
                            }
                        }

                        teamMembersToInsert.add(member);
                        rw = rw + 1;
                        //break;
                    }
                    
                    // Get name with Read only access                  
                    if(rw == 0){
                        if(role.Opportunity_Access__c.equals(UTIL_Constants.OPPORTUNITY_ACCESS_READONLY)){
                            System.debug('Read Only access');
                            OpportunityTeamMember member = new OpportunityTeamMember();
                            member.OpportunityId = role.Opportunity_Name__c;
                            member.TeamMemberRole = role.Role__c;
                            if (personMap.containsKey(team.Name__c)) {
                                if (userMap.containsKey(personMap.get(team.Name__c))) {
                                    member.UserId = userMap.get(personMap.get(team.Name__c)).Id;
                                }
                            }
                            teamMembersToInsert.add(member);
                        }
                    }           
                }
            }
        }
        
        try{
        
            database.delete(teamMembersToDelete,false);
            database.delete(opportunitySharesToDelete,false);
            database.insert(teamMembersToInsert,false);
            database.insert(opportunitySharesToInsert,false);
         } catch(exception e){
            System.debug(e.getMessage());
        }
    }

    /**
    *  To upsert Opportunity Team and copy over the Access level in standard Opportunity Team and OpportunityShare 
    *  @name upsertOpportunityTeam
    *  @param upsertedTeamRoles - Team Roles to be upserted
    *  @return void
    *  @throws exception
    */    
    public static void upsertOpportunityTeam(Opportunity_Team_Roles__c[] upsertedTeamRoles, Boolean isUpdate){
       
        OpportunityTeamMember[] teamMembersToInsert = new OpportunityTeamMember[]{};
        OpportunityTeamMember[] teamMembersToDelete = new OpportunityTeamMember[]{};
        OpportunityShare[] opportunitySharesToInsert = new OpportunityShare[]{};
        OpportunityShare[] opportunitySharesToDelete = new OpportunityShare[]{};
        Map<String, OpportunityShare> shareDeleteMap = new Map<String, OpportunityShare>();
        Map<Id, String> personMap = new Map<Id, String>{};
        Map<String, User> userMap = new Map<String, User>{};
        Set<String> teamRoleIds = new Set<String>();
        Set<Id> userIds = new Set<Id>();
        Set<Id> opportunityIds = new Set<Id>();
    
        for(Opportunity_Team_Roles__c team: upsertedTeamRoles){
            personMap.put(team.Name__c, null);
            opportunityIds.add(team.Opportunity_Name__c);
            teamRoleIds.add(team.Id); 
        }
        
        for (Person__c person : [SELECT Id, Email__c FROM Person__c WHERE Status__c = :UTIL_Constants.PERSON_STATUS AND Id IN :personMap.keyset() LIMIT 5000]){ // Default maximum of SOQL rows to 5000
            personMap.put(person.Id, person.Email__c);
        }
        
        for (User usr : [
            SELECT Id, Email FROM User
            WHERE IsActive = true
            AND Email IN :personMap.values()
            LIMIT 5000
         // Default maximum of SOQL rows to 5000
        ]){
            userMap.put(usr.Email, usr);
        }
        
        for(Opportunity_Team_Roles__c team: upsertedTeamRoles){
            OpportunityTeamMember member = new OpportunityTeamMember();  
            member.OpportunityId = team.Opportunity_Name__c;  
            member.TeamMemberRole = team.Role__c;
            member.Custom_Opportunity_Id__c = team.Id;
            if (personMap.containsKey(team.Name__c)) {
                if (userMap.containsKey(personMap.get(team.Name__c))) {
                    member.UserId = userMap.get(personMap.get(team.Name__c)).Id;
                }
            }
            teamMembersToInsert.add(member);
            
            //Grant New Team Member with Edit Access via Opportunity ShareTable
            if(team.Opportunity_Access__c.equals(UTIL_Constants.OPPORTUNITY_ACCESS_READWRITE)){
                System.debug('Read Write');
                OpportunityShare sharet = new OpportunityShare();
                sharet.OpportunityId = team.Opportunity_Name__c;
                sharet.OpportunityAccessLevel = UTIL_Constants.OPPORTUNITY_ACCESS_EDIT;
                if (personMap.containsKey(team.Name__c)) {
                    if (userMap.containsKey(personMap.get(team.Name__c))) {
                        sharet.UserOrGroupId = userMap.get(personMap.get(team.Name__c)).Id; 
                    }
                }
                opportunitySharesToInsert.add(sharet);
            }
            
            //Update Team Member with Read Access via Opportunity ShareTable
            if(team.Opportunity_Access__c.equals(UTIL_Constants.OPPORTUNITY_ACCESS_READONLY)){
                System.debug('Read Write');
                OpportunityShare sharet = new OpportunityShare();
                sharet.OpportunityId = team.Opportunity_Name__c;
                sharet.OpportunityAccessLevel = UTIL_Constants.OPPORTUNITY_ACCESS_READ;
                if (personMap.containsKey(team.Name__c)) {
                    if (userMap.containsKey(personMap.get(team.Name__c))) {
                        sharet.UserOrGroupId = userMap.get(personMap.get(team.Name__c)).Id; 
                    }
                }
                opportunitySharesToInsert.add(sharet);
            }
            
        }
        
        if(isUpdate){
            //Standard OpportunityTeamMember Opportunity and User fields are not updatable in Apex. 
            //Workaround is to delete the existing Opp team member and toreinsert the update Opp team Member
            teamMembersToDelete = [
                SELECT OpportunityId, UserId, TeamMemberRole, Custom_Opportunity_Id__c 
                FROM OpportunityTeamMember 
                WHERE Custom_Opportunity_Id__c IN: teamRoleIds
                LIMIT 5000 // Default maximum of SOQL rows to 5000
            ];
            
            
            for(OpportunityShare share: [SELECT UserOrGroupId,OpportunityId,Id FROM OpportunityShare WHERE UserOrGroupId IN: userIds AND 
                                          OpportunityId IN: opportunityIds LIMIT 5000]){ // Default maximum of SOQL rows to 5000
                shareDeleteMap.put(share.UserOrGroupId+ UTIL_Constants.PIPE +share.OpportunityId, share);
            }
            
            for(Opportunity_Team_Roles__c upsertedTeamRole: upsertedTeamRoles){
                if(shareDeleteMap.get(upsertedTeamRole.Name__c + UTIL_Constants.PIPE + upsertedTeamRole.Opportunity_Name__c ) <> NULL){
                    opportunitySharesToDelete.add(shareDeleteMap.get(upsertedTeamRole.Name__c + UTIL_Constants.PIPE + upsertedTeamRole.Opportunity_Name__c ));
                }
            }
        }
            
        try{
            if(isUpdate){       
                database.Delete(teamMembersToDelete,false);
                database.Delete(opportunitySharesToDelete,false);
            }
           
            database.insert(teamMembersToInsert,false);
            database.insert(opportunitySharesToInsert,false);
            
        } catch(exception e){
            System.debug(e.getMessage());
        }
    }

    /**
    *  To validate and update the Sales Credit of the Opportunity Team Role
    *  @name validateSalesCredit
    *  @param newOppTeam - New Opportunity Team Roles to validate sales credit
    *  @return void
    *  @throws no exception
    */
    public static void validateSalesCredit (Map<Id, Opportunity_Team_Roles__c> newOppTeam) {
        System.debug('passClass');
        set<id> oTRoleSet = new set<id>();
                
        for (Opportunity_Team_Roles__c OTRole: newOppTeam.values()){
            oTRoleSet.add(OTRole.Opportunity_Name__c);
        }
         List <Opportunity> opp = new List <Opportunity>([
             select id ,(select id, name__c, role__c, sales_credit__c,Opportunity_Name__c from Opportunity_Teams_Sales_Credit__r LIMIT 5000)// Default maximum of SOQL rows to 5000
             from opportunity where id in:oTRoleSet LIMIT 5000]) ;// Default maximum of SOQL rows to 5000
        
        Map <String,decimal> roleMapCredit = new Map<String,decimal>();
        Map <String,decimal> userMapCredit = new Map<String,decimal>();
        
        Map<String, Custom_Error_Messages__c> cem = Custom_Error_Messages__c.getAll();
        
        for(Opportunity Op: Opp ) {
            roleMapCredit = new Map<String,decimal>();
            userMapCredit = new Map<String,decimal>();
            
            for(Opportunity_Team_Roles__c otr: Op.Opportunity_Teams_Sales_Credit__r){
       
                if(roleMapCredit.get(otr.role__c) <> NULL && otr.Sales_Credit__c <> NULL) {
                    if((roleMapCredit.get(otr.role__c) + otr.sales_credit__c) > 100){
                        System.debug('---------roleMapCredit.get(otr.role__c)'+roleMapCredit.get(otr.role__c));
                        System.debug('---------roleMapCredit.get(otr.sales_credit__c)'+otr.sales_credit__c);
                        //newOppTeam.get(otr.Id).AddError('limit exceeded on role');
                        for(Opportunity_Team_Roles__c c: newOppTeam.values()){
                         System.debug('--------- c='+ otr.Opportunity_Name__c);
                            System.debug('--------- c='+ Op.Id);
                            if(c.Opportunity_Name__c == Op.Id){
                                System.debug('--------- otr.Opportunity_Name__c='+ otr.Opportunity_Name__c);        
                                c.addError(cem.get(UTIL_Constants.ERROR_MSG_TEA_016).Error_Message__c);
                                
                            }
                        }
                    } else{
                        roleMapCredit.put(otr.role__c, (roleMapCredit.get(otr.role__c) + otr.sales_credit__c));
                      
                        
                    }
                }else {
                    roleMapCredit.put(otr.role__c, otr.sales_credit__c);
                }
                
                if(userMapCredit.get(otr.name__c)<> NULL && otr.Sales_Credit__c <> NULL){
                    if((userMapCredit.get(otr.name__c)+otr.sales_credit__c) > 100){
                        System.debug('>>from user' + otr.name__c);
                        System.debug('>>from user' + (userMapCredit.get(otr.name__c)+otr.sales_credit__c));
                        
                        for(Opportunity_Team_Roles__c c: newOppTeam.values()){
                         
                            if(c.Opportunity_Name__c == Op.Id){
                                //c.AddError(UTIL_Constants.ERROR_LIMIT_USER);
                                c.addError(cem.get(UTIL_Constants.ERROR_MSG_TEA_013).Error_Message__c);
                            }
                        }
                    }else {
                        userMapCredit.put(otr.name__c, (userMapCredit.get(otr.name__c) + otr.sales_credit__c));
                    }
                }else {
                    userMapCredit.put(otr.name__c, otr.Sales_Credit__c);
                }
                
            }
        }
    }
               
}