AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Reporting_Status__c</fullName>
        <inlineHelpText>Field updated based on the stage of the opportunity through workflow. Reporting Status is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status</label>
        <picklist>
            <controllingField>Approved_Status_Stage__c</controllingField>
            <picklistValues>
                <fullName>Lost</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
                <color>#A845DC</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <formula>IF(AND(Consulting_Total_Revenue__c&lt;&gt;0, Outsourcing_Total_Revenue__c&lt;&gt;0),&quot;C/O&quot;,
IF(AND(Consulting_Total_Revenue__c=0, Outsourcing_Total_Revenue__c&gt;0), &quot;O&quot;, 
IF(AND(Outsourcing_Total_Revenue__c=0,Consulting_Total_Revenue__c&gt;0), &quot;C&quot;,
IF(AND(Consulting_Total_Revenue__c=0, Outsourcing_Total_Revenue__c=0),&quot;&quot;,&quot;&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type of Work</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Target_OI__c</fullName>
        <label>Target OI%</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Service Group</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <label>Type of Work</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

AFS_Dev/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Target_OI__c</fullName>
        <label>Target OI%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Service Group</label>
        <picklist>
            <picklistValues>
                <fullName>01 - AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02 - BPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03 - IO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 - MC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 - SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 - TC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 - Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 - IC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Work__c</fullName>
        <label>Type of Work</label>
        <picklist>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outsourcing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

AFS_Dev/src/classes/ProductBL.cls
/**
   @Author Pablito M. Abalos Jr.
   @name ProductBL
   @CreateDate 3/4/2015
   @Description Update All Service Groups, Type of Work and Targer OI% in product level
   @Version <1.0>
   @reference
  */
public class ProductBL{

    /**
    *  Retrived opportunity product fields Service Group, Type of work and Target OI % on all open Opportunity record. 
    *  @name updateTargetOI
    *  @param Product2[] , Product2[]
    *  @return <parameter> - <Description about the return parameter>
    *  @throws exception-<exception description>
    */
    public static void updateTargetOI(Product2[] oldProducts, Product2[] newProducts){
      //OpportunityLineItem[] oppItemNew = new OpportunityLineItem[]{};
       // Set<ID> prods = new Set<ID>();
        Map<Id, Product2> updatedProductMap = new Map<Id, Product2>{};
        
        for (Integer i = 0; i < newProducts.size(); i++) {
            if (oldProducts[i].Target_OI__c != newProducts[i].Target_OI__c || oldProducts[i].Type__c != newProducts[i].Type__c || oldProducts[i].Type_of_Work__c != newProducts[i].Type_of_Work__c) {
                updatedProductMap.put(newProducts[i].Id, newProducts[i]);
            }
        }
        
      OpportunityLineItem[] opportunityLineItemsToUpdate = [SELECT Id, Target_OI__c, Product2Id, PricebookEntryId
                                                                FROM OpportunityLineItem 
                                                                WHERE Opportunity.IsClosed = false and OpportunityId in : [SELECT Id FROM Opportunity WHERE Reporting_Status__c not in (:UTIL_Constants.STAGENAME_CLIENT_WITHDREW, :UTIL_Constants.STAGENAME_AFS_WITHDREW, :UTIL_Constants.STAGENAME_WON, :UTIL_Constants.STAGENAME_LOST, :UTIL_Constants.STAGENAME_CLOSED) LIMIT 5000] 
                                                                AND Product2Id In :updatedProductMap.keyset() ORDER BY Product2Id LIMIT 5000];
      
      for (OpportunityLineItem opportunityLineItemToUpdate : opportunityLineItemsToUpdate) {
        opportunityLineItemToUpdate.Target_OI__c = updatedProductMap.get(opportunityLineItemToUpdate.Product2Id).Target_OI__c;
        opportunityLineItemToUpdate.Type__c = updatedProductMap.get(opportunityLineItemToUpdate.Product2Id).Type__c;
        opportunityLineItemToUpdate.Type_of_Work__c = updatedProductMap.get(opportunityLineItemToUpdate.Product2Id).Type_of_Work__c;
      }
      
      Integer counter = 0;
        for (Database.SaveResult sr : Database.update(opportunityLineItemsToUpdate, false)) {
            if (!sr.isSuccess()) {
                //Database.Error err = ;
                //newProducts[counter].addError(err.getStatusCode() + ': ' + err.getMessage());
                updatedProductMap.get(opportunityLineItemsToUpdate[counter].Product2Id).addError(sr.getErrors()[0].getStatusCode() + ': ' + sr.getErrors()[0].getMessage() + '[ERROR RECORD : ' + opportunityLineItemsToUpdate[counter].Id + ']');
            }
            counter++;
        }
    }
}