AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Team_Roles__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Team Roles</label>
        <referenceTo>Opportunity_Team_Roles__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Salesforce</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>STaR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity_Team_Roles__c.object
<CustomObject>
    <description>This is an object for the Opportunity Team and Sales Credit Records.</description>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Teams_Sales_Credit</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Team Roles</label>
    <nameField>
        <displayFormat>ID-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Team Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/classes/UpdateOpportunityTeamBatch.cls
global class UpdateOpportunityTeamBatch implements Database.Batchable<sObject> {

public static final String FIN_BATCHQUERY = 'SELECT Id from Opportunity_Team_Roles__c where Opportunity_Name__r.Source__c = \'STaR\''; 

    /* Start method of Interface */
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = FIN_BATCHQUERY;
        return Database.getQueryLocator(query); 
    }
    
    /* Script statements to run on scope */
    global void execute(Database.BatchableContext BC, List<sObject> oppTeamList) {
       database.update(oppTeamList, false); 
    }
    
    /* Any post-processing will be run here */
    global void finish(Database.BatchableContext BC) {
    
    }
}